### ISSUE TITLE
How to make sure that my dynamic/server-side sitemap is only generated once a day?

### ISSUE THREAD

**Issue by jonasatmonday** [iamvishnusankar/next-sitemap#106]
Hello,

first of all, thanks a lot for creating and maintaining this project!

For our application, we create both a static sitemap of a couple of static pages and a dynamic sitemap of pages created from a CMS. 

I followed the guide for creating a dynamic sitemap under /pages/server-sitemap.xml/index.tsx by fetching all the dynamic content from the CMS. During testing, I realized that the dynamic sitemap is rendered from scratch whenever the sitemap is accessed. We have caching in place for our content-fetching but I would still like only generate the sitemap daily.

Is there an option for this already that I missed or is such a feature planned for the future?

Best regards,
Jonas

**Comment by LorhanSohaky** [comment]
How did you solve this?

**Comment by jonasatmonday** [comment]
Hello @LorhanSohaky,
we solved it without next-sitemap and with NextJS-features alone. Instead, we created an api-route and a route rewrite from xxx/sitemap.xml to our api-route. The api-route generates the sitemap XML. We then use the cache-control headers so that our middleware caches the sitemap XML for 24h. Sitemap regeneration is only triggered by the first request after 24h.

**Comment by iamvishnusankar** [comment]
@jonasatmonday Sorry for the late response. And thanks @Xetera for mention this issue. 

Since we have access to full `ctx` object, we can add custom `Cache-Control` headers like this. No need to write custom API Routes for generating dynamic sitemaps.

```ts
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // Fields
  const fields = []

  // Set headers
  ctx?.res?.setHeader('custom-header-key-1', 'custom-header-value-1')
  ctx?.res?.setHeader('custom-header-key-2', 'custom-header-value-2')

  return getServerSideSitemap(ctx, fields)
}
```

**Comment by josegoval** [comment]
@iamvishnusankar this solution does not protect against DDOS attacks. Maybe a crawler can "cache" something -and am not sure about it at all-, but any simple program can run lots of request to this endpoint to collapse your website. 

It should be anyway to control this to prevent it.

**Comment by Xetera** [comment]
I don't think getStaticProps would work because the sitemap needs to be written directly to the response, not passed to a react component
