### ISSUE TITLE
How to Return Full Path?

### ISSUE THREAD

**Issue by darrylmorley** [iamvishnusankar/next-sitemap#113]
Hi,

First of all thank you for creating this!

Is it possible to have the full path returned in my sitemap.xml please?

For example, current path returned: `https://shootingsuppliesltd.co.uk/accessories/4578`, the actual path is:  `https://shootingsuppliesltd.co.uk/accessories/4578?slug=napier-apex-auto-click`.

**Comment by iamvishnusankar** [comment]
@darrylmorley  `next-sitemap` relies on build manifest to generate sitemaps for static/pre-rendered pages. So, It is not possible to export query params with static sitemap path.

However, you can use `getServerSideSitemap` api and build custom sitemap path based on your needs.

**Comment by darrylmorley** [comment]
OK, thank you for the quick response! I'll try the getServerSideSitemap 👍
