### ISSUE TITLE
Excluding pages is not working properly with i18n

### ISSUE THREAD

**Issue by BjoernRave** [iamvishnusankar/next-sitemap#115]
When using different locales, the `exclude` array will only exclude the urls from the baseUrl, but not the localized routes.

So if I have:
```
"exclude": ["/foo"]
```

it wil exclude `/foo`, but there will still be an entry for `/en/foo`

**Comment by iamvishnusankar** [comment]
@BjoernRave Exclusion logic using [matcher](https://www.npmjs.com/package/matcher#usage) library to detect matches. In your case, `/foo` doesn't match with `/en/foo` hence the url being included in the package. Try to exclude using `/*/foo` or `*foo`.
