### ISSUE TITLE
Is there a way to generate a sitemap when using a custom dist folder? 

### ISSUE THREAD

**Issue by aegiz** [iamvishnusankar/next-sitemap#117]
**Describe the bug**

In our Next.js project we have defined a custom dist folder. Here is the content of `next.config.js`
```js
module.exports = {
    distDir: 'build',
};
```

As in  #91 this is triggering an error in node_modules/next-sitemap/dist/cjs/url/create-url-set/index.js 

**To Reproduce**

1. Run next build in build and next-sitemap in postbuild
2. Wait for it to build
3. See error

**Expected behavior**

Should generate a manifest.

=> So my question is: is there an actual way to use this Npm package if a custom dist folder has been defined?

**Comment by iamvishnusankar** [comment]
@aegiz Just set the `sourceDir` property to `dist`. By default `next-sitemap` looks for file in `.next` directory. You can override this by using `sourceDir` prop in `next-sitemap.js`

**Comment by aegiz** [comment]
Dang, you are absolutely right! Thank you so much for your quick answer it works now.
