### ISSUE TITLE
npm i error

### ISSUE THREAD

**Issue by zss1004504439** [iamvishnusankar/next-sitemap#122]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24915880/112285956-d1215280-8cc5-11eb-8890-ad1b4684c522.png)

**Comment by iamvishnusankar** [comment]
@zss1004504439 It might be some NPM server error. The version does exist though: https://www.npmjs.com/package/@corex/deepmerge/v/2.5.6

**Comment by zss1004504439** [comment]
use yarn
![image](https://user-images.githubusercontent.com/24915880/112297795-421a3780-8cd1-11eb-9733-fd0ed0139ee7.png)
How?

**Comment by zss1004504439** [comment]
update dependencies
![image](https://user-images.githubusercontent.com/24915880/112299385-b6090f80-8cd2-11eb-8362-23ec9753800f.png)
How  2.56 down 2.4.24
