### ISSUE TITLE
The default locale folder is not removed from url generated in the sitemap

### ISSUE THREAD

**Issue by giovannetti-eric** [iamvishnusankar/next-sitemap#127]
**Describe the bug**
When I generate a sitemap with a default locale (I'm using Next 10), the urls in the sitemap have the default locale in the path but the real urls don't have one.

https://nextjs.org/docs/advanced-features/i18n-routing

eg: 
- This url don't have a /fr folder: https://lafondcpa.ca/nous-joindre
- [In the sitemap](https://lafondcpa.ca/sitemap.xml), the generated url is https://lafondcpa.ca/fr/nous-joindre

**To Reproduce**
Use a default locale in your next.config.js, and generate the sitemap with `npm run build`.

_next.config.js_
``` js
 i18n: {
    // These are all the locales you want to support in
    // your application
    locales: ["fr"],
    // This is the default locale you want to be used when visiting
    // a non-locale prefixed path e.g. `/hello`
    defaultLocale: "fr",
  }
```

**Expected behavior**
I expect the urls generated by the sitemap from the default locale to not have the locale in the path.

**Comment by gyoon-dev** [comment]
@giovannetti-eric 
Found your question after searching for similars issues that I have been running into.
https://github.com/iamvishnusankar/next-sitemap/issues/134

Are you using Vercel to build your Next project?
I have noticed that Vercel prepends [dynamic] routes with the default locale and am wondering if these issues could be related.

**Comment by rintala** [comment]
Would be awesome if this fix could get implemented!
