### ISSUE TITLE
Question: is there a way to control the [dynamic] urls generated when using with Next i18n and Vercel?

### ISSUE THREAD

**Issue by gyoon-dev** [iamvishnusankar/next-sitemap#134]
Thanks for the great package 👏

When using Next i18n routing
https://nextjs.org/docs/advanced-features/i18n-routing

and building with Vercel, Vercel creates [dynamic] urls prepended with the i18n locale.

The sitemap generated also contains urls prepended with the i18n locale.

Is there a way to control this? Or a best practice when generating the static sitemap?

Thank you again.

**Comment by toiluj23** [comment]
Hi, I have an issue related to this, perhaps you can help me:
When I check the last sitemap.xml it is generating dynamicl url this way:
`<url><loc>https://<URL>/en/something/something-else</loc>`

As **en** is default, the URL full path should be: https://<URL>/something/something-else

Then, it's Ok that in Alternate URL i have the: https://<URL>/**es**/something/something-else

Any idea how should I remove the /en/?

**Comment by JarrodMFlesch** [comment]
@gyoon-dev  @toiluj23 

This is how I circumvented this issue, would this work for you too?

```javascript
transform: async (config, path) => {
    const defaultRegion = '/us/';
    let adjustedPath = path;

    if (path.substring(0, defaultRegion.length) === defaultRegion) {
      adjustedPath = path.substring(defaultRegion.length, path.length);
    }

    return {
      loc: adjustedPath, // => this will be exported as http(s)://<config.siteUrl>/<path>
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs: config.alternateRefs ?? [],
    };
  },
```
