### ISSUE TITLE
`next export` error

### ISSUE THREAD

**Issue by zss1004504439** [iamvishnusankar/next-sitemap#148]
**Describe the bug**
`Error: Error for page /news-sitemap.xml: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export`

**To Reproduce**

1. ![image](https://user-images.githubusercontent.com/24915880/117535607-25d81d00-b029-11eb-8803-c1fbe1f87db0.png)
2. `next build && next export`

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/24915880/117535552-df82be00-b028-11eb-8c63-8e9f7180bd28.png)
`Error: Error for page /news-sitemap.xml: pages with `getServerSideProps` can not be exported. See more info here: https://nextjs.org/docs/messages/gssp-export`
![image](https://user-images.githubusercontent.com/24915880/117535673-6fc10300-b029-11eb-8c55-b506edfa71a0.png)

**Additional context**

**Comment by CyberCyclone** [comment]
What was the solution to this? I'm trying to export and I was expecting a scenario like this would either ignore the file or produce a blank page. For some reason it's crashing when it shouldn't be.
