### ISSUE TITLE
Error when open server-sitemap

### ISSUE THREAD

**Issue by xxidbr9** [iamvishnusankar/next-sitemap#149]
**Describe the bug**
i tried the same file from this [example](https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx)

**To Reproduce**

1. I was try to go to this url _localhost:3000/server-sitemap.xml_
2. And it return 500 error
3. See this error
![image](https://user-images.githubusercontent.com/51733515/117757709-c8231b00-b24a-11eb-8267-a648c8e38bf5.png)

**Comment by illiabakunovskyi** [comment]
I have the same issue, will be good if add it to first places in queue of bugs to resolve

**Comment by tehnools** [comment]
Having the same issue.

**Comment by necheporenko** [comment]
@iamvishnusankar, The same issue!

`
"dependencies": {
"next-sitemap": "^1.6.168"
}`

pages/server-sitemap.xml/index.js
```
import nextSitemap from 'next-sitemap';

function SiteMap() {}

export async function getServerSideProps(ctx) {
  console.log('nextSitemap', nextSitemap);
  const { getServerSideSitemap } = nextSitemap;
  console.log('getServerSideSitemap', getServerSideSitemap);
  // Method to source urls from cms
  // const urls = await fetch('https//example.com/api')
  const priority = 0.7;
  const changefreq = 'monthly';

  const fields = [
    {
      loc: 'https://example.com/dynamic-path-1', // Absolute url
      lastmod: new Date().toISOString(),
      changefreq,
      priority,
    },
    {
      loc: 'https://example.com/dynamic-path-2', // Absolute url
      lastmod: new Date().toISOString(),
      changefreq,
      priority,
    },
  ];

  return getServerSideSitemap(ctx, fields);
}

// Default export to prevent next.js errors
export default SiteMap;
```

   
![image](https://user-images.githubusercontent.com/20722449/135277447-dbfaf71c-0822-4fb4-b57b-7d8c742fab79.png)
