### ISSUE TITLE
Sitemap does not contain links to all pages

### ISSUE THREAD

**Issue by karibertils** [iamvishnusankar/next-sitemap#155]
**Describe the bug**
My project has 5 pages. Generated sitemap has only 2.

**To Reproduce**
I am creating new sitemap using `next-sitemap --config next-sitemap.config.js`

**Expected behavior**
I expected sitemap to contain links to all 5 pages.

**Additional context**
next-sitemap.config.js:
```
module.exports = {
	siteUrl: process.env.SITE_URL || 'https://apps.is',
	generateRobotsTxt: true,
}
```

The generated sitemap:
```<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url><loc>https://apps.is</loc><changefreq>daily</changefreq><priority>0.7</priority><lastmod>2021-05-17T15:46:41.100Z</lastmod></url>
<url><loc>https://apps.is/our-way</loc><changefreq>daily</changefreq><priority>0.7</priority><lastmod>2021-05-17T15:46:41.100Z</lastmod></url>
</urlset>```

**Comment by muratkemaldar** [comment]
+1: Having the same issue.
Similar config to yours.

**Comment by klattiation** [comment]
+1

**Comment by abzeede** [comment]
Having the same issue but after I checked in the code, seems like it needs to run `next build` before run the sitemap script.

**Comment by sanderfish** [comment]
Chaining the build script instead of using `postbuild` works for me:

```
{
  "build": "next build && next-sitemap"
}
```

**Comment by LiangYingC** [comment]
Thanks @abzeede and @sanderfish answer to solve this problem.

Let me try to explain more after tracing source code by myself.

If we run next-sitemap of script, it will run [/bin/next-sitemap file](https://github.com/iamvishnusankar/next-sitemap/blob/master/packages/next-sitemap/bin/next-sitemap) and load cli.

So, we can see what happen at [/src/cli.ts](https://github.com/iamvishnusankar/next-sitemap/issues/155) and focus on 

```
// Get runtime paths
const runtimePaths = getRuntimePaths(config)
```

when we read more detail about `getRuntimePaths` at [/src/path/index.ts](https://github.com/iamvishnusankar/next-sitemap/blob/master/packages/next-sitemap/src/path/index.ts), we can realize it return

```
{
    BUILD_MANIFEST: getPath(config.sourceDir!, 'build-manifest.json'),
    PRERENDER_MANIFEST: getPath(config.sourceDir!, 'prerender-manifest.json'),
    EXPORT_MARKER: getPath(config.sourceDir!, 'export-marker.json'),
    ......
  }
```

we can get file paths about `build-manifest.json`, `prerender-manifest.json` and `export-marker.json` that all files will be create after `next build` and will be used to [create url set](https://github.com/iamvishnusankar/next-sitemap/blob/master/packages/next-sitemap/src/cli.ts#L35) at  [/src/cli.ts](https://github.com/iamvishnusankar/next-sitemap/issues/155).

To conclude, **cause next-sitemap need to use files will be create after `next build` to create sitemap**, so we need to run next build before run the next-sitemap script.

Hope to help understanding why need to do

```
{
  "build": "next build && next-sitemap"
}
```

not 

```
{
  "build": "next-sitemap && next build"
}
```

Thanks.
