### ISSUE TITLE
Instructions say to add as dev dependency, should be regular one when generating server-sitemap

### ISSUE THREAD

**Issue by whiterice-bryce** [iamvishnusankar/next-sitemap#156]
When installing as a dev dependancy, my server-sitemap.xml page which is generated from getServerSideProps would return a 500 error on production. This is because the page imports { getServerSideSitemap } from 'next-sitemap'. Because it was installed as dev dependancy, this would return an error because dev dependancies are removed as part of nextjs build process and therefore the import would fail. 

When I installed as regular dependancy, this worked fine.

Maybe the instructions should be updated?

**Comment by Ardhimas** [comment]
Odd. I got a warning from my linter for the exact same reason, but I made a commit without moving it out of devDependencies and it still worked for me.

**Comment by WillSquire** [comment]
Just hit this too. README should warn about dev dependency if using dynamic sitemaps.
