### ISSUE TITLE
Programmatically update sitemap without recompile

### ISSUE THREAD

**Issue by Nases** [iamvishnusankar/next-sitemap#158]
We are storing blog posts in database. `getStaticPaths` & `getStaticProps` updates our website w/o needing to re-compile the whole website as we add more blog posts.

This causes the old sitemap to be obsolete.

I would like to ask for a suggestion if there would be any programmatic way to update our sitemap as we publish blog posts?

**Comment by iamvishnusankar** [comment]
@Nases Please check [Dynamic/Server side sitemaps](https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps)

**Comment by Ardhimas** [comment]
@Nases Were you able to check if @iamvishnusankar 's suggestion works with ISR? I am potentially facing the same issue, though I have not tested whether it updates when the static generation updates.
