### ISSUE TITLE
ReferenceError when trying to load from .env

### ISSUE THREAD

**Issue by amosbastian** [iamvishnusankar/next-sitemap#175]
**Describe the bug**
I receive a `ReferenceError` when trying to load from `.env`.

**To Reproduce**
1. Install `next-sitemap`
2. Add a `next-sitemap.js` referencing e.g. `process.env.SITE_URL`
3. Add `.env` file with `SITE_URL="x"`
4. `npx next-sitemap`
5. Get error

```
Loaded env from /Users/amosbastian/Development/example/.env
(node:27064) UnhandledPromiseRejectionWarning: ReferenceError: SITE_URL is not defined
```

**Expected behavior**

>✅ next-sitemap now loads environment variables from .env files by default.

**Additional context**

I am not sure if I am missing something, since I thought it would load the environment variables automatically.

**Comment by JarrodMFlesch** [comment]
@amosbastian I tried to recreate it the same way you did and it works for me, are you using the newest version?

**Comment by amosbastian** [comment]
I am using `^1.6.116`. I'll try again after work.
