### ISSUE TITLE
Do not add pages marked with `noindex` to sitemap

### ISSUE THREAD

**Issue by fedeci** [iamvishnusankar/next-sitemap#182]
**Is your feature request related to a problem? Please describe.**
Pages with `<meta content="noindex, follow" name="robots" />` should not be added to the sitemap. 
I am not sure about how this library works, but I don't think it actually reads the content of the files so it may be hard to detect  that meta tag.

**Comment by eduncan911** [comment]
With other static site generators (Hugo, Octopress, Gatsby, etc), you typically mark the post as no index in the YAML frontmatter, or some programmable way if pages, etc.  

Some require you to create a sitemap config file to list an explicit exclusion list.

IMO, good sitemap generation tools usually honor all three:

* Frontmatter config
* Programmable API via the SDK (node module)
* Config file exclusion list

From what I see, this package supports the config file exclusions out of the box (see config file options).

As for Frontmatter parsing or some other form of trigging a "skip me!!" option on a per page, you can do that in the Transformations.  Just test for your condition, and `return null` to skip, as the example transformation shows you.

**Comment by fedeci** [comment]
Thanks @eduncan911, I am already doing it in the transformations, however it would be great if it was possible to integrate it directly in the lib. I'll probably fork it and open a PR as soon as possible.

**Comment by gabrielreisn** [comment]
hey, in case someone is still missing this, the solution I'm currently using within my team is a custom transform function. If that's ok I can open a PR with the fix

```
transform: async (config, path) => {
    const noIndexRegex = /<meta.*noindex/gim
    const basePath = '.next/serverless/pages'
    const filePath = `${basePath + path}.html`

    if (fs.existsSync(filePath)) {
      try {
        const data = await fs.promises.readFile(filePath, 'utf8')

        if (data.match(noIndexRegex)) {
          console.log('ignored file:', filePath)

          return null
        }
      } catch (error) {
        console.error('err', error)
      }
    }

    return {
      loc: path,
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs: config.alternateRefs || [],
    }
  },
  ```

**Comment by rserafim** [comment]
I remove like this

module.exports = {
  siteUrl: 'https://www.xxxx,
  exclude: ['/aaa/', '/xxx', '/yyyy'], // <= exclude here

**Comment by zacharias-pavlatos** [comment]
> I remove like this
> 
> module.exports = { siteUrl: 'https://www.xxxx, exclude: ['/aaa/', '/xxx', '/yyyy'], // <= exclude here

Yeap but this is not dynamic... 👎

**Comment by GautheyValentin** [comment]
> hey, in case someone is still missing this, the solution I'm currently using within my team is a custom transform function. If that's ok I can open a PR with the fix
> 
> ```
> transform: async (config, path) => {
>     const noIndexRegex = /<meta.*noindex/gim
>     const basePath = '.next/serverless/pages'
>     const filePath = `${basePath + path}.html`
> 
>     if (fs.existsSync(filePath)) {
>       try {
>         const data = await fs.promises.readFile(filePath, 'utf8')
> 
>         if (data.match(noIndexRegex)) {
>           console.log('ignored file:', filePath)
> 
>           return null
>         }
>       } catch (error) {
>         console.error('err', error)
>       }
>     }
> 
>     return {
>       loc: path,
>       changefreq: config.changefreq,
>       priority: config.priority,
>       lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
>       alternateRefs: config.alternateRefs || [],
>     }
>   },
> ```

It's always working but on version ``"next": "12.2.5"`` path change (Maybe before i don't know exactly)

Before 
```js
 const basePath = '.next/serverless/pages'
```

After 
```js
 const basePath = '.next/server/pages'
```
