### ISSUE TITLE
Question - Is that possible to make it work as static page?

### ISSUE THREAD

**Issue by BrunoQuaresma** [iamvishnusankar/next-sitemap#192]
Right now, I need to fetch a lot of stuff from my CMS and since it is server side, the sitemap will need to fetch all of that on each request. Is that possible to make the `getServerSideSitemap` work for `getStaticProps`?

**Comment by iamvishnusankar** [comment]
@BrunoQuaresma If you build static site by parsing contents from CMS via `getStaticProps` and run `next-stiemap` as `postbuild` script, it will generate sitemap with all sourced slugs.

**Comment by BrunoQuaresma** [comment]
I mean, I'm using ISR(https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration) to generate the site because it has 1K pages... it is static but is generated dynamically.

**Comment by LuizPelegrini** [comment]
@iamvishnusankar I would love to have an update on this. Is it possible to include `getStaticProps` + `revalidate` (e.g ISR) as an enhancement as @BrunoQuaresma mentioned?
