### ISSUE TITLE
ampFirstPages not included as potential paths for generating the manifest

### ISSUE THREAD

**Issue by vonElfvin** [iamvishnusankar/next-sitemap#198]
**Describe the bug**
If you have an `amp: true` page it will not be included in the generated sitemap (unless it has `getStaticProps`).

**To Reproduce**

1. Create a simple page with `export const config { amp: true }`
2. Run `yarn build && yarn next-manifest` and see that the page will not be included in the sitemap

**Expected behavior**
The page should be included in the sitemap unless excluded

**Additional context**
Since currently the check is done in `build-manifest.json['pages']  and `prerender-manifest.json` as a whole and not `build.manifest.json['ampFirstPages]` the paths are clearly not picked up. I have a PR ready with a suggested solution.

Some weird behaviour: Even if it's `amp: true` and if it has `getStaticProps` then it'll be included when generating the manifest since then it'll be included in `prerender-manifest.json` since there it'll specify the props. And similarly if you visit the page locally it'll be included since then it'll be included in `pages` in the `build-manifest` 🤷  Doing it clean slate without `getStaticProps` will result in it being excluded though 😢  

Disclaimer: I am pretty new with `sitemaps` and `amp` in general, maybe there is some magic involved where AMP pages are picked up without a `sitemap`. But I highly doub't that since it'd be a unwanted behaviour.

I have a suggested code fix ready and will try and submit a PR straight away. 

Edit. Seems like I don't have access to push the code to create a PR. With the exception of fixing the tests this is suggested approach:
![image](https://user-images.githubusercontent.com/20777544/127788673-98db5312-3742-4ef7-adac-d7ff6eded388.png)

**Comment by memerapi** [comment]
hi @iamvishnusankar, can you tell us what's the reason behind closing this issue?

**Comment by iamvishnusankar** [comment]
@memerapi This might have closed accidentally. Added support #304
