### ISSUE TITLE
Sitemap ~6m pages

### ISSUE THREAD

**Issue by rserafim** [iamvishnusankar/next-sitemap#199]
Hello people. Can you help me with this question?

My project has over 6 million pages.

I can only generate 3k static pages. The others will be generated by ISR.

Can I generate a complete sitemap with my 6 million pages?

As this is an ad portal. If a new advertiser joins, I need to add it to the sitemap. Likewise if a customer asks to be deleted.

**Comment by iamvishnusankar** [comment]
Hey @rserafim , you can make use of [additionalPaths](https://github.com/iamvishnusankar/next-sitemap#additional-paths-function) (Thanks to @KonstantinBozhkov ) method and inject additional page info during static site generation or make use of [dynamic sitemap](https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps).

**Comment by iamvishnusankar** [comment]
> Hey @rserafim , you can use [additionalPaths](https://github.com/iamvishnusankar/next-sitemap#additional-paths-function) (Thanks to @KonstantinBozhkov ) method and inject additional page info during static site generation or use [dynamic sitemap](https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps).

**Comment by pixelmultiplo** [comment]
How would you do a dynamic sitemap with 6M pages if the URLs come from an API?

**Comment by rserafim** [comment]
> How would you do a dynamic sitemap with 6M pages if the URLs come from an API?

with pagination
