### ISSUE TITLE
Escape required html entities in paths

### ISSUE THREAD

**Issue by csandman** [iamvishnusankar/next-sitemap#207]
**Is your feature request related to a problem? Please describe.**
In order to have valid XML, certain characters need to be escaped.  according to Google's sitemap guidelines, certain characters need to be escaped to their html entities.

> **Non-alphanumeric and non-latin characters**. We require your sitemap file to be UTF-8 encoded (you can generally do this when you save the file). As with all XML files, any data values (including URLs) must use entity escape codes for the characters listed in the table below. A sitemap can contain only ASCII characters; it can't contain upper ASCII characters or certain control codes or special characters such as `*` and `{}`. If your sitemap URL contains these characters, you'll receive an error when you try to add it.
> 
> | Character    | Symbol | Escape Code |
> |--------------|--------|-------------|
> | Ampersand    | `&`      |`&amp;`       |
> | Single Quote | `'`      | `&apos;`      |
> | Double Quote | `"`      | `&quot;`      |
> | Greater Than | `>`      | `&gt;`        |
> | Less Than    | `<`      | `&lt;`        |
>
> —https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#general-guidelines

**Describe the solution you'd like**
Ideally this would be done automatically by this plugin, I can't think of a good reason why it doesn't.  If there is a good reason, I'd be glad to hear it!

**Describe alternatives you've considered**
My solution was to add this replacement to the path in the `transform` function, but it just seems like something that should be built in:

```js
module.exports = {
  transform: async (config, path) => ({
    loc: path
      .replace(/&/g, "&amp;")
      .replace(/'/g, "&apos;")
      .replace(/"/g, "&quot;")
      .replace(/>/g, "&gt;")
      .replace(/</g, "&lt;"),
    changefreq: config.changefreq,
    priority: config.priority,
    lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
    alternateRefs: config.alternateRefs ?? [],
  }),
};
```

**Additional context**
![image](https://user-images.githubusercontent.com/9214195/130531670-5dff1483-49b7-4443-8a70-2c0753211f9a.png)

**Comment by machineghost** [comment]
This is a significant issue, and the OP has all but submitted a PR (although personally I'd use `encodeURI` instead of a replace).

Could we please get some maintainer response?

**Comment by iamvishnusankar** [comment]
@csandman @machineghost Added support for entity escaped safe urls #252
