### ISSUE TITLE
Wrong URLs for locale sub-path routing 

### ISSUE THREAD

**Issue by CruelMoney** [iamvishnusankar/next-sitemap#212]
**Describe the bug**
When using sub-path routing for multiple languages and the alternateRefs - the script produces wrong alternate URLs.

**To Reproduce**

1. Have a next-sitemap.js config with sub-path alternateRefs: 

```javascript
const siteUrl = 'http://localhost:8500'

module.exports = {

  ...

  alternateRefs: [
    {
      href: siteUrl + '/da', // sub-route
      hreflang: 'da',
    },
    {
      href: siteUrl, // base path for default locale
      hreflang: 'en',
    },
  ]
};
```

2. Run `yarn next-sitemap`
3. sitemap.xml now contains entries with alternate URLs ending with for example `/da/da/about`

```xml
...
<url>
  <loc>http://localhost:8500/about</loc>
  <xhtml:link rel="alternate" hreflang="da" href="http://localhost:8500/da/about"/>
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:8500/about"/>
</url>
<url>
  <loc>http://localhost:8500/da/about</loc>

    <!- Wrong hrefs below -->
  <xhtml:link rel="alternate" hreflang="da" href="http://localhost:8500/da/da/about"/> 
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:8500/da/about"/> 

</url>
...
```

**Expected behavior**
Ideally, the XML should be stripped of the sub-route before appending the alternate hrefs: 

```xml
...
<url>
  <loc>http://localhost:8500/about</loc>
  <xhtml:link rel="alternate" hreflang="da" href="http://localhost:8500/da/about"/>
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:8500/about"/>
</url>
<url>
  <loc>http://localhost:8500/da/about</loc>

  <!- Corrected by stripping the initial locale -->
  <xhtml:link rel="alternate" hreflang="da" href="http://localhost:8500/da/about"/>
  <xhtml:link rel="alternate" hreflang="en" href="http://localhost:8500/about"/>

</url>
...
```

**Comment by vfilter** [comment]
Facing the same issue. Is there a workaround maybe using a custom transformation? Otherwise it'll have to be manual edits for now. :(

**Comment by knightspore** [comment]
Facing the same issue here - I've tried a few custom transforms, none of which solve the problem (which is especially hard to verify on a large site with supporting many locales).

**Comment by tkhquang** [comment]
I'm running to the same problem here, any workaround for this yet?

**Comment by knightspore** [comment]
There's an ongoing fix here https://github.com/iamvishnusankar/next-sitemap/pull/234
