### ISSUE TITLE
Question: When should `additionalPaths` or `dynamic/server-side sitemaps` be used?

### ISSUE THREAD

**Issue by marnixhoh** [iamvishnusankar/next-sitemap#216]
First of all, thank you for creating and maintaining this awesome project!

I am currently working on integrating it into our application. I do have one question. It is not completely clear to me as to when `additionalPath` should be used and when `dynamic/server-side sitemaps` should be used instead to add dynamic pages to the sitemap?

- Are there any advantages / drawbacks of using one of the two?
- Is sitemap splitting using `sitemapSize` supported by both?

Thank you so much in advance for taking the time to answer my question(s).

**Comment by rserafim** [comment]
same doubts

**Comment by marnixhoh** [comment]
@rserafim Yeah I think you're right. I just checked the project's source code and the splitting functionality only runs for additional paths.

@iamvishnusankar I have taken the liberty to tag you here. I think splitting functionality for dynamic sitemaps could be a great enhancement. :)
