### ISSUE TITLE
Allow es modules to be imported in `next-sitemap.js`.

### ISSUE THREAD

**Issue by marnixhoh** [iamvishnusankar/next-sitemap#217]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to import es modules in `next-sitemap.js`.

For example:
**paths.js**
```
export const somePath = 'some/path'
```

**next-sitemap.js**
```
import { somePath } from './paths'
```
or
```
const { somePath } = require('./paths')
```

Both of these won't work. In other words, it is in no way possible to import an es module into `next-sitemap.js`.

I could imagine that many next.js users have a paths.js file containing all of their app's paths. E.g. one would import these into `next-sitemap.js` to exclude a path.

**Describe the solution you'd like**
There are multiple solutions:

1. import `next-sitemap.js` (inside next-sitemap src code) using the `import` statement as opposed to using the require statement. This would effectively make `next-sitemap.js` an es module being able to import other es modules. Without using Babel it is necessary though to rename `next-sitemap.js` to `next-sitemap.mjs` to use the `import` syntax. Or adding `{ type: 'module' }` to `package.json`.
2. let Babel process `next-sitemap.js` before executing it using the `@babel-node` package for example.

**Describe alternatives you've considered**
The only alternative I see right now is to hardcode any values you'd like to import and thereby duplicating them. But if the values change and one forgets to update the hardcoded values in `next-sitemap.js`, things will obviously break...

**Comment by benjaminhoffman** [comment]
Huge upvote for this one! ⬆

My use case(s):
- I don't use `.env` file to store my `siteUrl`. Instead, I use a `src/data/company` file that holds all my project info (company name, domain name, social profiles, etc). Thus, in my `next-sitemap.js` file, I'd like to `import company from ...` then do `siteUrl: company.domain`

- for my `exclude` array, I'd like to iterate over all my URLs and exclude the ones with the `noindex` tag. I'm not sure how I plan to do this yet but as we scale, we'll definitely need this feature (@marnixhoh you mention a `paths.js` file, is this dynamically generated for you -- can you share more how you accomplished this?)

Thanks @iamvishnusankar for this package -- I've used it on three client projects so far and appreciate the maintenance!

**Comment by NoobTW** [comment]
This is what I've been doing:

1. install `esm` package:

```shell
npm i -D esm
```

2. run `next-sitemap` with `esm` on postbuild stage:
``` json
{
    "build": "next build",
    "postbuild": "node -r esm node_modules/next-sitemap/bin/next-sitemap"
}
```

Now I can include es modules like:

```javascript
// next-sitemap.js
import axios from './utils/axios';

module.exports = {
    additionalPaths: async () => {
        const data = await axios.get('/api/v1/data');
        return data.map((d) => ({
            loc: `https://example.com/${d}`,
        });
    },
};
```

**Comment by benjaminhoffman** [comment]
i may just do this solution instead since i dont have a lot of URLs. https://nextjs.org/learn/seo/crawling-and-indexing/xml-sitemaps

**Comment by benjaminhoffman** [comment]
@iamvishnusankar i cant if this is closed bc it's solved or closed bc it's not being fixed?  if the former, what's the solution?

**Comment by eakl** [comment]
any update? I have the same problem. Trying to import an util function in next-sitemap.js

**Comment by mediabeastnz** [comment]
👀

**Comment by JarFrank** [comment]
As a workaround, I am using this code:
```
module.exports = {
  siteUrl: "http://localhost:3000",
  generateRobotsTxt: true,
  outDir: "./out",
};
```

**Comment by KishokanthJeganathan** [comment]
yep this is how I solved this too ^. More info - https://www.kishokanth.com/blog/how-to-fix-postbuild-error-when-using-next-sitemap

**Comment by MatthiPR** [comment]
@iamvishnusankar why was this closed this does not work at all?

**Comment by bhavesh-chaudhari** [comment]
Any solution?

**Comment by robinsadeghpour** [comment]
Just rename the file to "next-sitemap.config.cjs", declaring that it is a common js file  and change the postbuild command to   "postbuild": "next-sitemap --config next-sitemap.config.cjs",
