### ISSUE TITLE
not showing multiple files when sitemap size increases 

### ISSUE THREAD

**Issue by Hassaan0316** [iamvishnusankar/next-sitemap#228]
I have a list of 18000 URLs. i have created a folder  **"server-sitemap.xml"** that contains index.js which takes all the URLs. In your documentation its written that if size increases the limit defined, it will create multiple file, but after creating the dynamic sitemaps there is only 1 file showing of dynamic sitemaps.

this is the code i am receiving in my robots.txt

```
# *
User-agent: *
Allow: /

# Host
Host: https://www.*******.io

# Sitemaps
Sitemap: https://www.*******.io/sitemap.xml
Sitemap: https://www.*******.io/server-sitemap.xml
```

Note: used Asterik to keep the real site hidden.

**Comment by rserafim** [comment]
> I have a list of 18000 URLs. i have created a folder **"server-sitemap.xml"** that contains index.js which takes all the URLs. In your documentation its written that if size increases the limit defined, it will create multiple file, but after creating the dynamic sitemaps there is only 1 file showing of dynamic sitemaps.
> 
> this is the code i am receiving in my robots.txt
> 
> ```
> # *
> User-agent: *
> Allow: /
> 
> # Host
> Host: https://www.*******.io
> 
> # Sitemaps
> Sitemap: https://www.*******.io/sitemap.xml
> Sitemap: https://www.*******.io/server-sitemap.xml
> ```
> 
> Note: used Asterik to keep the real site hidden.
This is only in the static part, as it will already know how many urls were generated. For Generating dynamic/server-side sitemaps you must control this as there is no way to know how many urls your CMS has.

**Comment by VinceCTL** [comment]
Some news about it ? I have the same issue !

**Comment by iamvishnusankar** [comment]
`next-sitemap` can only split static sitemaps into multiple files. In case of dynamic/server-side sitemaps, `next-sitemap` doesn't have info regarding the data, hence you are supposed to paginate the sitemap using url params

```
/server-sitemap.xml/[id].tsx
```

**Comment by 28development** [comment]
@iamvishnusankar this component
`/server-sitemap-[id].xml.tsx` is just inside the pages directory and has no upper directory like `server-sidemap-index.xml` right?
