### ISSUE TITLE
An unexpected error occurred: "Potentially dangerous call to \"next-sitemap\"

### ISSUE THREAD

**Issue by winstonsec** [iamvishnusankar/next-sitemap#243]
**Describe the bug**
When i run:  yarn build, the comand throws an error:

```
yarn run v1.22.17
$ next-sitemap
error An unexpected error occurred: "Potentially dangerous call to \"next-sitemap\" in C:\\Users\\jonat\\Downloads\\app-modern-next\\004-app-modern-next
```

**Comment by qasimali0001** [comment]
This error comes on Windows environment. Running on Macbook works fine.

**Comment by RicardoRB** [comment]
Same problem here

**Comment by ProgrammingInBlood** [comment]
dont use yarn .... use NPM its just works fine

**Comment by Suubash** [comment]
This error only occurs in windows machine. If you want to remove this error, just use cross-env plugin.
`yarn add cross-en`

Update scripts inside package.json file and add the following command:
` "postbuild": "cross-env next-sitemap --config next-sitemap.js"`

It should look like this:
`"scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "postbuild": "cross-env next-sitemap --config next-sitemap.js"
  }`

**Comment by RicardoRB** [comment]
> This error only occurs in windows machine. If you want to remove this error, just use **cross-env** plugin.
> 
> `yarn add cross-env` OR `npm install cross-env`
> 
> Update scripts inside package.json file and add the following command: ` "postbuild": "cross-env next-sitemap --config next-sitemap.js"`
> 
> It should look like this:
> 
> ```
> "scripts": {
>     "dev": "next dev",
>     "build": "next build",
>     "start": "next start",
>     "postbuild": "cross-env next-sitemap --config next-sitemap.js"
>   }
> ```

Thank you for your response. Already fixed ;)

**Comment by iamvishnusankar** [comment]
This is regarding windows file system. It's already addressed at: https://github.com/iamvishnusankar/next-sitemap#building-sitemaps

Closing this for now!
