### ISSUE TITLE
url Tag per Locale

### ISSUE THREAD

**Issue by raphaelniederer** [iamvishnusankar/next-sitemap#244]
Hello

I have a question. How can I generate a url Tag per locale? I defined the `alternateRefs` but this don't generate an url tag per locale.

Thank you for your support.

https://www.wishlistboard.com/sitemap.xml

**Comment by ekfn** [comment]
Same question, shouldn't it create a separate sitemap entry for each locale? https://developers.google.com/search/docs/advanced/crawling/localized-versions?visit_id=637877918639597405-1110157180&rd=1#example_2
