### ISSUE TITLE
`next-sitemap` does not exit with a non-zero exit code when an error occur

### ISSUE THREAD

**Issue by nddery** [iamvishnusankar/next-sitemap#245]
**Describe the bug**
`next-sitemap` does not exit with a non-zero exit code when an error is encountered.

**To Reproduce**
With the following configuration file:

```js
throw new Error("error")
```

Running `npx next-sitemap --config ./path/to/config.js` yields the following error:

```bash
❯ npx next-sitemap --config ./next-sitemap.js
Loaded env from /.env.local
(node:14742) UnhandledPromiseRejectionWarning: Error: error
    at Object.<anonymous> (/next-sitemap.js:5:7)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.exports.loadFile (/node_modules/next-sitemap/dist/cjs/file/index.js:12:16)
    at Object.exports.loadConfig (/node_modules/next-sitemap/dist/cjs/config/index.js:16:31)
    at /node_modules/next-sitemap/dist/cjs/cli.js:24:27
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

However, `next-sitemap` exited with a code of 0:

```bash
❯ echo $?
0
```

**Expected behavior**
I'd expect `next-sitemap` to exit with a non-zero status code, so to fail my build.

**Additional information**
We're using `next-sitemap@1.6.203`.

**Comment by teinett** [comment]
I use next-sitemap v.2.0.7 and have the same problem.

**Comment by iamvishnusankar** [comment]
@teinett Have you tried it after building the project?

**Comment by teinett** [comment]
@iamvishnusankar thanks for the quick response!

I installed the last version of your package: "next-sitemap": "^2.1.5".

I tried to do `npm run build` and `npm run postbuild` together and only `npm run postbuild`.

The bug is still present, build is not completed.

```
➜  frontend git:(main) ✗ npm run postbuild  

> media-frontend@0.1.0 postbuild /Users/teine/Development/frontend
> next-sitemap

Loaded env from /Users/teine/Development/frontend/.env.local
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'node:fs/promises'
Require stack:
- /Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/file/index.js
- /Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/config/index.js
- /Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/cli.js
- /Users/teine/Development/frontend/node_modules/next-sitemap/bin/next-sitemap
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/file/index.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/file/index.js',
    '/Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/config/index.js',
    '/Users/teine/Development/frontend/node_modules/next-sitemap/dist/cjs/cli.js',
    '/Users/teine/Development/frontend/node_modules/next-sitemap/bin/next-sitemap'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! media-frontend@0.1.0 postbuild: `next-sitemap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the media-frontend@0.1.0 postbuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/teine/.npm/_logs/2022-01-30T21_01_37_676Z-debug.log
```

**Comment by iamvishnusankar** [comment]
@teinett Looks like this is an issue with your Node installation. May I know your current node version? This package only supports node >= 14

**Comment by teinett** [comment]
NPM: 6.14.14
NodeJS: 14.17.5
NextJS: 12.0.9
next-sitemap: 2.1.5
MacOS Catalina - 10.15.7

**Comment by teinett** [comment]
> @teinett Looks like this is an issue with your Node installation. May I know your current node version? This package only supports node >= 14

I will update to Node 14.18.3 (the last available stable version) and try again.

**Comment by iamvishnusankar** [comment]
@teinett Looks like all the 14.x integration tests are run against node [14.18.3](https://github.com/iamvishnusankar/next-sitemap/runs/4998516626?check_suite_focus=true#step:3:7)

More about this: https://nodejs.org/api/modules.html#requirecache

**Comment by teinett** [comment]
@iamvishnusankar I updated my node.

Npm: 6.14.15
Node: 14.18.3
NextJS: 12.0.9
next-sitemap: 2.1.5
MacOS Catalina - 10.15.7

Now it's another error:

```
> next-sitemap

Loaded env from /Users/teine/Development/traffic-exchange-media/frontend/.env.local
 ❌ [next-sitemap] Unable to find export-maker.
Make sure to build the project using `next build` command

(node:80615) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/Users/teine/Development/traffic-exchange-media/frontend/.next/export-marker.json'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:80615) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:80615) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by iamvishnusankar** [comment]
@teinett You need to build your next.is project first before running next-sitemap.

> Make sure to build the project using `next build` command

**Comment by teinett** [comment]
@iamvishnusankar 
OK, I found the problem.

NextJS has an option the change the output folder from the build. 
The developer can do it in the file next.config.js: [`distDir: 'build',`.](https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory).

If I have default build directory, you package works fine.
If I have custom build directory, you package has error and crashes the build.

So I won't use custom build folder settings for now, and will do the sitemap. 

But I should work with this option.

**Comment by iamvishnusankar** [comment]
@teinett This package do support custom build folder. Just set the "sourceDir" in your next-sitemap.js

Check the configuration options in ReadMe to know more about this.

**Comment by teinett** [comment]
@iamvishnusankar Ok, I found this option. I will try it in my code.

Thanks a lot for your package and fast replies here!

**Comment by victorcarvalhosp** [comment]
I changed the sourceDir on my next-sitemap.js and it works locally - but when I try to run it on Vercel I get the error below:

<html>
<body>


✨ [next-sitemap] Loading next-sitemap config: file:///vercel/path0/next-sitemap.config.js
--
16:43:59.995 | ❌ [next-sitemap] Unable to find export-maker.
16:43:59.995 | Make sure to build the project using `next build` command
16:43:59.995 |  
16:43:59.998 | node:internal/process/promises:279
16:43:59.998 | triggerUncaughtException(err, true /* fromPromise */);
16:43:59.998 | ^
16:43:59.999 |  
16:43:59.999 | [Error: ENOENT: no such file or directory, stat '/vercel/path0/.next/export-marker.json'] {
16:43:59.999 | errno: -2,
16:43:59.999 | code: 'ENOENT',
16:43:59.999 | syscall: 'stat',
16:43:59.999 | path: '/vercel/path0/.next/export-marker.json'
16:43:59.999 | }
16:44:00.012 | Error: Command "npm run build" exited with 1


</body>
</html>

Do I need to change some other configuration to make this work on Vercel?
