### ISSUE TITLE
Not compitable with latest next 12 build

### ISSUE THREAD

**Issue by RobinGiel** [iamvishnusankar/next-sitemap#266]
**Describe the bug**

error next-sitemap@1.9.12: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.7"
--
14:14:24.255 | error Found incompatible module.
14:14:24.255 | info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
14:14:24.299 | Error: Command "yarn install" exited with 1

**To Reproduce**
1.Run the build with latest NextJs version

**Comment by ShreyaThapa** [comment]
Were you able to find a solution for this @RobinGiel? I'm still getting the error when on Next 9.3.2.

**Comment by iamvishnusankar** [comment]
@ShreyaThapa next-sitemap requires node version >=14

**Comment by ShreyaThapa** [comment]
D'oh! Thanks @iamvishnusankar!
