### ISSUE TITLE
Excluding a page does not exclude it's translations

### ISSUE THREAD

**Issue by angelovdev** [iamvishnusankar/next-sitemap#267]
**Describe the bug**
Excluding a page in the `exclude` array does not automatically exclude translated pages.

**To Reproduce**

1. Create a next project
2. Add languages
```js
// next.config.js
module.exports = {
  i18n: {
    locales: ['en-US', 'fr', 'nl-NL'],
    defaultLocale: 'en-US',
  },
}
```
3. Add a page
4. Exclude page from sitemap
```js
module.exports = {
  siteUrl: 'https://example.org',
  generateRobotsTxt: true,
  exclude: ['/page'],
};
```
5. Generate sitemap
6. `/page` is not in the sitemap.xml file but `/fr/page` and `/nl-NL/page` are there.

**Expected behavior**
Internationalization should be accounted for.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by kirkegaard** [comment]
Why was this closed? Is this the expected behaviour?
