### ISSUE TITLE
Dynamic/server-side sitemaps are not included in the index sitemap file

### ISSUE THREAD

**Issue by rychnovsky** [iamvishnusankar/next-sitemap#271]
**Describe the bug**
From `next-sitemap` v2.x onwards, sitemap index file is generated, but sitemaps generated dynamically on server-side are not included in this index file. 

**To Reproduce**

1. Create a dynamic/server-side sitemap as described in the docs
```
// next-sitemap.js
module.exports = {
  siteUrl: 'https://example.com',
  generateRobotsTxt: true,
  exclude: ['/server-sitemap.xml'],
  robotsTxtOptions: {
    additionalSitemaps: [
      'https://example.com/server-sitemap.xml',
    ],
  },
}
```
2. Build the app and generate sitemaps

**Expected behavior**
Dynamic sitemaps should be included in the sitemap index file. They could be described in current `robotsTxtOptions.additionalSitemaps` option, or alternatively, there could be another option to provide urls of these dynamic sitemaps.

**Additional context**
I'm using `next-sitemap@2.0.5`

**Comment by iamvishnusankar** [comment]
@rychnovsky Thanks for reporting! Fixed!

**Comment by rychnovsky** [comment]
@iamvishnusankar Wow, what a quick fix! Thanks a lot, it works as expected.
