### ISSUE TITLE
Build url with different locales and different slug

### ISSUE THREAD

**Issue by julianblanco00** [iamvishnusankar/next-sitemap#273]
Hi! You have build an amazing library. I'm struggling with something.
The package builds perfectly the url with its locales, but my urls look like this: 'www.url.com/hi' && 'www.url.com/fr/bonjour', this two urls are the same page, but only with different locale. Is it posible to change  'www.url.com/hi' &&  'www.url.com/fr/hi' as this  package builds to the url format that I wrote before? Thank you!

**Comment by safirelauene** [comment]
The same thing happened to me. I have generated pages with localised slugs, but when generating the alternative links in the sitemap, the same problem happens as @julianblanco00 reported: `www.url.com/fr/hi` instead of `www.url.com/fr/bonjour`
