### ISSUE TITLE
How to fix duplicate entries between /sitemap.xml and /server-sitemap.xml?

### ISSUE THREAD

**Issue by bramvdpluijm** [iamvishnusankar/next-sitemap#274]
First of all, great work on this library! I came across an issue which is not described in the readme, but I also don't think it's a bug. Therefore I'm just creating an open issue / question. Maybe someone can help me out.

**Case**:
The website I'm working on has a mix of static urls and dynamic urls. Therefore it uses getStaticProps for the static url pages and getStaticProps with getStaticPaths for the dynamic url pages. On build time (whenever I commit my code), all static pages will be generated. Next.js will also generate static html pages of the dynamic url pages and get data from a CMS. I'm left with a complete build of all pages. All good here.

This is the part where it gets interesting. Because whenever a user creates a new page in the CMS I don't want to trigger an entire new build of the entire website. Doing that would counteract the purpose of [Incremental Static Optimization](https://nextjs.org/docs/basic-features/data-fetching/incremental-static-regeneration).

The solution to the above "problem" would be to use server-sitemap.xml, as far as I understood correctly. That way, whenever google crawls `{site-url}/server-sitemap.xml` (which is part of /sitemap.xml) it will always be presented with an up-to-date version of all urls that exist from data in the CMS.

I have a server-sitemap.xml in place which works well, but it includes the same pages as sitemap.xml minus the static url pages. It's all logical, because in the build step all pages will be generated and next-sitemap will create sitemap entries for all of them. But I'm left with 2 sitemaps with 90% of the same pages.

My question: Is there a solution to delete duplicate pages that also exist in sitemap.xml from server-sitemap.xml?

**Comment by iamvishnusankar** [comment]
@bramvdpluijm This is an interesting logical problem. I think you need some sort of flag to determine last build time. Here's my take on this.

Set a build time `.env` via CI/CD and only fetch links generated after that timestamp via `sever-sitemap.xml`. Following will be the pseudo logic.

During build time (CI/CD)
```
Set env process.env.LAST_BUILD_TIMESTAMP
```

During server-sitemap query
```
Fetch all links: post.createdAt > process.env.LAST_BUILD_TIMESTAMP
```

**Comment by bramvdpluijm** [comment]
I'll give that a go! Thanks 👍
