### ISSUE TITLE
Configurable priority and changefreq per URL

### ISSUE THREAD

**Issue by alexandersch** [iamvishnusankar/next-sitemap#28]
Is it possible to configure priority and changefreq per URL instead of one default setting for all entries?

**Comment by iamvishnusankar** [comment]
@alexandersch Thanks for coming up with this suggestion. This opens window for customising individual field set as well as excluding wildcard url patterns.  

Added support in #29

**Comment by alexandersch** [comment]
Hi, 
Thanks for responding so quickly! I will try this out!
