### ISSUE TITLE
Error: Cannot find module 'node:fs/promises'

### ISSUE THREAD

**Issue by JonQuayle** [iamvishnusankar/next-sitemap#281]
Hi, I'm getting the error:

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:fs/promises'
Require stack:
- /Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/file/index.js
- /Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/config/index.js
- /Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/cli.js
- /Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/bin/next-sitemap
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/file/index.js:17:36)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/file/index.js',
    '/Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/config/index.js',
    '/Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/dist/cjs/cli.js',
    '/Users/jonquayle/Sites/next-js-starter/node_modules/next-sitemap/bin/next-sitemap'
  ]
}
```
 when running the post build script. As far as I know 'node:fs/promises' is built into node? Having followed the Read me and various tutorials using next-sitemap, I'm at a loss to know what isn't quite working. Can anyone shed some light for me please?

**Comment by iamvishnusankar** [comment]
@JonQuayle Fixed #282

**Comment by sandrooco** [comment]
@iamvishnusankar This still happens on 2.1.8 - any ideas? I have a standard vercel setup.

**Comment by iamvishnusankar** [comment]
@sandrooco Make sure your node version is >=14.18.3

**Comment by sandrooco** [comment]
Sorry, I didn't know that I can choose the node version on vercel until just now. It works!
Thanks for the quick help, I really appreciate it.

**Comment by JonQuayle** [comment]
It works brilliantly! Thanks for fixing this so fast! 👍

**Comment by ezekiel747** [comment]
> @sandrooco Make sure your node version is >=14.18.3

thanks. Could you or someone please add this version requirement to the Readme doc?
I just encountered this today and arrived here looking for answers, after scanning the readme for hints.

**Comment by remarcable** [comment]
On Netlify, you can set the `NODE_VERSION` environment variable to `14` or add the `.nvmrc` config file to fix this: https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript

**Comment by ferremek** [comment]
Hey guys,

I still seem to have this issue. I even downloaded the [/examples/basic](https://github.com/iamvishnusankar/next-sitemap/tree/master/examples/basic) folder and run into the same issue. I have npm version `v15.3.0` and node version `7.0.14`.

I followed the docs instructions and created a `./next-sitemap.js` in the root folder with the following:
```
module.exports = {
  siteUrl: process.env.SITE_URL,
  generateRobotsTxt: true,
};
```

My package.json looks like this:
```
{
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "postbuild": "next-sitemap",
    "start": "next start"
  },
  "dependencies": {
    "@fancyapps/ui": "^4.0.26",
    "he": "^1.2.0",
    "i18n-iso-countries": "^7.3.0",
    "isomorphic-unfetch": "^3.1.0",
    "next": "^12.1.0",
    "next-sitemap": "^2.5.20",
    "nprogress": "^0.2.0",
    "query-string": "^7.1.1",
    "react": "17.0.2",
    "react-datepicker": "^4.7.0",
    "react-dom": "17.0.2",
    "react-dropzone": "^12.0.4",
    "react-input-mask": "^2.0.4",
    "react-select": "^5.2.2",
    "sass": "^1.49.9",
    "swiper": "^7.4.1",
    "swr": "^1.2.2"
  },
  "devDependencies": {
    "prettier": "2.5.1"
  }
}
```

Any ideas on how I can fix this?

Thanks!

<img width="840" alt="Schermafbeelding 2022-05-16 om 14 02 16" src="https://user-images.githubusercontent.com/15103617/168588344-49376dd5-cdf3-463d-bca9-f82cda7d2b48.png">

**Comment by BrunoElo** [comment]
> > @sandrooco Make sure your node version is >=14.18.3
> 
> thanks. Could you or someone please add this version requirement to the Readme doc? I just encountered this today and arrived here looking for answers, after scanning the readme for hints.

This still hasn't been done. Struggled a lot!
