### ISSUE TITLE
Double locale in alternateRefs using i18n

### ISSUE THREAD

**Issue by viktor-edgardcooper** [iamvishnusankar/next-sitemap#284]
**Describe the bug**

The locale from the path is added to the alternateRefs, which results in multiple locales in the alternateRefs.

```
i18n: {
  defaultLocale: 'default',
  locales: ['default', 'en', 'nl', 'fr', 'de', 'it', 'es'],
},

```
```
let alternateRefs = filteredLocales.map((locale) => ({
  href: `${siteUrl}/${locale}`,
  hreflang: locale,
}));
alternateRefs.push({
  href: `${siteUrl}/en`,
  hreflang: 'x-default'
});
```

**Expected behavior**
The alternateRefs should not keep their original locale.

**Screenshots**

![image](https://user-images.githubusercontent.com/92312223/152201518-b5234294-f0c0-45c5-b530-9d5899f68212.png)

**Additional context**
I've seen this issue being mentioned before, but haven't seen this being resolved.
I'm using the current latest version of this package: version `"2.1.8"`

**Comment by viktor-edgardcooper** [comment]
I just wanted to give an update on this issue for people who are experiencing the same problem. We decided to remove this package and implemented a custom sitemap. This guide helped us to get things started: [https://leerob.io/blog/nextjs-sitemap-robots](https://leerob.io/blog/nextjs-sitemap-robots)

**Comment by RemyMachado** [comment]
You shouldn't have closed this issue, as it still is a problem, but I must agree with implementing a custom sitemap. This library seems to have too many bugs wandering for a long time. Basic subpath localization isn't even working...
This library had great potential, but didn't reach it.

**Comment by gybber-dev** [comment]
I have the same error in v.4.1.3

**Comment by thatgriffith** [comment]
I found this awesome solution: https://dev.to/valse/create-sitemaps-for-a-multi-language-multi-domain-url-translated-static-nextjs-site-41ap. Hope it helps anyone else that is stuck with this.

**Comment by luluhoc** [comment]
Here is my solution

```
transform: async (config, path) => {
    // Remove the locale part of the path (e.g. /es/about -> /about)
    const extractLocaleIndependentPath = (path) => {
      const matches = config.alternateRefs.map((alt) =>
        `${config.siteUrl}${path}/`
          .replace(`${alt.href}/`, "/")
          .replace(/\/+$/, "")
      )
      return matches.sort((a, b) => a.length - b.length)[0]
    }

    const localeIndependentPath = extractLocaleIndependentPath(path)
    const extractLocale = (p) => {
      const locale = p.split("/")[1]

      return locale
    }

    const locale = extractLocale(path)
    if (!locale || locale !== "en") {
      return null
    }

    // Map the locale independent path onto the locale paths
    const alternateRefs = config.alternateRefs.map((alt) => {
      return {
        ...alt,
        href: `${alt.href}${localeIndependentPath}`,
        hrefIsAbsolute: true,
      }
    })

    return {
      loc: path.replace("/en", ""),
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
      alternateRefs,
    }
  }
```
