### ISSUE TITLE
Add @type JSDoc in sample next-sitemap.js config files

### ISSUE THREAD

**Issue by raphaelsaunier** [iamvishnusankar/next-sitemap#291]
**Is your feature request related to a problem? Please describe.**

This library has nice TypeScript interfaces; I reckon it would be very useful for newcomers to have validation and autocompletion to discover the valid configuration values. 

**Describe the solution you'd like**

This can be done simply by adding the following line at the top of `next-sitemap.js`:

`/** @type {import('next-sitemap').IConfig} */`

I'd suggest updating the samples in README.md as well as those in the `examples/` folder.

**Describe alternatives you've considered**
n/a

**Additional context**

Look at this lovely autocompletion! 😍

<img width="684" alt="image" src="https://user-images.githubusercontent.com/170256/152859732-137a9fc3-c5cd-4306-abc0-046c9e5ee083.png">
<img width="564" alt="image" src="https://user-images.githubusercontent.com/170256/152861134-b183c875-5438-414a-b064-c2ac3dc4a938.png">

**Comment by iamvishnusankar** [comment]
@raphaelsaunier Thanks for this wonderful suggestion. Added JSDoc details in README via #292 :)
