### ISSUE TITLE
[help wanted] Windows 10 error - "postbuild": "next-sitemap --config next-sitemap.js"

### ISSUE THREAD

**Issue by bubuq3** [iamvishnusankar/next-sitemap#295]
**Describe the bug**
git bash: `npm run postbuild` shows an windows 10 error
![image](https://user-images.githubusercontent.com/62507500/153721067-a9c8e0ec-5887-40dc-9b50-c3eec4edd7eb.png)

**To Reproduce**

1. add build script: `"postbuild": "next-sitemap --config next-sitemap.js"` in package.json
2. create next-sitemap.js in root folder and enter:
```js module.exports = {
  siteUrl: "https://example.vercel.app/",
  changefreq: "daily",
  priority: 0.7,
  //   sitemapSize: 5000,
  generateRobotsTxt: true,
  exclude: ["/server-sitemap.xml"],

  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
      },
    ],
    additionalSitemaps: [
      "https://example.vercel.app/server-sitemap.xml",
    ],
  },
};
```
3. Create a server-sitemap.xml folder in pages folder and inside this folder index.js enter this code:
```js import { getServerSideSitemap } from "next-sitemap";
import { getPortfolioSlugs } from "../../lib/data";

export const getServerSideProps = async (ctx) => {
  // Method to source urls from cms
  const slugs = await getPortfolioSlugs();

  const fields = slugs.map((slug) => ({
    loc: `https://example.vercel.app/portfolio/${slug.slug}`,
    lastmod: new Date().toISOString(),
  }));

  return getServerSideSitemap(ctx, fields);
};

// Default export to prevent next.js errors
export default Sitemap = () => {};
```
4. `npm run postbuild` in git terminal

**Expected behavior**
create a robots.txt file and sitemap.xml in public folder?

**Screenshots**
When I want to deploy my app to Vercel there is an error while building:
![image](https://user-images.githubusercontent.com/62507500/153723350-891af27c-4428-4250-b9cf-4ee3a8f90262.png)

**Additional context**
I've installed cross-env package and add `"postbuild": "cross-env next-sitemap --config next-sitemap.js"` but hasn't helped.... :/

getPortfolioSlugs function btw.
```js
import { GraphQLClient, gql } from "graphql-request";
const endpoint = process.env.REACT_APP_GRAPHCMS_API;

export const getPortfolioSlugs = async () => {
  const graphQLClient = new GraphQLClient(endpoint);

  const query = gql`
    {
      portfolios {
        slug
      }
    }
  `;
  return await graphQLClient.request(query);
};

```

**Comment by iamvishnusankar** [comment]
@bubuq3 Please read https://github.com/iamvishnusankar/next-sitemap#building-sitemaps

**Comment by bubuq3** [comment]
changed in /pages/server-sitemap.xml a line of code: from `export default Sitemap = () => {}` to `export default function Sitemap() {}` and it generated the sitemap BUT the code I took was from next-sitemap snippet example :D
now when I want to enter: `http://localhost:3000/server-sitemap.xml` there is an error `slugs.map is not a function`

```js
import { getServerSideSitemap } from "next-sitemap";
import { getPortfolioSlugs } from "../../lib/data";

export const getServerSideProps = async (ctx) => {
  // Method to source urls from cms
  const slugs = await getPortfolioSlugs();

  const fields = slugs.map((slug) => ({
    loc: `https://mywebsite.vercel.app/portfolio/${slug.slug}`,
    lastmod: new Date().toISOString(),
  }));

  return getServerSideSitemap(ctx, fields);
};

export default function Sitemap() {} // good
// was `export default Sitemap = () => {}` and it was causing the problem that I couldn't generate a sitemap and robots.txt
```
