### ISSUE TITLE
Support dynamic sitemap index generation

### ISSUE THREAD

**Issue by stefanb2** [iamvishnusankar/next-sitemap#299]
**Is your feature request related to a problem? Please describe.**
`robotsTxtOptions.additionalSitemaps` allows to add additional sitemaps, which also get added to the sitemap index. You can't use this for additional sitemap indices, because nested sitemap indices aren't allowed by the standard.

**Describe the solution you'd like**
* add `robotsTxtOptions.additionalSitemapIndices` to add additional lines to `robots.txt` but not to the auto-generated sitemap index.
* add `getServerSideSitemapIndex()` to simplify writing dynamic sitemap index generation.

**Describe alternatives you've considered**
Roll back to @1 of the module which doesn't generate a sitemap index and where `robotsTxtOptions.additionalSitemaps` can therefore be used to add dynamic sitemap indices.

**Additional context**
From our package.json: `"next-sitemap": "^2.1.14",`

**Side note**
The package adds both the auto-generated sitemap index and the auto-generated sitemaps to `robots.txt`. IMHO that will lead to double submissions of URLs (once through index -> sitemap -> URL and once through sitemap -> URL). I think only the auto-generated sitemap index should be added to `robots.txt`.

**Comment by stefanb2** [comment]
This is somewhat like the old PR #69, because not everything suggested there has been implemented by PR #268. Actually API @2 now makes dynamic sitemap indices impossible.

**Comment by iamvishnusankar** [comment]
@stefanb2 Thanks for reporting this. Added support via #300 

See `robotsTxtOptions.includeNonIndexSitemaps` section to see how duplicate url submission is handled.

**Comment by stefanb2** [comment]
Thanks, I did a quick update and it seems to address all outstanding issues for us.

I no longer have hand-generate XML code for dynamic sitemap indices :-)
