### ISSUE TITLE
Index sitemap does not reference the generated sitemaps

### ISSUE THREAD

**Issue by jopesh** [iamvishnusankar/next-sitemap#301]
**Describe the bug**
Upgraded from `^2.1.15` to `^2.4.1` and now the following happens on `next build`: 

* `sitemap.xml` and `sitemap-0.xml` are produced as expected.
* `sitemap-0.xml` does have the expected content
* `sitemap.xml` however yields:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">

</sitemapindex>
```
Hence, not referencing the `sitemap-0.xml`. The configuration file has not been modified.

**To Reproduce**
Steps to reproduce the behaviour:

1. Upgrade package  from `^2.1.15` to `^2.4.1`
2. Run `next build`
3. Validate the generated files 

**Expected behavior**
Expected output of `sitemap.xml` would've been:
```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://johnschmidt.de/sitemap-0.xml</loc>
  </sitemap>
</sitemapindex>
```

**Additional context**
Contents of the configuration file:
```js
/** @type {import('next-sitemap').IConfig} */

module.exports = {
  siteUrl: "https://johnschmidt.de",
  generateRobotsTxt: true,
}
```

**Comment by iamvishnusankar** [comment]
@jopesh Thanks for reporting this. Fixed #302
