### ISSUE TITLE
<trailingSlash>true</trailingSlash> found in the sitemap.xml

### ISSUE THREAD

**Issue by dominicarrojado** [iamvishnusankar/next-sitemap#316]
**Describe the bug**
`<trailingSlash>true</trailingSlash>` found in the `sitemap.xml`

**To Reproduce**

Code sandbox: https://codesandbox.io/s/interesting-tu-toztvx?file=/public/sitemap-0.xml:705-740

**Expected behavior**
It should not have `<trailingSlash>true</trailingSlash>` in the `sitemap.xml`

**Screenshots**
<img width="638" alt="image" src="https://user-images.githubusercontent.com/6789191/156366772-2f97fc96-c130-4f50-b4c9-4bef4864f79f.png">

**Additional context**
I'm using `next-sitemap@2.5.3`

**Comment by iamvishnusankar** [comment]
@dominicarrojado Fixed: #317
