### ISSUE TITLE
Sitemap Size being ignored

### ISSUE THREAD

**Issue by donhook** [iamvishnusankar/next-sitemap#318]
I just updated to 2.5.4 and now my sitemap has been split into 2 files ... a sitemap.xml and sitemap-0.xml

I have set the sitemap size to 10000 as I only want one sitemap ... not a sitemap-0 file.

increasing the sitemap size still produces the sitemap.xml and sitemap-0.xml

What am i missing?

Here is the config:

module.exports = {
    siteUrl: process.env.SITE_URL || 'https://www.xxx.com',
    generateRobotsTxt: true, // (optional)
    priority: false, // (optional)
    changefreq: false, // (optional)
    sitemapSize: 10000,
    // ...other options
  }

Here is the sitemap-0.xml. - 6848 characters.

<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url><loc>https://www.fullonconsulting.com</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/about-us</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/application-rationalization-program</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/data-warehouse-project</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/disaster-recovery-project</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/it-transformation-program</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/jamstack-project</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/sap-hr-hcm-program</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/sap-upgrade-project</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/client-success/servicenow-project</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/contact-us</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/insights</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/insights/first-90-days-as-cio</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/insights/making-it-a-differentiator</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/lp/12-reasons-why-it-initiatives-fail</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/lp/how-to-make-digital-transformation-succeed</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/privacy-policy</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/business-consulting/business-process-improvement</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/business-consulting/business-transformation</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/business-consulting/change-management</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/business-consulting/customer-experience</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/business-consulting/mergers-and-acquisitions</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/enterprise-applications/oracle-consulting</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/enterprise-applications/salesforce-consulting</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/enterprise-applications/sap-consulting</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/enterprise-applications/servicenow-consulting</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/service-delivery/agile-development</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/service-delivery/devops</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/service-delivery/pmaas</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/service-delivery/program-management</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/service-delivery/project-management</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/digital-transformation</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/ecommerce</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/enterprise-architecture</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/interim-cio</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/interim-cto</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/strategy/it-strategy</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/application-integration</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/data-analytics-and-visualization</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/data-management</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/data-science</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/jamstack</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/mobile-development</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/user-interface-design</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/what-we-do/technology-enablement/web-development</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
<url><loc>https://www.fullonconsulting.com/who-we-are</loc><lastmod>2022-03-05T13:40:56.512Z</lastmod></url>
</urlset>

**Comment by iamvishnusankar** [comment]
@donhook Read: https://github.com/iamvishnusankar/next-sitemap#index-sitemaps

**Comment by donhook** [comment]
why?

**Comment by iamvishnusankar** [comment]
More about index sitemap: https://support.google.com/webmasters/thread/76418206?hl=en&msgid=76452426
