### ISSUE TITLE
Deployments to Vercel are failing because of Node 14.18.3 version requirement

### ISSUE THREAD

**Issue by raphaelsaunier** [iamvishnusankar/next-sitemap#330]
**Describe the bug**

Deployments to Vercel are failing because of the Node >=14.18.3 requirement.

```
error next-sitemap@2.5.9: The engine "node" is incompatible with this module. Expected version ">=14.18.3". Got "14.18.1"
17:28:24.273
```

**To Reproduce**

1. Try to deploy a Next.js project that uses `next-sitemap` to Vercel.com

**Expected behavior**

`next-sitemap` should require Node >= 14.18 (without specifying an explicit patch version)

**Screenshots**
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/170256/158427611-197c3b8b-e3ee-43d7-acac-a3c9a79e15a4.png">

**Additional context**

**Comment by milo-** [comment]
Also seeing this all of a sudden although everything was building fine earlier today with the same version

**Comment by milo-** [comment]
Also seeing this all of a sudden although everything was building fine earlier today with the same version
