### ISSUE TITLE
sitemapSize parameter for dynamic sitemaps

### ISSUE THREAD

**Issue by byrneml** [iamvishnusankar/next-sitemap#335]
**Is your feature request related to a problem? Please describe.**
Not sure how to chunk dynamic sitemaps the way that static ones are chunked. EG I am generating multiple server-sitemaps and need to split them into something like the following and am not sure how to:
-  server-sitemap-a-1
- server-sitemap-a-2
- server-sitemap-b-1
- server-sitemap-b-2 

**Describe the solution you'd like**
When generating multiple dynamic sitemaps, it would be good to have a `sitemapSize` parameter that dynamically chunks all sitemaps, not just static ones.

**Describe alternatives you've considered**
Manually splitting the dynamic sitemaps into chunks of 10k

**Comment by kuladeep3** [comment]
A bigupvote. I do have the same requirement where i need to generate dynamic sitemap and split them into multiple files. Would be great to have this feature.

**Comment by Shofol** [comment]
@byrneml , how did you manually split dynamic sitemaps into chunks of 10k? Can you share your code? Facing the same issue.

**Comment by dastrong** [comment]
The solution for this was mentioned in a past issue:

https://github.com/iamvishnusankar/next-sitemap/issues/228#issuecomment-1007893976
