### ISSUE TITLE
Wrong field order inside <url> ? 

### ISSUE THREAD

**Issue by JuroUhlar** [iamvishnusankar/next-sitemap#345]
First of all, thanks for maintaining this helpful package :)

**Describe the bug**

The XML fields inside `<url>` seem to be in the wrong order? 

**To Reproduce**

Generate any sitemap with the default config. You get a structure like this: 

```
<url>
  <loc>https://www.example.com/about</loc>
  <changefreq>daily</changefreq>
  <priority>0.7</priority>
  <lastmod>2022-03-24T07:12:41.525Z</lastmod>
</url>
```

But according to the [sitemap schema](https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd) the package itself references, it should be: 

```
<xsd:sequence>
  <xsd:element name="loc" type="tLoc"/>
  <xsd:element name="lastmod" type="tLastmod" minOccurs="0"/>
  <xsd:element name="changefreq" type="tChangeFreq" minOccurs="0"/>
  <xsd:element name="priority" type="tPriority" minOccurs="0"/>
  <xsd:any namespace="##other" minOccurs="0" maxOccurs="unbounded" processContents="strict"/>
</xsd:sequence>
```

Apparently Google can get tripped up on this.

**Expected behavior**

The XML fields are in the expected order: 

```
<url>
  <loc>https://www.example.com/about</loc>
  <lastmod>2022-03-24T07:12:41.525Z</lastmod>
  <changefreq>daily</changefreq>
  <priority>0.7</priority>
</url>
```

**Comment by iamvishnusankar** [comment]
> Apparently Google can get tripped up on this.

@JuroUhlar Can you please provide little more context about this?

**Comment by JuroUhlar** [comment]
I think Google Search Console was flagging this as an issue with the sitemap. The XML does not conform to the schema.

**Comment by iamvishnusankar** [comment]
I don't think XML node order would be an issue. However, I'm not sure about it as well, can you share the flagging message/screenshot?

**Comment by iamvishnusankar** [comment]
Closing this issue now, feel free to open it when you have more updates about this.

**Comment by JuroUhlar** [comment]
I think it is. Or at least Google Search Consle thinks it is. I dug up the screenshot from my teammate: 
![image](https://user-images.githubusercontent.com/11249993/171884218-e80dba89-e9fe-435d-96f0-00a07967abde.png)

But I would think running your result through any XML schema validator will fail. The schema defines the elements as children of `<xsd:sequence>` meaning they must the present in the expected order. 
https://www.w3schools.com/xml/el_sequence.asp

**Comment by iamvishnusankar** [comment]
@JuroUhlar Thanks for sharing the debug info and more details about this. I wasn't aware of the `xsd:sequence` order. However, I've fixed the xml order. #405.
