### ISSUE TITLE
put in a custom message to robots.txt

### ISSUE THREAD

**Issue by myriky** [iamvishnusankar/next-sitemap#350]
**Is your feature request related to a problem? Please describe.**

I don't know exactly if this syntax is standard.
I want to insert the following phrase into the robots.txt for a specific search engine.

```
robots.txt

#DaumWebMasterTool:blablablabla7cbee386:OOBnc7VzmVsuhgOh/DzTfQ==
```

**Describe the solution you'd like**

```
next-sitemap.js

module.exports = {
	.....  
	generateRobotsTxt: true,
	robotsTxtOptions: {
		customTexts: [
		        "#DaumWebMasterTool:blablablabla7cbee386:OOBnc7VzmVsuhgOh/DzTfQ=="
                 ]
	}
}
```
As with this, I hope there is a way to add custom messages.

Thank you for your commitment. 👍

**Comment by myriky** [comment]
I've been looking for this CRAPPY syntax, which Apple also uses. lol

https://www.apple.com/robots.txt

**Comment by djfarly** [comment]
I'd be really cool if this could be done via a `transformRobotsTxt` function (`(robotsTxt: string) => string`) in the config. That would allow for all kind of modifications like this: https://www.nike.com/robots.txt

❤️
