### ISSUE TITLE
Best practice of connection

### ISSUE THREAD

**Issue by 1LEN1** [iamvishnusankar/next-sitemap#352]
I have different sitemaps which were generated on server side, and want to ask about best practices how to connect it in next-sitemap.js

Now it looks like that
![Снимок экрана 2022-03-30 в 12 22 30](https://user-images.githubusercontent.com/48198711/160798112-2eb9e9b6-050b-4098-aed9-e1520ffec68c.png)

**Comment by guillermo-avalos** [comment]
That's how I'm doing it. Do we need to have a `sitemap` folder for each dynamic route though? I feel it visually pollutes my file structure.
