### ISSUE TITLE
Wrong XHTML namespace

### ISSUE THREAD

**Issue by ilidev** [iamvishnusankar/next-sitemap#360]
**Describe the bug**
Currently is next-sitemap (NS) using xhtml namespace **http://www.w3.org/1999/xhtml** but sitemap shown in browser is as plain/text.

**To Reproduce**
Visit generated sitemap-(x).xml

**Expected behavior**
Sitemap is shown as xml

**Screenshots**
![A](https://user-images.githubusercontent.com/8217218/162435577-684e3e17-750e-480f-be44-ea9d5b59faf8.png)
![B](https://user-images.githubusercontent.com/8217218/162435579-27e36216-e185-4093-aee2-18dc87134aad.png)

**Solution**
Replace by new namespace: **http://www.w3.org/TR/xhtml1-schema**

**Comment by scottgrunerud** [comment]
Any movement on this ?

**Comment by ilidev** [comment]
Nothing I know :/
