### ISSUE TITLE
Deploying Sitemap on Vercel Custom Domain 

### ISSUE THREAD

**Issue by vvillait88** [iamvishnusankar/next-sitemap#367]
**Describe the bug**
When I deploy my app on Vercel, next-sitemap runs fine but it deploys on the wrong domain and when visiting /sitemap.xml on the alternative domain, the file is not found.  You can check it out here: blog-iz2hgxdv9-pdl.vercel.app/sitemap.xml and then blog.peopledatalabs.com/sitemap.xml

Have you found a workaround to this?

**To Reproduce**
1. Create a vercel app with a custom domain
2. Follow normal steps to deploy the app
3. Check the build logs and you will see it deploys to the main vercel domain but not the custom domains

**Expected behavior**
Sitemap should be available on any domain associated with the Vercel app.

**Screenshots**
<img width="728" alt="image" src="https://user-images.githubusercontent.com/7389451/163177956-f4e4d8c9-d4d4-4553-879d-c763c45a8e3b.png">

**Comment by bahrmichael** [comment]
If you followed the example, I assume your sitemap config uses `process.env.SITE_URL`. I didn't see this exact env var in the vercel docs, but others like `VERCEL_URL` which seem to give the deloyed url but not the custom domain.

What I use instead, is the following code:

```
process.env.NEXT_PUBLIC_VERCEL_ENV === "production" ? "https://www.my-domain.com" : "http://localhost:3000"
```

**Comment by vvillait88** [comment]
yeah i do this but for some reason the sitemap is only available at the default vercel build domain and not at the custom one (the links are pointed to the custom domain, but the sitemap isn't).  See here: https://blog.peopledatalabs.com/sitemap.xml and https://blog-iz2hgxdv9-pdl.vercel.app/sitemap.xml

**Comment by alastairlangridge** [comment]
@vvillait88 how did you resolve this?

**Comment by vvillait88** [comment]
I ended up rolling my own solution @alastairlangridge
