### ISSUE TITLE
feature request: add optional parameter to point to a config file

### ISSUE THREAD

**Issue by mcansh** [iamvishnusankar/next-sitemap#37]
my [project](https://github.com/mcansh/blog)  uses typescript and [next-mdx-remote](https://github.com/hashicorp/next-mdx-remote) so some things like modified date are added to my frontmatter at build time. i can add the functionality either tonight, tomorrow, or sometime next week.

**Comment by iamvishnusankar** [comment]
Hey @mcansh, I'm sorry I don't understand your problem. Can you please elaborate the issue a little more?

**Comment by iamvishnusankar** [comment]
Hey, @mcansh. It's still within the scope of this project. You can use the `transform` method to add/modify `lastmod` property for each url.
