### ISSUE TITLE
Add custom <sitemap><loc>... entry to sitemapindex

### ISSUE THREAD

**Issue by peaffenzeller** [iamvishnusankar/next-sitemap#370]
**Is your feature request related to a problem? Please describe.**
hi, I'm currently trying to generate two sitemaps - one including all the pages from a CMS, the other including job postings from an applicant tracking system. the one with the pages from the cms is created using next-sitemap, excluding all pages with ```/jobs/``` in the url. for the jobs, I create another sitemap that I can add to the ```robots.txt``` with the ```additionalSitemaps``` config, but I didn't manage to create a new ```<sitemap>``` element in ```sitemap.xml```

using ```getServerSideSitemap``` unfortunately is not an option, since I'm using ```next export```, which is not working with ```getServerSideProps```...

**Describe the solution you'd like**
be able to add additional sitemaps with SSG

**Describe alternatives you've considered**
- provide some utility (similar to ```getServerSideProps```) to add additional sitemaps
- additional config field to add ```<sitemap>``` entries
- config to explicitly tell what urls should go into what sitemap. something like the custom transform, with an option to tell that e.g. all urls including ```/jobs/``` should go into ```sitemap-jobs.xml``` and all others to the default ```sitemap-0.xml``` or other explicitly named sitemaps. currently, it's only possible to split into multiple smaller sitemaps with the ```sitemapSize``` config, but there's no way to name the generated sitemaps or tell which entries should go where.

**Comment by x6o** [comment]
Bump. This proposed enhancement is quite needed in my opinion because for example, in my project we need to bundle multiple sitemaps into the index, and some of are generated from the backend.

**Comment by Pnlvfx** [comment]
Any fix for this?
