### ISSUE TITLE
How to remove Host in robots

### ISSUE THREAD

**Issue by HidemitsuHashimoto** [iamvishnusankar/next-sitemap#381]
**Is your feature request related to a problem? Please describe.**
Is not a problema but my SEO ask me about this Host in robots.
![Screenshot_1](https://user-images.githubusercontent.com/37240367/166923023-1f5eff38-c52d-4166-8ec5-84a282a649d8.png)

**Describe the solution you'd like**
Can i remove the Host line in robots.txt?

**Describe alternatives you've considered**
This lib has a method in config to remove only this line?

**Comment by snup77** [comment]
Has the ability to remove the Host directive from robot.txt been added as an enhancement. I am also looking to remove Host but don't see it in the documentation.

**Comment by djad442** [comment]
i am also looking how to remove HOST directive, any idea?

**Comment by sreetamdas** [comment]
@HidemitsuHashimoto @snup77 @djad442 The package provides a `robotsTxtOptions` option that we can use to alter the generated `robots.txt`, I tried this out locally and got it working:

```js
/** @type {import('next-sitemap').IConfig} */
module.exports = {
	siteUrl: process.env.SITE_URL,
	generateRobotsTxt: true,
	robotsTxtOptions: {
		transformRobotsTxt: async (_, robotsTxt) => {
			const withoutHost = robotsTxt.replace(
				`# Host\nHost: ${process.env.SITE_URL}\n\n`,
				"",
			);

			return withoutHost;
		},
	},
};
```

Result (diff of default `robots.txt` vs after adding the above snippet):

```diff
# *
User-agent: *
Allow: /

- # Host
- Host: https://example.com
- 
# Sitemaps
Sitemap: https://example.com/sitemap.xml
```
