### ISSUE TITLE
Add trailing slash to only the index url

### ISSUE THREAD

**Issue by AaronMcCloskey** [iamvishnusankar/next-sitemap#411]
**Describe the bug**
Similar to [this](https://github.com/iamvishnusankar/next-sitemap/issues/221#issue-1015287533) issue. I just want the trailing slash to be added to the index URL, but not to any other url.

**To Reproduce**
```
const siteUrl = `${process.env.NEXT_PUBLIC_DOMAIN}/`;

const ADDITIONAL_SITEMAPS = ['club-sitemap'];

const getAdditionalSitemaps = () => ADDITIONAL_SITEMAPS.map((s) => `${siteUrl}sitemaps/${s}.xml`);

module.exports = {
  siteUrl,
  generateRobotsTxt: true,
  sitemapSize: 5000,
  // trailingSlash: true, // adds forward slash to all URLs
  robotsTxtOptions: {
    policies: [{ userAgent: '*', allow: '/' }],
    additionalSitemaps: getAdditionalSitemaps(),
  },
  exclude: ['/sitemaps/*'], // exclude all additional sitemaps, don't need to be included
};
```

Then run `yarn build` / `yarn next-sitemap`

**Expected behavior**
For sitemap to add trailing slash to index URL as so
```
<loc>http://localhost:3000/</loc>
```
and not
```
<loc>http://localhost:3000</loc>
```
And other URLs to be added as so
```
<loc>http://localhost:3000/login</loc>
```
and not
```
<loc>http://localhost:3000/login/</loc>
```

Or is it better practice to add `trailingSlash: true` and then setting the `canonical` `href` attribute in the `head` tag to add the trailing slash for indexing by google?

**Comment by iamvishnusankar** [comment]
@AaronMcCloskey Please read: https://github.com/iamvishnusankar/next-sitemap#custom-transformation-function

While writing a custom transformation method, you can pass `trailingSlash: false` property and it will disable the trailingSlash for that particular URL.
