### ISSUE TITLE
alternateRefs are not generating multiple locale versions 

### ISSUE THREAD

**Issue by Vanluren** [iamvishnusankar/next-sitemap#413]
**Describe the bug**
Hey guys, 
[According to the google developers guide
](https://developers.google.com/search/docs/advanced/crawling/localized-versions#sitemap) a multi-locale website should have multiple locations specified in the sitemap indicating the base URL and localization element(i.e. `https://mysite.io/de`) for all locales. Whenever I define `alternateRefs` and generate the sitemap using the package, this is not followed.

Am I doing something wrong or is this not what the package is supposed to do?

**To Reproduce**
Using the following config:

```js
const SITE_URL = process.env.NEXT_PUBLIC_URL || 'https://mysite.io'

/** @type {import('next-sitemap').IConfig} */
const config = {
  siteUrl: SITE_URL,
  alternateRefs: [
    {
      href: SITE_URL,
      hreflang: 'en',
    },
    {
      href: SITE_URL + '/de',
      hreflang: 'de',
    },
  ],
  sitemapSize: 1000,
}

module.exports = config
```

Results in the following sitemap:

```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://mysite.io/sitemap-0.xml</loc>
</sitemap>
</sitemapindex>
```

**Expected behavior**
The generated sitemap should contain definitions for all locales defined in `alternateRefs`

**Comment by iamvishnusankar** [comment]
@Vanluren Read: https://github.com/iamvishnusankar/next-sitemap#index-sitemaps-optional
