### ISSUE TITLE
Missing `dist/` directory for `v3.0.10`

### ISSUE THREAD

**Issue by sabertazimi** [iamvishnusankar/next-sitemap#418]
**Describe the bug**

[v3.0.10](https://unpkg.com/browse/next-sitemap@3.0.10/) missing `dist/` directory.

**To Reproduce**

![next-sitemap v3.0.10](https://user-images.githubusercontent.com/12670482/174489560-98852d12-93db-42ad-b514-20b82b9f1a22.png)

**Expected behavior**

![next-sitemap v3.0.5](https://user-images.githubusercontent.com/12670482/174489571-0f0a9efe-0961-4c6c-920c-7cac77124fce.png)

**Comment by iamvishnusankar** [comment]
@sabertazimi Thanks a lot for reporting this. I'm using azure pipeline for release. Some folders are not getting published to npm unless specified within `package.json`. Fixed: #419
