### ISSUE TITLE
List of breaking changes in 3.x

### ISSUE THREAD

**Issue by jekh** [iamvishnusankar/next-sitemap#424]
I didn't see a list of breaking changes in 3.x anywhere. What caused the major version number bump? What do consumers of 2.x need to know in order to upgrade?

**Comment by jekh** [comment]
@iamvishnusankar Can you give us any insights here? There must have been a reason for the major version bump.

**Comment by christian98** [comment]
Why is this closed without any response? If there is a list now, can anyone add a link here? I could not find it.
