### ISSUE TITLE
Hello, I'm getting the following error with next-sitemap on running yarn build:

### ISSUE THREAD

**Issue by RamboGj** [iamvishnusankar/next-sitemap#444]
`error An unexpected error occurred: "Potentially dangerous call to \"next-sitemap\" in C:\\sonica-web3\\app`
![nexttime](https://user-images.githubusercontent.com/64593022/179821377-a343b558-6014-437c-bbf1-0cbe3115dc72.png)

**Comment by hemerson-git** [comment]
Same here.

Here are my next-sitemap.js configs:

![image](https://user-images.githubusercontent.com/48595787/204855555-fcd70d11-b03b-4186-8f78-737c5449e811.png)

![image](https://user-images.githubusercontent.com/48595787/204855847-8e3e5cbd-cc68-4104-aafe-c8d0ffb86545.png)

**Comment by Mathias-21** [comment]
Same bug
![error next-sitemap](https://user-images.githubusercontent.com/78583100/205326746-ea26d0ff-7510-4c3b-ba34-32d132e27765.png)

**Comment by iamvishnusankar** [comment]
It can happen due to `next-sitemap.js` file having the same name as `next-sitemap` bin command. Try to rename your config to `next-sitemap.config.js` and pass the filename to build command as follows.

```json
{
  "build": "next build",
  "postbuild": "next-sitemap --config next-sitemap.config.js"
}
```
