### ISSUE TITLE
Rewrites not taking into consideration

### ISSUE THREAD

**Issue by thebiltheory** [iamvishnusankar/next-sitemap#448]
**Is your feature request related to a problem? Please describe.**
A sitemap will be generated using the file names only and not taking url rewrites into consideration. 
Take the following url rewrite in `next.config.js` for the file `pages/terms-of-services`: 
```
{
   source: "/conditions-generales",
   destination: "/terms-of-service",
},
```

**Describe the solution you'd like**
I am expecting the above code to generate a sitemap with the following XML
```diff
<url>
-  <loc>http://localhost:3004/terms-of-service</loc>
+  <loc>http://localhost:3004/conditions-generales</loc>
   <lastmod>2022-07-26T09:09:58.904Z</lastmod>
   <changefreq>daily</changefreq>
   <priority>0.7</priority>
</url>
```

**Describe alternatives you've considered**
Nothing yet. Since I have a lot of rewrites would be hard to rename all pages.

**Additional context**
n/a

**Comment by corysimmons** [comment]
Why remove `/terms-of-service`? Keep both.

**Comment by fanttis** [comment]
You can define redirects in a separate file and import to `next.config` for redirects and to `next-sitemap.config.js` to be used for `exclude`.
Redirects should not be included in Sitemap as it's considered a SEO issue

**Comment by Ilnore** [comment]
Rewrites are not redirects though, they're more of an URL proxy, where you possibly want to hide an internal implementation URL, and replace it to be shown for clients as a different URL.
https://nextjs.org/docs/api-reference/next.config.js/rewrites

We also are having trouble with the fact that the library drops rewrites from the sitemap output.
