### ISSUE TITLE
Can't generate multiple server side sitemaps according to size defined in next-sitemap.config

### ISSUE THREAD

**Issue by mansisindhu** [iamvishnusankar/next-sitemap#449]
I'm dynamically generating server side sitemaps, I have a list of items with total number 70k, but max limit of sitemap is 50k. I want to divide it in multiple sitemaps but `sitemapSize` in `next-sitemap.config` is not working in this case. I did set `sitemapSize` to 7000, but not working.

I guess there is no config for server side sitemap generation. Please help in this issue.

**Comment by iamvishnusankar** [comment]
@mansisindhu Please read: https://github.com/iamvishnusankar/next-sitemap/issues/92#issuecomment-761505090
