### ISSUE TITLE
Generated only during build? Dynamically? Cached?

### ISSUE THREAD

**Issue by emkayy** [iamvishnusankar/next-sitemap#450]
It is not quite clear to me if the sitemap is only built during build time or also dynamically on the server.
Since my site has a lot of dynamic URLs (also new ones) I can't generate it during build time and also not on every request but need some caching. 

So does this module generate sitemaps dynamically or can it be triggered manually?
Does it have some kind of caching mechanism?

**Comment by jlarmstrongiv** [comment]
It’s both 😄 The sitemap is built with any pages and urls in the getStaticPaths, but also allows you to add your own dynamic sitemaps too.

**Comment by emkayy** [comment]
Ok, great! Thanks a lot!
Maybe it would be interesting to people looking for a solution in the future to add this information to the description? Or add some examples that make it clear how powerful your plug-in is?
