### ISSUE TITLE
Dynamic sitemap appears both in index sitemap and in robots.txt

### ISSUE THREAD

**Issue by Lizusha** [iamvishnusankar/next-sitemap#451]
I copied the example from the "server side sitemap (getServerSideSitemap)" section in the docs. And I got in sitemap.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap><loc>https://example.com/sitemap-0.xml</loc></sitemap>
  <sitemap><loc>https://example.com/server-sitemap.xml</loc></sitemap>
</sitemapindex>
```

And in robots.txt:
```
Sitemap: https://example.com/sitemap.xml
Sitemap: https://example.com/server-sitemap.xml
```

But https://example.com/server-sitemap.xml is not an index sitemap and it's already listed in sitemap.xml so why do we need it in robots.txt?

**Comment by oleggrishechkin** [comment]
Same issue. Will be good to have some option to add server sitemaps only to index sitemap

@Lizusha For me this works (just remove my additional sitemaps and keep generated index sitemap):
```javascript
robotsTxtOptions: {
    transformRobotsTxt: async (config, robotsTxt) =>
      config.robotsTxtOptions.additionalSitemaps
        .slice(1)
        .reduce((res, item) => res.replace(`Sitemap: ${item}\n`, ''), robotsTxt),
    ...
},
```
