### ISSUE TITLE
output is not alphabetically sorted

### ISSUE THREAD

**Issue by bonesoul** [iamvishnusankar/next-sitemap#452]
basically the output is not alphabetically sorted and each time i build the site, even though it's okay for time & date info to get updated, the pages sorting is scrambled and i get a different diff each time.

any solutions?

**Comment by iamvishnusankar** [comment]
@bonesoul Can you please provide additional details about why alphabetical sort is required?

**Comment by bonesoul** [comment]
I've a huge sitemap with with at least 3000+ entries:

```
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/kisitlamasiz</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/karantina-tavsiyesi</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/karantina-gerekebilir</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/gidis-ve-donuste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/gidiste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/sadece-gidiste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/donuste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/sadece-donuste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/tumu</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/kisitlama/bilinmeyen</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/vize-basvurusu/kisitlamasiz</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/vize-basvurusu/karantina-tavsiyesi</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/vize-basvurusu/karantina-gerekebilir</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/vize-basvurusu/gidis-ve-donuste-kisitlama</loc><lastmod>2022-07-28T14:54:26.048Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
<url><loc>https://www.vizesizgezi.com/seyahat/vize-basvurusu/gidiste-kisitlama</loc><lastmod>2022
```

all those 3000 pages are statically generated on server side:
when all those urls are alphabetically sorted i can check out diff the builds to see if anything is missing or incorrect basically.

of course, different priories should be alphabetically sorted on their own sublist.

**Comment by gragland** [comment]
+1 for alphabetical sorting. When viewing the diff with hundreds of pages it can be hard to verify that only the intended changes are being made.

**Comment by bonesoul** [comment]
any chances we can see this get implemented?

**Comment by iamvishnusankar** [comment]
@bonesoul Can you provide a use case of alphabetical sorting?

**Comment by bonesoul** [comment]
this and this:

- https://github.com/iamvishnusankar/next-sitemap/issues/452#issuecomment-1200528379
- https://github.com/iamvishnusankar/next-sitemap/issues/452#issuecomment-1201779285

**Comment by Arunjenson-ss** [comment]
@iamvishnusankar can we sort it based on the latest modified date 
so that we can get urls where we have a updations

**Comment by keyserj** [comment]
I use next-sitemap for my nextra project, and for some reason after upgrading to nextra 4, my sitemap started being ordered differently after each build, so I figured sorting the URLs alphabetically afterwards would solve this.

As a jank solution I used the `head`, `tail`, & `sed` linux utilities to sort my sitemap after build, slightly modified from this stackoverflow answer https://stackoverflow.com/a/46018020/8409296:
`next-sitemap && { head -n 2 public/sitemap.xml; sed '1,2d;$d' public/sitemap.xml | sort; tail -n 1 public/sitemap.xml; } > public/sitemap.tmp && mv public/sitemap.tmp public/sitemap.xml`

Command explanation:
- `head -n 2`: take first 2 lines
- `sed '1,2d;$d ... | sort` : delete first 2 and last line, sort the rest
- `tail -n 1`: take last line
- `{ ... } > sitemap.tmp`: take all that output and put it into a file
- `mv sitemap.tmp sitemap.xml`: overwrite the original file with the result (can't read from and `>` to a file in the same command)
