### ISSUE TITLE
Async Excludes

### ISSUE THREAD

**Issue by georgebutter** [iamvishnusankar/next-sitemap#457]
**Is your feature request related to a problem? Please describe.**
I need to query 2 APIs and generate a list of URLs I wish to exclude. Currently exclude only accepts an array of strings. Alternatively, I could use transform which accepts an async function BUT this calls for each path which totally spams my API.

**Describe the solution you'd like**
I would like to be able to call my API once generate a list of excludes. Either this would extend the existing `exclude` option to accept a function or be a separate additional option such as `asyncExcludes`.

**Describe alternatives you've considered**
I've tried using `transform` as mentioned but this causes my API to get spammed.
`additionalPaths` only adds new paths.

I could potentially use the Dynamic site map approach but it's significantly more work + boilerplate to maintain it this way. I feel as though it's not much of a stretch to handle this use case in the config.

**Additional context**
Happy to raise the PR for this if you think this is a worthy proposal.

**Comment by georgebutter** [comment]
Something along the lines of 
```
    // Remove the urls based on this.config?.exclude array
    if (this.config?.exclude) {
      if (typeof this.config.exclude === 'function') {
        const asyncExcludes = await this.config.exclude();
        urlSet = removeIfMatchPattern(urlSet, asyncExcludes)
      }
      urlSet = removeIfMatchPattern(urlSet, this.config?.exclude)
    }
 ```
 Where exclude can be a function
 ```
   /**
   * Array of relative paths (wildcard pattern supported) to exclude from listing on sitemap.xml or sitemap-*.xml.
   * Apart from this option next-sitemap also offers a custom transform option which could be used to exclude urls that match specific patterns
   * @example ['/page-0', '/page-*', '/private/*']
   */
  exclude?: string[] | (() => Promise<string[]>)
 ```

**Comment by georgebutter** [comment]
PR: #458

**Comment by aa-jeremyhoover** [comment]
I'd like to see this PR merged, it looks like it would make this library usable for me.

Thanks!

**Comment by PeterKottas** [comment]
It would possibly make more sense to have the whole config file optionally return a promise. That way you can fetch any part of the config from various sources. Not just the exclude option.

**Comment by georgebutter** [comment]
@iamvishnusankar Do you have any feedback for this PR?
