### ISSUE TITLE
Build process complaining

### ISSUE THREAD

**Issue by Wollivan** [iamvishnusankar/next-sitemap#468]
## I followed the instructions to the letter and am getting the following build error:

<img width="1215" alt="Screenshot 2022-08-19 at 13 01 56" src="https://user-images.githubusercontent.com/91621088/185614443-13896e8c-6421-4513-90bf-6a829a360721.png">

## When I do what it says and add "type": "module" this is the new error:

<img width="1224" alt="Screenshot 2022-08-19 at 13 10 40" src="https://user-images.githubusercontent.com/91621088/185615618-7c85a8f4-da6e-4cb9-abd4-349787ea1b4a.png">

I'm hosting the site on vercel if that matters.

**Comment by MrRobz** [comment]
I exported the file as commonJS and things started to work
```
/** @type {import('next-sitemap').IConfig} */
const config = {
  siteUrl: process.env.SITE_URL || "https://www.robie.dev",
  generateRobotsTxt: true,
};

module.exports = config;
```

**Comment by Wollivan** [comment]
> module.exports = config;

Oh my word you are the MAN!

Thanks so much. You have no idea how many things I tried and how many different errors I managed to generate!

Bless you sir!
