### ISSUE TITLE
Can't exclude /sitemap.xml and /sitemap-0.xml

### ISSUE THREAD

**Issue by akzone** [iamvishnusankar/next-sitemap#471]
dynamic/server-side sitemaps already generated 

 /sitemap.xml and /sitemap-0.xml are duplicated, and unable to exclude

Thank you

**Comment by dkrefta** [comment]
Are we still with this problem? I created a static sitemap to handle that problem for now. thanks, guys!

**Comment by dkrefta** [comment]
completed 👀
