### ISSUE TITLE
undefined/sitemap.xml   undefined/sitemap-0.xml 

### ISSUE THREAD

**Issue by Kawan-edres** [iamvishnusankar/next-sitemap#472]
when npm run build and npm run post build i get the result of undefind and i provided my siteUrl.
here my files are :

next-sitemap.config.js
/** @type {import('next-sitemap').IConfig} */

const config = {
    siteUrl:"https://devspace.krd"||process.env.SITE_URL,
    generateRobotsTxt: true, // (optional)
    // ...other options
      outDir : "./out",

  }

And here its my package.json data

 "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "postbuild": " next-sitemap --next-sitemap.config.js"
  },

**Comment by yvikasofficial** [comment]
You are using wrong syntax.
 
This is the correct one: 
`"postbuild": "next-sitemap --config next-sitemap.config.js"`

**Comment by Kawan-edres** [comment]
![image](https://user-images.githubusercontent.com/69269939/186108145-b3d849d9-f514-4c70-87e3-c18984ac6445.png)
 I used your syntax too but again it does not fixes my problem

**Comment by Kawan-edres** [comment]
![image](https://user-images.githubusercontent.com/69269939/186108356-33d9e742-8c31-41b1-ae5d-1994bd414fb1.png)

**Comment by Kawan-edres** [comment]
and this is my next-sitemap.config.js
![image](https://user-images.githubusercontent.com/69269939/186108548-f8fa801d-7d03-4b43-9f45-608db72a4920.png)

**Comment by iamvishnusankar** [comment]
@Kawan-edres Can you provide a basic reproduction?

**Comment by Kawan-edres** [comment]
Thanks for your response , but what do you mean by reproduction , I did build my web page again do you mean rebuild or what ?

**Comment by magoz** [comment]
Almost likely you are passing `undefined` to `siteUrl`.
Check that you have properly set up your `.env` files and you are passing the right one.

**Comment by desmon91** [comment]
> and this is my next-sitemap.config.js ![image](https://user-images.githubusercontent.com/69269939/186108548-f8fa801d-7d03-4b43-9f45-608db72a4920.png)

Hello there. it seems like you are not exporting your config yet?
you try export it by adding this code below your config variable
`module.exports = { ...config };`

**Comment by Kawan-edres** [comment]
> > and this is my next-sitemap.config.js ![image](https://user-images.githubusercontent.com/69269939/186108548-f8fa801d-7d03-4b43-9f45-608db72a4920.png)
> 
> Hello there. it seems like you are not exporting your config yet? you can try to export it by adding this code below your config variable `module.exports = { ...config };`

Thanks a lot it fixes my problem I appreciate your answer
