### ISSUE TITLE
Cannot change the name of the root directory '.next'.

### ISSUE THREAD

**Issue by Pnlvfx** [iamvishnusankar/next-sitemap#476]
I've changed the default '.next' root directory in next.config.js but I cannot change it into next.sitemap.config.js. the result is that the build fail and I cannot do nothing if not come back to the default '.next'. Maybe I've lost something in the documentation or I hope that this feature will be added soon.!

**Comment by Kyoss79** [comment]
Nevermind this is possible:

you can add **sourceDir** and **outDir** to your next-sitemap.config.js
