### ISSUE TITLE
Add additional sitemap indices to robot.txt

### ISSUE THREAD

**Issue by stefanb2** [iamvishnusankar/next-sitemap#477]
**Is your feature request related to a problem? Please describe.**
Recursive sitemap indices aren't allowed by the standard, i.e. listing a URL to a sitemap index file in a sitemap index file. Unfortunately `robotsTxtOptions.additionalSitemaps` are automatically added to the generated sitemap index file, i.e. this should only be used for sitemap files.

**Describe the solution you'd like**
I guess adding `robotsTxtOptions.additionalSitemapIndices` would be the most logical choice. You could list sitemap indices that need to be added to `robots.txt` but not appear in the generated sitemap index file.

Another option would be to not include URLs from `robotsTxtOptions.additionalSitemaps` in the generated sitemap index file and add another option `additionalIndexPaths` or `additionalSitemaps` (on the config top-level) to handle the case when you need to add dynamically generated sitemaps to the generated sitemap index file.

**Describe alternatives you've considered**
There is no transform function for the generated sitemap index file, hence no possibility to filter those sitemap index files out.

I maintain two localized Next.js websites. In both cases the current version of `next-sitemap` doesn't allow me to generate the correct contents.
1. the generated sitemap references the index pages and it has dynamically generated **sitemap files**. For this setup the sitemaps should be included in the generated sitemap index file **but not** in `robots.txt` to avoid duplicate references.  
(The website has localized index pages where the URLs on the index page point to a single page -> it needs a sitemap file per locale)
2. the generated sitemap references the index pages and it has dynamically generated **sitemap index files**. For this setup the sitemap index files should only be listed in `robots.txt`.  
(The website has localized index pages where the URLs on the index page point to landing pages with more URLs -> it needs a sitemap index file per locale pointing to a list of sitemap files)

Both sites only generate the localized index pages during the build, all other pages are statically generated when referenced by users, hence the need for dynamically generated sitemap (index) files.

IMHO to solve both cases correctly you would need to implement the second suggested solution.

**Comment by Seelvex** [comment]
Hope this gets fixed asap.
