### ISSUE TITLE
Adding a sitemap to the robotsTxtOptions.additionalSitemaps list adds it to the sitemap index

### ISSUE THREAD

**Issue by andrewliden** [iamvishnusankar/next-sitemap#481]
**Describe the bug**
Adding a sitemap to the robotsTxtOptions.additionalSitemaps list adds it to the sitemap index. The exclude list does not solve this problem. I even tried excluding all by adding '*' to the exclude list. The sitemap in robotsTxtOptions.additionalSitemaps was still added to the index (and it was the only entry).
This is problematic, because it creates a nested sitemap index error. Nested sitemap indexes are generally unsupported by search engines.

**To Reproduce**

1. Create a serverside sitemap index using getServerSideSitemapIndex.
2. Attempt to exclude it using the exclude list.
3. Examine the generated sitemap.xml index.
4. Notice that the sitemap.xml index contains an index, which is a nested sitemap index, and thus a standards violation.

**Expected behavior**
Sitemap indexes should be included in robots.txt, but not in the sitemap.xml sitemap index. Excluding a sitemap index should remove it.

**Comment by ardeois** [comment]
I have the same issue too, did you find a workaround?

**Comment by ok4d4** [comment]
I'm having the same problem, and I'm dealing with it by disabling the robotsOption.

**Comment by Seelvex** [comment]
I'm also facing this issue while having multiple sitemap indexes for multiple post types. I need those indexes in the robots.txt.

@iamvishnusankar maybe you could consider adding a new option for `robotsTxtOptions.additionalSitemapIndexes` or something similiar in order that those indexes are not included in the array of sitemaps to be put inside the generated sitemap.xml index.
I am available to open a PR if you'd like to discuss it further. 
Appreciate your work on this package :)

**Comment by FINDarkside** [comment]
Any workarounds? This bug makes this library unusable. :thinking:

**Comment by FINDarkside** [comment]
Can this issue be opened? As far as I can see `next-sitemap` cannot create valid dynamic sitemaps at all so seems like pretty major issue to me. And even the fix is easy and it's already done: https://github.com/iamvishnusankar/next-sitemap/pull/568
