### ISSUE TITLE
Handling multiple config for multiple sitemap

### ISSUE THREAD

**Issue by FatManiac** [iamvishnusankar/next-sitemap#494]
**Is your feature request related to a problem? Please describe.**
I am trying to figure out how, with one build i can generate 2 sitemap. I actually generate them one after the other by building twice with different conf.

**Describe the solution you'd like**
i would be able to export multiple conf so that different sitemap may be created as i wish with different tranform options or excludes

**Describe alternatives you've considered**
New option additionnalSitemap where you inject other sitemap conf

**Additional context**
Right now i switch the order to get what i want while i build twice
`
/** @type {import('next-sitemap').IConfig} */

module.exports = {
  transform: async (config, path) => {
    if (path.includes('/code/cours/')) {
      return {
        loc: path,
        changefreq: config.changefreq,
        priority: config.priority,
      }
    } else {
      return null;
    }
  },
  siteUrl: process.env.PREVIEW_PUBLISHED_URL,
  sitemapBaseFileName: 'cours_sitemap',
  generateIndexSitemap: false,
}

module.exports = {
  transform: async (config, path) => {
    if (path.includes('/code/cours/') || path.includes('/redirects') || path.includes('/cours_sitemap')) {
      return null;
    } else {
      return {
        loc: path,
        changefreq: config.changefreq,
        priority: config.priority,
      }
    }
  },
  siteUrl: process.env.PREVIEW_PUBLISHED_URL,
  sitemapBaseFileName: 'sitemap',
  generateIndexSitemap: false,
}
`

that what i would like to be able to do, or something like that

`
/** @type {import('next-sitemap').IConfig} */

const coursSitemap = {
  transform: async (config, path) => {
    if (path.includes('/code/cours/')) {
      return {
        loc: path,
        changefreq: config.changefreq,
        priority: config.priority,
      }
    } else {
      return null;
    }
  },
  siteUrl: process.env.STRAPI_PREVIEW_PUBLISHED_URL,
  sitemapBaseFileName: 'cours_sitemap',
  generateIndexSitemap: false,
};

const sitemap = {
  transform: async (config, path) => {
    if (path.includes('/code/cours/') || path.includes('/redirects') || path.includes('/cours_sitemap')) {
      return null;
    } else {
      return {
        loc: path,
        changefreq: config.changefreq,
        priority: config.priority,
      }
    }
  },
  siteUrl: process.env.STRAPI_PREVIEW_PUBLISHED_URL,
  sitemapBaseFileName: 'sitemap',
  generateIndexSitemap: false,
}

module.exports = { coursSitemap, sitemap }
`

Thank you for considering

**Comment by GeoffreyOnRails** [comment]
Have you considered  `"postbuild": "next-sitemap --config awesome1.config.js && next-sitemap --config awesome2.config.js " `? :) 
Or would you like the enhancement to allow you to automatically create an index based on the various places you would have configured instead of being based on the size only, and have everything in one summary?

**Comment by FatManiac** [comment]
It worked fine thank you, the proposition is good that would be more readable
