### ISSUE TITLE
How to create only 1 sitemap file?

### ISSUE THREAD

**Issue by lennine3** [iamvishnusankar/next-sitemap#502]
As for the title, I just want to create only 1 sitemap file but I cannot find how to do that, I have read the doc but there is no answer for that. Can you help me do that? Thanks.

**Comment by vradriano** [comment]
Hey Lennine, you can just add: **generateIndexSitemap: false** at your next-sitemap,config.js.
![image](https://user-images.githubusercontent.com/90075349/195598565-3dab8e33-1cc7-40ce-9b45-84b3d918d77f.png)
