### ISSUE TITLE
Unable to find export-maker occurs in Nest.js

### ISSUE THREAD

**Issue by yangyangisyou** [iamvishnusankar/next-sitemap#505]
After  `next build`, our folder structure looks like
```
.next
- public
- src
  - export-marker.json
  - ...
```

But, we got this trouble
```
❌ [next-sitemap] Unable to find export-maker.
Make sure to build the project using `next build` command

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '.../.next/export-marker.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '.../.next/export-marker.json'
}
```

Is there any way to change export-marker path ?

**Comment by a7medmo7med9** [comment]
I encountered this problem a while ago and I found the cause of the problem and the solution

**1- cause of the problem**
        if you using nextjs [[distDir](https://nextjs.org/docs/api-reference/next.config.js/setting-a-custom-build-directory)] config in next.config.js or export build to another folder which is not .next (the default)

**2- my custom the solution**
create .next folder if not exist and copy this files from your build folder to .next folder
        
    1- yourBuildFolder/build-manifest.json
    2- yourBuildFolder/export-marker.json
    3- yourBuildFolder/prerender-manifest.json
    4- yourBuildFolder/routes-manifest.json

**You don't have to do this manually every time**
create a script that does this automatically

1- create js file **fixSiteMap.js** 
2- use this script or create your own


```js
const fs = require("fs");

// iam saving my custom build folder name to json file
// get your custom build path with your own way
const buildID = require("./getBuildID");

// copy build files to .next folder to fix createSitemMap
// check if build folder exist
if (fs.existsSync(buildID)) {
  // creating next dir if not exist in project root
  try {
    fs.mkdirSync("./.next");
  } catch (error) {}

  // copy files needed from real buld folder to .next
  const filesToCopy = ["/build-manifest.json", "/export-marker.json", "/prerender-manifest.json", "/routes-manifest.json"];

  for (const fileName of filesToCopy) {
    const fullPath = buildID + fileName;
    if (fs.existsSync(fullPath)) fs.copyFileSync(fullPath, "./.next" + fileName);
  }
}
```

3- run this script after every build from package.json like

```json
 "scripts": {
    "build": "next build && npm createSiteMap",
    "createSiteMap": "node fixSiteMap.js && next-sitemap",
  },
```

this is working for me

**Comment by yangyangisyou** [comment]
Thanks @a7medmo7med9 . I change sourceDir path, then it works.

```
module.exports = {
  sourceDir: './.next/src',
  ...
}
```

**Comment by asaharan** [comment]
Removing `distDir` was causing the issue, so removing that helped.

**Comment by AdrianMrn** [comment]
Setting `sourceDir` in my `next-sitemap.config.js` to the same value as my `distDir` from `next.config.js` solved the error for me!

**Comment by Corgile** [comment]
mine doesn't work, do you have any solutions? thx

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/48396880/210124806-77883dd2-35fd-4cc5-ba5d-106183958216.png">

**Comment by yangyangisyou** [comment]
@Corgile Hi, do you next-build success and create a build folder already? It looks like it can't find the path, or you can tune sourceDir to the relative path?
