### ISSUE TITLE
Google Search Console throws an error when trying to read a sitemap index generated by next-sitemap

### ISSUE THREAD

**Issue by jhyahav** [iamvishnusankar/next-sitemap#510]
**Describe the bug**
Google Search Console throws an `incorrect namespace` error when trying to read a sitemap index generated by next-sitemap.

**To Reproduce**
Create a sitemap with the sitemap index setting enabled, then try to add it to your site's Google Search Console.

**Expected behavior**
Google Search Console should be able to read the sitemap index without errors.

**Screenshots**

![image](https://user-images.githubusercontent.com/24489231/196471037-d1d02370-cf8b-463e-a2b9-0d558f914498.png)

**Suggested solution**
The problem appears to stem from a minor namespace misconfiguration caused by [`sitemap-builder.ts`](https://github.com/iamvishnusankar/next-sitemap/blob/master/packages/next-sitemap/src/builders/sitemap-builder.ts). 
See [this relevant Google Support thread](https://support.google.com/webmasters/thread/179371738?hl=en&msgid=179380014). 
See #511

**Comment by vdjurdjevic** [comment]
@iamvishnusankar Why is this closed? I think @johnnyc1120 is right, I still see wrong namespace, and google is rejecting the sitemap. Can we reopen this issue?

**Comment by iamvishnusankar** [comment]
@johnnyc1120 @vdjurdjevic Fixed: #520

**Comment by vdjurdjevic** [comment]
Awesome :) Thank you!

**Comment by vdjurdjevic** [comment]
When is it going to be merged and published to npm?

**Comment by iamvishnusankar** [comment]
@vdjurdjevic It'll be live as soon as these builds are completed https://github.com/iamvishnusankar/next-sitemap/runs/9201838180
