### ISSUE TITLE
Multi-tenant setup, dynamic user URL via Middleware

### ISSUE THREAD

**Issue by JanKups** [iamvishnusankar/next-sitemap#515]
**Is your feature request related to a problem? Please describe.**
I'm using a multi-tenant setup, which in my case provides users with a unique URL for their own public page. Currently, I believe, middleware routes are filtered out ([commit](https://github.com/iamvishnusankar/next-sitemap/commit/cc2036aa2e7ed3b6edd61da0396a5b01e0d7cf2b)). It would be great if those pages could be added to the sitemap dynamically.   

**Describe the solution you'd like**
Support for a multi-tenant setup. Example [middleware](https://github.com/vercel/platforms/blob/main/middleware.ts).

**Describe alternatives you've considered**
Add generated pages via additionalPaths, I am unsure if this can be done dynamically. 

A workaround or different approach to this setup would also be great.

**Comment by jlarmstrongiv** [comment]
Still active!  Please re-open

**Comment by SSardorf** [comment]
I have the same issue!
