### ISSUE TITLE
siteUrl is not getting set and returns undefined

### ISSUE THREAD

**Issue by cobaltwhite** [iamvishnusankar/next-sitemap#526]
I have just installed the latest version of the package on the latest version of NextJS. I can retrive the env variable for the siteUrl from the file, and also tried to hard coding it in as stated on the documentation, but sitemap is getting generated with the undefined siteUrl as listed below. Unsure if this is a mistake somewhere that I can't spot or perhaps a bug.

`module.exports = {
    siteUrl: "http://localhost:3000",
    changefreq: "daily",
    priority: 0.7,
    generateRobotsTxt: true,
    sitemapSize: 5000,
}`

### Error:
 SITEMAP INDICES
   ○ undefined/sitemap.xml

 SITEMAPS
   ○ undefined/sitemap-0.xml

**Sitemap XML**
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>undefined/sitemap-0.xml</loc>
</sitemap>
</sitemapindex>
```

**Comment by iamvishnusankar** [comment]
@cobaltwhite Thanks for reporting this? Could you please provide a reproduction?

**Comment by cobaltwhite** [comment]
@iamvishnusankar sure, I've put a fresh copy on here: [https://github.com/cobaltwhite/next-starter](url)

**Comment by iamvishnusankar** [comment]
@cobaltwhite Your `next-sitemap` config file is wrong. Here's the fixed version: [cobaltwhite/next-starter](https://stackblitz.com/edit/github-shstkx?file=public%2Fsitemap-0.xml,next-sitemap.config.js,next.config.js,public%2Fsitemap.xml)
