### ISSUE TITLE
Support new app folder in next13

### ISSUE THREAD

**Issue by cipriancaba** [iamvishnusankar/next-sitemap#527]
**Is your feature request related to a problem? Please describe.**
Next13 app folder is not supported, it doesn't generate all the paths from `generateStaticParams` just the static ones

**Describe the solution you'd like**
Sitemap to include dynamic routes

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by iamvishnusankar** [comment]
@cipriancaba `generateStaticParams` is already supported.

Example: https://github.com/iamvishnusankar/next-sitemap/tree/master/examples/app-dir

**Comment by switz** [comment]
But what about dynamic routes that don't include `generateStaticParams`. I'm not seeing any generated from my app dir.

**Comment by emilwalter** [comment]
Did you manage to solve this @switz ?

**Comment by lundjrl** [comment]
Shouldn't you generate your dynamic routes in generateStaticParams @switz ?
