### ISSUE TITLE
ERR_UNSUPPORTED_ESM_URL_SCHEME - next-sitemap

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [iamvishnusankar/next-sitemap#529]
hi
when I want build my project I got this error:
ERR_UNSUPPORTED_ESM_URL_SCHEME 

node version:
v14.11.0
next: 12.0.7

    next-sitemap.config.js

    module.exports = {
        siteUrl: 'https://*****.com',
        generateRobotsTxt: true,
        robotsTxtOptions: {
          additionalSitemaps: [
            'https://*****.com/server-sitemap-index.xml', // <==== Add here
          ],
        },
      }

inside this file:

pages/server-sitemap-index.xml/index.ts

    // @ts-nocheck
    import { getServerSideSitemapIndex } from 'next-sitemap'
    import { GetServerSideProps } from 'next'
    import { baseApiURL } from "src/utiles/constants.js";
    export const getServerSideProps: GetServerSideProps = async (ctx) => {
      // Method to source urls from cms
      const res = await axios(`${process.env.NEXT_PUBLIC_BASE_API}dental/generic/wide-range-of-services/`);
      const { data } = res.data;
      const fields = data.map((item) => ({
        loc: `${process.env.SITE_URL}service/${item.slug}`,
        lastmod: 'item.updatedAt',
        priority: 0.7,
        changefreq: "daily",
      }));
    
      console.log({ fields });
    
      return getServerSideSitemapIndex(ctx, services)
    }
    
    // Default export to prevent next.js errors
    export default function SitemapIndex() {}

package.json:

      "scripts": {
        "dev": "next dev",
        "build": "next build",
        "postbuild": "next-sitemap",
            ...

but when I want to build I got this error:

    next-sitemap
    internal/process/esm_loader.js:74
        internalBinding('errors').triggerUncaughtException(
                                  ^
    
    Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'
        at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:751:11)
        at Loader.resolve (internal/modules/esm/loader.js:85:40)
        at Loader.getModuleJob (internal/modules/esm/loader.js:229:28)
        at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:51:40)
        at link (internal/modules/esm/module_job.js:50:36) {
      code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
    }
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! dental@0.1.0 postbuild: `next-sitemap`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the dental@0.1.0 postbuild script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

  [1]: https://www.npmjs.com/package/next-sitemap/v/1.6.228

**Comment by iamvishnusankar** [comment]
@S-Masoud-Emamian Minimum supported node version is `"node": ">=14.18"`. Feel free to re-open if the issue persists after upgrading your node version.
