### ISSUE TITLE
Allow disable static sitemap

### ISSUE THREAD

**Issue by rodrigo-arias** [iamvishnusankar/next-sitemap#532]
**Is your feature request related to a problem? Please describe.**
Add an option to disable the standard sitemap generated from static pages.

**Describe the solution you'd like**
It would be nice to have a flag to disable the static sitemap for when we want to use only the server sitemap through `additionalSitemaps`.

**Describe alternatives you've considered**
At the moment I am returning null to all paths in the `transform` function, but this is just a hack.

**Additional context**
I have a 5k-page site where I use ISR to generate a reduced number of pages to limit build time. I don't need the static sitemap since those pages are already included in the server sitemap and there are none (in my case) generated only in the front-end.

**Comment by iamvishnusankar** [comment]
@rodrigo-arias Have you tried `exclude: ["*"]` option?.

**Comment by rodrigo-arias** [comment]
@iamvishnusankar thanks for your reply, this does the job.

**Comment by tr1s** [comment]
> @rodrigo-arias Have you tried `exclude: ["*"]` option?.

This worked for me thanks!

This would be helpful to add in the docs
