### ISSUE TITLE
google search console rejecting sitemap

### ISSUE THREAD

**Issue by cdking007** [iamvishnusankar/next-sitemap#535]
**Describe the bug**
when i submit the sitemap generated by the next-sitemap it rejecting it saying couldn't fetch

**version**
^3.1.32

**Expected behavior**
should accept the sitemap

**Screenshots**
![image](https://user-images.githubusercontent.com/39514257/203921073-12897877-234f-4128-816c-e053934f6a2f.png)

**Comment by w33ts** [comment]
What was the fix here? I'm running into this same exact issue.

**Comment by cdking007** [comment]
@w33ts fixed?
cause at that time it was issue of i guess from my ccTLD.

**Comment by w33ts** [comment]
> 

Ohhhh interesting. We have a .info domain, so I wonder if that's why.

**Comment by cdking007** [comment]
are you using cloudflare or something?

**Comment by w33ts** [comment]
Yeah, I am. If I input the sitemap-0.xml, it works just fine but the sitemap.xml doesn't work. I haven't dug too much into it, though.

**Comment by cdking007** [comment]
possibly have to look into issue, possibly that might be misconfigured the sitemap?

**Comment by w33ts** [comment]
It very well could be, I'll re-read the docs and see if maybe I missed something. Thank you!

**Comment by cdking007** [comment]
@w33ts share me the url if possible?

**Comment by w33ts** [comment]
Sure, it's https://cyber.info and the sitemap is of course https://cyber.info/sitemap.xml

**Comment by w33ts** [comment]
Do you mind sharing your sitemap index? I'm curious to see if it's different in any way.

**Comment by cdking007** [comment]
@w33ts yes sure here it is: https://prinpod.com/sitemap.xml

**Comment by simonpeters** [comment]
I'm running into the same issue: [https://www.gewoon.club/sitemap.xml](https://www.gewoon.club/sitemap.xml)

**Comment by Zain-ul-din** [comment]
This question may help you to understand **how to submit the sitemap in Google Search Console?**
https://support.google.com/webmasters/thread/6353519/your-sitemap-appears-to-be-an-html-page-please-use-a-supported-sitemap-format-instead?hl=en

## Works for me

![image](https://user-images.githubusercontent.com/78583049/232583887-e3bcb38e-5629-4bea-b0e0-76c7124915e7.png)
