### ISSUE TITLE
Do not run `next-sitemap` when building locally

### ISSUE THREAD

**Issue by brenopolanski** [iamvishnusankar/next-sitemap#540]
Is there a way to not run `next-sitemap` when building locally? Sometimes it's really annoying to have `sitemap.xml` and `robots.txt` updated all the time.

**My configs:**

- `package.json`

```
"build": "next build --debug",
"postbuild": "next-sitemap",
```

- `next-sitemap.config.js`

```js
/** @type {import('next-sitemap').IConfig} */
module.exports = {
  changefreq: 'monthly',
  generateIndexSitemap: false,
  generateRobotsTxt: true,
  siteUrl: process.env.SITE_URL,
}
```

**Comment by brenopolanski** [comment]
Hey @iamvishnusankar, can you help me?

**Comment by isaachinman** [comment]
@brenopolanski Just gitignore the files.

**Comment by iamvishnusankar** [comment]
@brenopolanski Sorry I was away! As @isaachinman mentioned, you may add the generated files to gitignore.

**Comment by brenopolanski** [comment]
> @brenopolanski Just gitignore the files.

Owww yeah @isaachinman, I don't know why I didn't think of that before :P
