### ISSUE TITLE
Image sitemap

### ISSUE THREAD

**Issue by konsumer** [iamvishnusankar/next-sitemap#545]
**Is your feature request related to a problem? Please describe.**

I'd like to create [image sitemaps](https://developers.google.com/search/docs/crawling-indexing/sitemaps/image-sitemaps) so we get more hits for google-images.

**Describe the solution you'd like**

An option to generate this, based on the image-tags in the HTML for each page.

**Describe alternatives you've considered**

A separate script to do this, and augment the generated sitemap with `<image:image>` tags.

**Additional context**

I am happy to PR for the feature, if there is interest.

**Comment by mikeldoka1** [comment]
This is definitely a missing feature

**Comment by nonoumasy** [comment]
I'm also looking for a solution since my site is image heavy.

**Comment by iamvishnusankar** [comment]
Fixed: #437
