### ISSUE TITLE
Sitemap includes page 404 and 500

### ISSUE THREAD

**Issue by petrbrzek** [iamvishnusankar/next-sitemap#548]
**Describe the bug**
The sitemap of my site contains 404 and 500. Should it be ignored? Here is the [sitemap](https://www.mindhaste.com/sitemap-0.xml). The config is pretty basic.

```
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://www.mindhaste.com/',
  generateRobotsTxt: true,
}
```

**Expected behavior**
I would expect that these pages will not be in the sitemap. Various site audits report this as a bug. For example GSC or Ubersuggest.

**Screenshots**
<img width="809" alt="Screen Shot 2022-12-21 at 11 39 13 PM" src="https://user-images.githubusercontent.com/879564/209016219-5f1beced-d29e-44fb-b303-32133decb2ba.png">

**Comment by pmpwith2i** [comment]
Hi @petrbrzek 😄 
Which version of the package are you using?
I checked and next-sitemap skips the next.js internal errors page, as described in this snippet

```
/**
 * Checks whether a url is next.js specific or not
 * @param path path check
 */
export const isNextInternalUrl = (path: string): boolean => {
  return new RegExp(/[^/]*^.[_]|^\/(404|500)$|\/_middleware$|(?:\[)/g).test(
    path
  )
}
```

**Comment by OdifYltsaeb** [comment]
I have the same issue - But I have a custom 404 page: /pages/404.js

But using this example: https://github.com/iamvishnusankar/next-sitemap#custom-transformation-function I just removed the custom 404 page from the sitemap.
