### ISSUE TITLE
Support for Custom Build Directories

### ISSUE THREAD

**Issue by Marxon13** [iamvishnusankar/next-sitemap#551]
**Is your feature request related to a problem? Please describe.**
I would like to build my next site to a custom directory. When specifying a custom directory in the Next config, Next Sitemap still looks for related files in the `.next` directory, and throws an error.

```
$ next-sitemap
Loaded env from /home/user/actions-runner/_work/Site/Site/.env
✨ [next-sitemap] Loading next-sitemap config: file:///home/user/actions-runner/_work/Site/Site/next-sitemap.config.js
❌ [next-sitemap] Unable to find export-maker.
Make sure to build the project using `next build` command

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: ENOENT: no such file or directory, stat '/home/user/actions-runner/_work/Site/Site/.next/export-marker.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/user/actions-runner/_work/Site/Site/.next/export-marker.json'
}

Node.js v18.12.1
error Command failed with exit code 1.
```

**Describe the solution you'd like**
I would like to build my NextJS site to a custom directory, then copy the new site into the standard `.next` directory to minimize downtime. I can customize the build directory in the `next.config.js` file. 

Example config:
```
{
    distDir: process.env.BUILD_DIR || '.next',
}
```

Example build script:
```
BUILD_DIR=".tmp-next" yarn build
rm -rf .next; mv .tmp-next .next
BUILD_DIR=".next" pm2 restart NextJSApp
```

Ideally next-sitemap would pick up on the `distDir` from the Next config automatically. Adding a matching `distDir` property to the sitemap config would also work, but if it doesn't match the Next config, the same error would probably occur.

**Comment by iamvishnusankar** [comment]
@Marxon13 Please check `sourceDir` param. 

See: https://github.com/iamvishnusankar/next-sitemap#configuration-options
