### ISSUE TITLE
generateIndexSitemap: false not working

### ISSUE THREAD

**Issue by KohanTorabiStage** [iamvishnusankar/next-sitemap#552]
This is my project config, although I put `generateIndexSitemap: false` in my config, the index sitemap is generated!

![image](https://user-images.githubusercontent.com/97602392/210175031-d7257e27-ac24-4684-9e15-465fe3a86a20.png)

**Comment by iamvishnusankar** [comment]
@KohanTorabiStage Feel free to re-open this with a reproduction

**Comment by chipcop106** [comment]
I confirmed this problem; It still generates a sitemap on the build process whether  the generateIndexSitemap flag is false

**Comment by chipcop106** [comment]
> This is my project config. Although I put `generateIndexSitemap: false` in my config, the index sitemap is generated!
> 
> ![image](https://user-images.githubusercontent.com/97602392/210175031-d7257e27-ac24-4684-9e15-465fe3a86a20.png)

I set the exclude flag to ["*"], and it probably works.
