### ISSUE TITLE
How to create only one sitemap in nextjs

### ISSUE THREAD

**Issue by S-Masoud-Emamian** [iamvishnusankar/next-sitemap#557]
I'm using `next-sitemap` package for creating sitemap.
I have dynamic and static pages.

this is my `next-sitemap.config.js` file:

    module.exports = {
        siteUrl: 'https://example.com',
        generateRobotsTxt: false,
        exclude: ['/server-sitemap-index.xml'], // <= exclude here
        robotsTxtOptions: {
          additionalSitemaps: [
            'https://example.com/server-sitemap-index.xml', // <==== Add here
          ],
        },
      }

but this config generate two sitemaps.

`robots.txt`:

    Sitemap: https://example.com/sitemap.xml

content of above link:

    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <script/>
    <sitemap>
    <loc>https://example.com/sitemap-0.xml</loc>
    </sitemap>
    <sitemap>
    <loc>https://example.com/server-sitemap-index.xml</loc>
    </sitemap>
    </sitemapindex>

`sitemap-0.xml` is static links and `server-sitemap-index.xml` is dynamic links.

but I want to have only one site map for example:

https://example.com/sitemap.xml

    static links
    ....
    dynamic links

**Comment by iamvishnusankar** [comment]
@S-Masoud-Emamian  Set `generateIndexSitemap:false` in `next-sitemap.config.js`

**Comment by S-Masoud-Emamian** [comment]
> @S-Masoud-Emamian Set `generateIndexSitemap:false` in `next-sitemap.config.js`

but it doesn't generated  SSR urls.
I want to have static and dynamic routes inside a file.

**Comment by S-Masoud-Emamian** [comment]
any solution? @iamvishnusankar
