### ISSUE TITLE
any plans regarding dynamic pages?

### ISSUE THREAD

**Issue by einSelbst** [iamvishnusankar/next-sitemap#57]
I was so happy when I found this....
But then I realized, it's only for static pages...

Is support for dynamic pages on the roadmap?

Have you seen how he's doing it https://blog.yorunohikage.fr/2020/07/20/statically-generated-sitemap-in-nextjs-9-3/

**Comment by iamvishnusankar** [comment]
Hi, I'm actually focused on adding full support for i18n routes at this moment. And for dynamic pages, this package already supports pre-rendered and ISG pages. Next update will include two major features:

1. Full i18n routes support.
2. Functionality to fetch data from server and generate sitemaps based on it.

**Comment by einSelbst** [comment]
That sounds great! Support for i18n is also something we would benefit from, although we haven't yet switched to the nextjs10 method (and I'm not sure we will). I really like the way you set it all up, the blog entry, the documentation, the example - a big compliment.

**Comment by qb-rivkyb** [comment]
> Functionality to fetch data from server and generate sitemaps based on it.
Hey! Wondering when this will be implemented?
