### ISSUE TITLE
Splitting sitemap based on locale

### ISSUE THREAD

**Issue by BramDecuypere** [iamvishnusankar/next-sitemap#58]
I was wondering how we would go about splitting the sitemap with locales?

so instead of just a `sitemap-index.xml`:
- sitemap-index.xml (with references to the following languages indexes)
- sitemap-nl-index.xml
- sitemap-fr-index.xml
- ....

**Comment by iamvishnusankar** [comment]
Hi @BramDecuypere , Working on locale based sitemaps are bit tricky. It involves few challenges to tackle before implementing. Some of them are:

- Domain based and sub-dir based locale routes.
- We can't expect the translation for every pages, so creating sitemaps for localised contents from `default` sitemap becomes challenging.
- Nextjs doesn't have any pre-render manifest for i18n routes.
..etc

But a generic solution can be implemented to address all these issue. I will be posting a detailed RFC of next major release.

**Comment by erwanriou** [comment]
First congratulation on your solution to generate sitemap, it's work very well. I am myself in a similar situation. I run a kubernetes nginx that will deploy few next js app in different domains. Depending of these domains i have setup a default language and i generate a specific default url for each pages. (/sponsor in english would be /parainer in french for exemple..) 

Right now the sitemap generator is only interpreting the url including the language path /us /fr /es but does not take in account the default paths.
So yes to be able to generate a sitemap depending of the default language of the app would be absolutely amazing!

In the meantime i will try work in a custom solution.

**Comment by iamvishnusankar** [comment]
@erwanriou Thanks for the feedback. Turns out, doing i18n route support is bit more complex than I originally imagined. It's primarily because of the support for subdomain and sub-directory based routes. It would be great if you could share some input/suggestions based on your use case to deal with this problem.

**Comment by erwanriou** [comment]
@iamvishnusankar Ok yes i suspected it wouldn't be an easy one, yes. 

Well one quick solution would be to implement the possibility to do multiple sitemap and control the url generated for each, so after with the transform function you made up we could manipulate the content of the pages generated for each and have a sitemap for each language potentially.

**Comment by ProjectINT** [comment]
Hi. In my case will be enough add ability to merge sitemap with my additional sitemap. All dynamic routes well mapped with this plugin, but static routes localized pages missed in sitemap. I have not so match this type routes near 10, i can write additional sitemap for each by hands, but how to merge it with main sitemap?

**Comment by mariesta** [comment]
> Hi. In my case will be enough add ability to merge sitemap with my additional sitemap. All dynamic routes well mapped with this plugin, but static routes localized pages missed in sitemap. I have not so match this type routes near 10, i can write additional sitemap for each by hands, but how to merge it with main sitemap?

Having the same issue. My dynamic pages are generating separate urls for each locales thanks to [this](https://nextjs.org/docs/advanced-features/i18n-routing#dynamic-getstaticprops-pages), but my static pages don't. Is there a plan to support internationalization with next-sitemap?

**Comment by thiras** [comment]
+1 for support

**Comment by paales** [comment]
@iamvishnusankar We're trying to use nextjs with multiple domains as mentioned here: https://nextjs.org/docs/advanced-features/i18n-routing#getting-started

I'm not totally sure if this issue would solve it, but would be nice if next-sitemap could parse the domains section and everything would 'just work'. 

Maybe we can already get something up and running, but I can't figure it out. Any ideas?
