### ISSUE TITLE
The outDir option does not adjust sitemap.xml or robots.txt.

### ISSUE THREAD

**Issue by masa5714** [iamvishnusankar/next-sitemap#581]
**Describe the bug**

version: "next-sitemap": "^3.1.52"

base URL: https://example.jp/
sitemap: https://example.jp/vkk6fj7dw6fr/sitemap.xml
sitemap-1: https://example.jp/vkk6fj7dw6fr/sitemap-1.xml

```js
/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://example.jp/',
  generateRobotsTxt: true,
  outDir: './public/vkk6fj7dw6fr',
  additionalPaths: async () => { // Additional my paths.
    return await generateSamplePaths()
  }
}
```

A sitemap is generated in `/public/vkk6fj7dw6fr`.

- robots.txt
- sitemap.xml
- sitemap-0,xml
- sitemap-1.xml

The description of the generated file was as follows:

◆1-1. robots.txt
```
# *
User-agent: *
Allow: /

# Host
Host: https://example.jp

# Sitemaps
Sitemap: https://example.jp/sitemap.xml <- ★ Problem this line.
```

◆1-2. sitemap.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://example.jp/sitemap-0.xml</loc></sitemap>  <- ★ Problem this line.
<sitemap><loc>https://example.jp/sitemap-1.xml</loc></sitemap> <- ★ Problem this line.
</sitemapindex>
```

**Expected behavior**

◆2-1. robots.txt

```
# *
User-agent: *
Allow: /

# Host
Host: https://example.jp

# Sitemaps
Sitemap: https://example.jp/vkk6fj7dw6fr/sitemap.xml
```

◆2-2. sitemap.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://example.jp/vkk6fj7dw6fr/sitemap-0.xml</loc></sitemap>
<sitemap><loc>https://example.jp/vkk6fj7dw6fr/sitemap-1.xml</loc></sitemap>
</sitemapindex>
```

**Additional context**
I do not know if this is a spec or a bug.
Sorry if this is a problem with my usage.
I solved this by running `next-sitemap && node sitemap-replace.js` in package.json postbuild.

◆ sitemap-replace.js
```js
const replaceSitemap = async (fileName) => {
  const fs = require('fs/promises')
  const appRoot = require('app-root-path')
  const subDirectory = 'vkk6fj7dw6fr'
  const filePath = `${appRoot}/public/${subDirectory}/${fileName}`

  const original = await fs.readFile(filePath, 'utf8')
  const replacedData = original.replace(
    /https\:\/\/example\.jp\/sitemap/g,
    `https://example.jp/${subDirectory}/sitemap`
  )

  await fs.writeFile(filePath, replacedData, 'utf8')
}

;(async () => {
  await replaceSitemap('robots.txt')
  await replaceSitemap('sitemap.xml')
})()
```

**Comment by iamvishnusankar** [comment]
@masa5714 Can you please provide a reproduction?

**Comment by masa5714** [comment]
Hi @iamvishnusankar .
I have created a repository for this issues.  
https://github.com/masa5714/next-sitemap-outdir-sample

next-sitemap is very nice.
I have been helped by next-sitemap and @iamvishnusankar !!

**Comment by bonesoul** [comment]
same issue here. 

`  outDir: `public/${process.env.NEXT_PUBLIC_SITE_LOCALE}`,`

generated sitemap.xml doesn't obey the outdir:

`<sitemap><loc>https://www.vizesizgezi.com/sitemap-0.xml</loc></sitemap>`

**Comment by lindseybradford** [comment]
Just noting I'm also encountering this. Thanks!

**Comment by ryo-ebata** [comment]
Please Reopen this Issue.
We are still facing this problem: `robots.txt` and `sitemap.xml` are only considered to be placed directly under the public directory, ignoring the outDir.
