### ISSUE TITLE
Googlebot reads getServerSideSitemapIndexLegacy to be an HTML page error.

### ISSUE THREAD

**Issue by agamm** [iamvishnusankar/next-sitemap#595]
**Describe the bug**
I get the following error from Google Search Console:
![image](https://user-images.githubusercontent.com/1269911/223431035-ae0ac62a-6087-4774-b6f6-a78dcfd3a78b.png)

**To Reproduce**
```
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // Method to source urls from cms
  const blogs = // ... fetching from DB.
  const urls = [];
  for (const blog of blogs) {
    urls.push(`https://mysite.com/blog/${blog.slug}`);
  }

  return getServerSideSitemapIndexLegacy(ctx, urls);
};

// Default export to prevent next.js errors
// eslint-disable-next-line @typescript-eslint/no-empty-function
export default function SitemapIndex() {}
```

**Expected behavior**
The sitemap should be valid like:
```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url><loc>https://www.mysite.com/blog/slug-here</loc><lastmod>2023-02-06T16:36:70.999Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
...
```

Current sitemap looks like so:
```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>https://mysite.com/blog/slug-here</loc></sitemap>
```
(I think that google doesn't understand the `sitemap` tag correctly, and we should use a `url` tag.

**Screenshots**
Already done.

**Additional context**
Using next 13. but with pages folder.

**Comment by iamvishnusankar** [comment]
@agamm Can you provide a public repo reproduction?

**Comment by agamm** [comment]
> @agamm Can you provide a public repo reproduction?

No @iamvishnusankar, I wish. I'm working for a client that can't be shared here. But from the code I can see the generation being that:
https://github.com/iamvishnusankar/next-sitemap/blob/cf5fdec237128e72241db0135376e7f8b490c3bc/packages/next-sitemap/src/ssr/sitemap-index.ts#L11

Is generating a sitemap [**index**](https://github.com/iamvishnusankar/next-sitemap/blob/cf5fdec237128e72241db0135376e7f8b490c3bc/packages/next-sitemap/src/builders/sitemap-builder.ts#L22) and not a normal sitemap like: https://github.com/iamvishnusankar/next-sitemap/blob/cf5fdec237128e72241db0135376e7f8b490c3bc/packages/next-sitemap/src/builders/sitemap-builder.ts#L56

**Comment by iamvishnusankar** [comment]
@agamm I'm sorry, I can't debug without a reproduction. So closing this issue for now.

Here're some useful link to help you resolve this:
- https://github.com/iamvishnusankar/next-sitemap#index-sitemaps-optional
- https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps

**Comment by agamm** [comment]
@iamvishnusankar Yes, that really helped, I needed the normal sitemap not the index. Thanks!
