### ISSUE TITLE
Postbuild opening config file instead of running next-sitemap

### ISSUE THREAD

**Issue by MoltenCoffee** [iamvishnusankar/next-sitemap#61]
Hi!

I've installed `next-sitemap` (1.2.26) as a dev dependency, and added it to package.json: `"postbuild": "next-sitemap"`.=
However, when I build, the postbuild just opens the config file (`next-sitemap.js`) instead of executing `next-sitemap`.

Any ideas how to solve this?

Regards, TJ

**Comment by iamvishnusankar** [comment]
Hi @MoltenCoffee , That's a strange issue. Can you please share a reproduction repo to investigate?

**Comment by MoltenCoffee** [comment]
Sure: https://github.com/MoltenCoffee/next-sitemap-bug

Could it be that I'm using NPM instead of Yarn? I'm not able to use the letter within my organization I'm afraid.

**Comment by MoltenCoffee** [comment]
The initial commits were a bit of a mess, the repo should now be in its 'proper' reproduction state.

**Comment by iamvishnusankar** [comment]
Your reproduction repo doesn't have `next-sitemap` as its dev/dependency. I tried building after installing the package and all works fine on my machine. (Both using nom and run).

May be check your node installation restricts any post/pre scripts. If so you can update your build script as `next build && next-sitemap`

**Comment by MoltenCoffee** [comment]
I had forgotten to push that commit, but it does have the proper dependencies now. It does run the postscript, as otherwise is would not try to open the file, it also prints it does in the terminal. Changing the build script to include it does not yield any results either.

However, this was all run on Windows 10 with node 14.3.0, npm 6.14.5. I just tried running it on Arch linux, node 15.1.0, npm 6.14.8 which does work, so it seems related to windows.

I tried changing the script to:

```
{
    "postbuild": "bash next-sitemap"
}
```

which did execute next-sitemap, but failed on line 12, because `node` command was not recognized, I guess it uses bash in my Debian WSL (windows subsytem for linux). Installing node here would probably solve the issue, but I don't think it's a proper solution, node and npm are quite platform-neutral (and I think should be). 

I'm curious if others are able to execute this without problems on windows machines

**Comment by iamvishnusankar** [comment]
I ran a matrix cross platform matrix test and all builds succeeded. 

Here's the test: https://github.com/iamvishnusankar/next-sitemap/actions/runs/355823291

Unfortunately, I don't have a windows machine to test it. Keeping this issue open for now.

**Comment by MoltenCoffee** [comment]
I'll try to look into this some more, I'll let you know if I find anything!

**Comment by KevinBacas** [comment]
Hello :)
Just to let you know, I'm having the same issue on windows.
It opens `next-sitemap.js` and does not generate robots.txt + sitemap.xml 

I tried a few thing like `npx next-sitemap` but I got the same result.

**Comment by MoltenCoffee** [comment]
The immediate cause seems to be the configuration file `next-sitemap.js` having the same name as the package itself. (With Node ignoring the .js part of course, in contrast with regular Windows behaviour). Node on windows seems to prioritize local files above known values in PATH.

This can be demonstrated by creating a `next.js` file inside the project directory, and then running the build script (`npm run build`, `next build`). It will act the same, trying to open this file instead of running the Next scripts.

**A workaround:**
When I edit `/src/path/index.ts` to include:

```js
export const KNOWN_PATHS = {
  CONFIG_FILE: getPath('next-sitemap.config.js'), // See the underscore in the filename
}
```

instead of `next-sitemap.js`, and change the name of the config file accordingly, everything works as intended.

**A solution?**
Of course this package _could_ change its config file, to something like next-sitemap.config.js (which seems to a common format, as it is what Babel, PostCSS, Styleguidist, Next and many others offer (among other options)) bu will present a breaking change. Adding it as a secondary config filepath for Windows-users could be an option as well.

I do find it peculiar I don't seem to be able to find more examples like this online, although I get that developing on Windows might not be the greatest option out there.

**Comment by MoltenCoffee** [comment]
Addendum: This might actually be related to NPM 7 or Node 15, which I recently updated. `rimraf` Stopped working in another project as well.

@KevinBacas @pierretusseau which versions do you use?

**Comment by KevinBacas** [comment]
I was using Node 15.1.0, I tried downgrading to the LTS version (14.15.0) but I'm having the same problem

**Comment by iamvishnusankar** [comment]
@MoltenCoffee That's a great find. It'll be a major breaking change to rename the config file from `next-sitemap.js` to `next-sitemap.config.js`. Does passing `--config` flag work on windows?

If so it'll will be a minor fix to implement the feature.

**Comment by MoltenCoffee** [comment]
I'm not entirely sure what I should pass the `--config` flag to?

_Meanwhile_, however, completely deleting Node, npm, npm caches etc and reinstalling (following [these steps from the readme of `npm-windows-upgrade`](https://github.com/felixrieseberg/npm-windows-upgrade#fix-an-attempted-upgrade)) did solve my problem. So it must have been something within Node or npm during an upgrade, I guess. I'm curious if @KevinBacas would be willing and able to give this a try, it's not worth a major breaking change if it's just an edge case caused by a bodged upgrade.

**Comment by iamvishnusankar** [comment]
It's to provide a custom config file instead of `next-sitemap.js`. So the build command will be `next-sitemap --config next-sitemap.config.js`.

If deleting and reinstalling node_modules fixes the issue, then there's no need for that. Let's wait for @KevinBacas replay.

**Comment by KevinBacas** [comment]
Still not working for me...
I tried removing and reinstalling NodeJS, clean npm and npm-cache, I tried installing deps with npm and yarn. Same behavior for me.

I'll try again tomorrow with a different PC

A `--config` would be a nice solution tho :)

**Comment by MoltenCoffee** [comment]
Ah, I completely misunderstood the comment about the `--config` option, but that sure seems great! I believe that's a nice feature in general, no matter the platform!

It still bugs me we don't know the real problem here, as @KevinBacas still experiences it. But now it works on my end, I really don't see how `next-sitemap` could be the problem (which is good for next-sitemap, but not really for KevinBacas)..

**Comment by iamvishnusankar** [comment]
I've added supported for custom config file. I was planning this with the `next` v10 release. Glad that this issue came up and gave a reason to push it fast. 

Even though this cause this issue still unknown, having a custom config file may slowly help to migrate `next-sitemap.js` to use `next-config.js`.  It will be helpful managing the i18n routes and domain info in a single file.

**Comment by iamvishnusankar** [comment]
keeping it open for further investigation.

**Comment by pjsachdev** [comment]
Adding cross-env to the postbuild script seemed to fix this for me.

**Comment by DopamineDriven** [comment]
@pjsachdev is correct, adding cross-env is required

when using anything with `NODE_OPTIONS` on a windows OS you must have `cross-env` before the NODE_OPTIONS keyword (for example)

```json
    "postbuild": "cross-env next-sitemap --config next-sitemap.js",
    "prod:build": "yarn codegen && yarn build && yarn postbuild",
``` 

- Other examples 
```json
    "codegen": "graphql-codegen --config codegen.yml -r dotenv/config",
    "dev:debug": "cross-env NODE_OPTIONS='--inspect' next -p 3060",
    "vercel:debug": "cross-env NODE_OPTIONS='--inspect' vercel dev --listen 3060",
```

just run
```git
yarn add -D cross-env
```

**Comment by reginpv** [comment]
Any update on this one guys?

**Comment by reginpv** [comment]
Ok so, I followed the thread.

What worked for me was:

1. Install `cross-env` --> (`npm i --save-dev crosss-env`)
2. Update my `package.json` postbuild script to: "cross-env next-sitemap --config next-sitemap.js"
3. run npm run build, and worked for me

**Comment by reginpv** [comment]
> Ok so, I followed the thread.
> 
> What worked for me was:
> 
> 1. Install `cross-env` --> (`npm i --save-dev crosss-env`)
> 2. Update my `package.json` postbuild script to: "cross-env next-sitemap --config next-sitemap.js"
> 3. run npm run build, and worked for me

This is for Window only

**Comment by shl1997** [comment]
> Hello :)
> Just to let you know, I'm having the same issue on windows.
> It opens `next-sitemap.js` and does not generate robots.txt + sitemap.xml
> 
> I tried a few thing like `npx next-sitemap` but I got the same result.
use yarn next-sitemap

**Comment by vasumittalhcl** [comment]
Unable to access GCP secrets/env variables from GCP into next-sitemap.config file. It is only loading from .env which my current project is avoiding. Any solution or way out?

however in next.config those same secrets/env variables are accessible without any effort.

**Comment by VGuanCentra** [comment]
Below worked for me on win10 and win11 VSCode Nextjs:
1. install
   > yarn add next-sitemap -D
2. install [cross-env](https://www.npmjs.com/package/cross-env)
  >npm i cross-env
3. Create config file
   create "next-sitemap.js"
   or create custom file "gem-sitemap.js"
4. Building sitemaps add "package.json

  "scripts": {
    "__dev": "next dev",
    "dev": "cross-env NODE_OPTIONS='--inspect' next",
    "build": "next build",
    "__Popup_1_postbuild": "next-sitemap",
    "__Popup_2_postbuild": "next-sitemap --config next-sitemap.js",
    "postbuild": "cross-env next-sitemap --config gem-sitemap.js",
    "__worked_1_postbuild": "cross-env next-sitemap --config next-sitemap.js",
    "__worked_2_postbuild": "cross-env NODE_OPTIONS='--inspect' next-sitemap --config next-sitemap.js",

    "start": "next start"
  },
5. run
   > npm run postbuild
6. observer public folder below 2 files added!
   -robots.txt
   -sitemap.xml
Happy Coding

**Comment by rawalprashant** [comment]
> Hello, Win 10 user over here. I was having the same issue where command `postbuild: next-sitemap` wouldn't work.
> 
> Solution for me was renaming _next-sitemap_ file and adding config flag, like this: `postbuild: next-sitemap --config next-sitemap.config.js`
> 
> **Didn't need to install `cross-env`**

Thanks a lot, you save my day...

**Comment by DeepCoreB4** [comment]
Hi...

Nice to start the day with a successful solution for my problem i had a long time ago

Thanks, this was the one that worked for me.

**Comment by thomas159** [comment]
I have   ` "postbuild": "next-sitemap --config next-sitemap.config.js",` but this doesn't seem to generate the sitemap on windows 11

**Comment by NarayanasamyP** [comment]
Hello Team,

I have tried all the suggestions but nothing is worked for me. Any suggestions?

Here are my development environment details,

**OS: Windows 10

Nodejs Version: v14.17.0

npm version: 6.14.13**



Tried the following suggestions:

1. cross-env --- **not working**
2.  "postbuild": "next-sitemap --config next-sitemap.config.js" -- **not working**

When I try the **second** suggestion I'm getting the below errors,

![image](https://user-images.githubusercontent.com/34939696/164914997-8d926f7e-4ce8-4005-97b2-fb3b189a2638.png)

I have tried to delete the node_modules folder and installed all the packages using npm cmd. but still, it's throws the above error.


Note: I'm using nextjs app in **JS** syntax, not in **JSX** or **TSX**. Anyone can confirm is that causes the issue?

**Comment by NarayanasamyP** [comment]
> I have ` "postbuild": "next-sitemap --config next-sitemap.config.js",` but this doesn't seem to generate the sitemap on windows 11


I have faced the same issue when I'm using node version 14.17.0

Then, I upgraded the nodejs version to 16.13.2 then the issue is resolved. Make sure that you have renamed the next-sitemap.js file name too.

**Comment by AcadecraftDeveloper** [comment]
Is it necessary to use the typescript in server-sitemap-index.xml.index.ts.??
in dynamic case sitemap only generating static fils only

**Comment by Eddie2111** [comment]
Did this from my windows 10, 22H2.

package.json
`  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "postbuild": "cross-env next-sitemap --config next-sitemap.js",
    "start": "next start",
    "lint": "next lint"
  },`
  
  next-sitemap.config.js  [yes, this is the file named as next-sitemap.js in the documentation as well as in the upper threads]
  `module.exports = {
    siteUrl: 'https://www.cartgo.com',
    generateRobotsTxt: true,
    exclude: ['/admin'],
    // Add any other configuration options you want to use
  };`
  
 The command executed in the terminal
 `npx cross-env next-sitemap --config next-sitemap.config.js`
 
 Now, the descriptive part, why facing the problem,
 
 - Windows prioritizes local files above known values in PATH in case of script execution for security. This is the reason `cross-env` is required. 
 
 - The `next-sitemap.js` is just not any script but a configuration file which has to be prioritized. Name the file `next-sitemap.config.js` to get it going.
