### ISSUE TITLE
Sitemap is generated with - undefined/sitemap-0.xml.

### ISSUE THREAD

**Issue by the-iter8** [iamvishnusankar/next-sitemap#612]
**Describe the bug**
The sitemap files that are generated have `undefined` as their siteUrl. It's not even capturing the priority etc. Seems that the config file isn't loading at all.

**To Reproduce**
Here is a direct link to sandbox reproduction - https://codesandbox.io/p/sandbox/stupefied-joliot-gspwwt?file=%2Fpackage.json

**Expected behavior**
Expected to get example.com as the siteUrl

**Screenshots**
Here are screenshot of the package.json and config file and the output- 
![Package.json](https://user-images.githubusercontent.com/78586739/230706256-c6611ba5-2d86-495f-bff0-f2dfc16315cf.png)

![Config file in root dir](https://user-images.githubusercontent.com/78586739/230706301-1efa8a31-3b57-4e4c-b021-d856a739b2e1.png)

![Output](https://user-images.githubusercontent.com/78586739/230706325-7cfcd585-5139-4304-848e-21ebc082b3f2.png)

**Comment by rohanreddy888** [comment]
Is this fixed? Did you find a way around this?

**Comment by royaltyisdead** [comment]
It seems, as per their docs (Index sitemaps (Optional)), since v2 it will contain sitemaps with other generated sitemaps. You can disable this feature by using  `generateIndexSitemap: false`.

**Comment by mwawrusch** [comment]
Just started with a fresh install with this config:
```
// env is empty

let hasSitemap = !!process.env.SITEMAP_SITE_URL;

module.exports = {
  siteUrl: process.env.SITEMAP_SITE_URL ,
  generateIndexSitemap: hasSitemap,
  generateRobotsTxt: hasSitemap,
  changefreq: 'daily',
  // ...other options
}
```
and it creates the following index sitemap (despite the env being empty):

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
<url><loc>undefined/robots.txt</loc><lastmod>2023-05-28T22:47:26.370Z</lastmod><changefreq>daily</changefreq><priority>0.7</priority></url>
</urlset>
```

I'd expect no sitemap file to be produced
