### ISSUE TITLE
Url in "About" section in githut repo doesn't exist

### ISSUE THREAD

**Issue by dragGH102** [iamvishnusankar/next-sitemap#620]
This repo: https://github.com/iamvishnusankar/next-sitemap
Where: on the right, "about section" -> URL: https://www.iamvishnusankar.com/blogs/how-to-generate-sitemap-for-nextjs-projects/
Error: DNS_PROBE_FINISHED_NXDOMAIN

DNS used: https://developers.google.com/speed/public-dns

**Comment by iamvishnusankar** [comment]
@dragGH102 Sorry, fixed!
