### ISSUE TITLE
How to create no index for .nextjs pages

### ISSUE THREAD

**Issue by FriendlyUser** [iamvishnusankar/next-sitemap#630]
**Describe the bug**
I looked at the documentation for the next-sitemap, I would like to add a noindex option to certain pages, ./pokemon/*, its not clear to me thats its possible, for the IRobot type I only see allow / disallow in robots.txt. This is for preventing pages from being indexed on certain environments like dev.

**To Reproduce**

1. Attempt to use noindex on the policies under next-sitemap

**Expected behavior**
The specified pages are no indexed

**Screenshots**

**Additional context**
Going to try using exclude to see if it helps.

**Comment by mbifulco** [comment]
Hi @FriendlyUser  - you should be able to do this with the excludes array option on your sitemap config.

I think you may need to use `/pokemon*` instead of `/pokemon/*` to exclude all your subpages, so:

```js
/** @type {import('next-sitemap').IConfig} */
module.exports = {
  generateRobotsTxt: true,
  exclude: [
    "/pokemon*",
  ],
};
```
