### ISSUE TITLE
Support Statically Exported Websites without `next export`

### ISSUE THREAD

**Issue by ovflowd** [iamvishnusankar/next-sitemap#637]
Next.js is deprecating the `next export` command in favour of `next build` with `output: 'export'` (https://nextjs.org/docs/pages/building-your-application/deploying/static-exports). This means that a `postbuild` script, such as `next-sitemap` will not work anymore.

With the new way of exporting, a Next.js Static Application will move the exported files directly to the output directory after the build. No `.next` folder is created + files are transferred to the final guide beforehand.

There should be a way that either `next-sitemap` can be invoked either as a prebuild step or within Next.js itself during the build process.

Using the serverSide generation of sitemap via `getServerSideProps` doesn't really work, since static websites do not contain SSR.

**Comment by iamvishnusankar** [comment]
@ovflowd Thanks for reporting this. Added support via #638 

**Demo**: [Static export](https://github.com/iamvishnusankar/next-sitemap/tree/feat/static-export/examples/static-export)

Example config:
```js
/* eslint-disable @typescript-eslint/no-var-requires */
/** @type {import('next-sitemap').IConfig} */
const config = {
  siteUrl: process.env.SITE_URL || 'https://example.com',
  generateRobotsTxt: true,
  output: 'static', // Set static output here
}

module.exports = config
```

**Comment by ovflowd** [comment]
Nice! Waiting excitedly for this to get merged 😄 

Thank you for being so quick on implementing this!!
