### ISSUE TITLE
Any way to use `frontmatter` data like `published: true` field to generate sitemap?

### ISSUE THREAD

**Issue by deadcoder0904** [iamvishnusankar/next-sitemap#64]
**Is your feature request related to a problem? Please describe.**

I have a `published` field in my `.mdx` file like:

```js
export const meta = {
	title: 'Hello World',
	date: '2020-09-11T14:54:37.229Z',
	tags: ['hello', 'world'],
	author: 'Akshay Kadam',
	published: false,
}

# Hello World

This is my first blog post, not yet ready to be published
```

**Describe the solution you'd like**
I want to not add the URL to the sitemap because it's `published: false`

**Describe alternatives you've considered**
To use `glob` pattern & then read the `.mdx` file & finally use `transform` function to add individually.

**Additional context**
I think this module can also have `include` function just like `exclude` function so we can add the URLs to Sitemap directly

**Comment by iamvishnusankar** [comment]
Closing. Ref: #65
