### ISSUE TITLE
`robots.txt` isn't generated & `siteUrl` isn't outputted properly while adding script to Next's compilation chain

### ISSUE THREAD

**Issue by deadcoder0904** [iamvishnusankar/next-sitemap#65]
**Describe the bug**

`robots.txt` isn't generated & `siteUrl` isn't outputted properly while adding script to Next's compilation chain. In place of `siteUrl`, it has `undefined` everywhere. Even the `exclude` property isn't working properly.

As mentioned in my previous issue https://github.com/iamvishnusankar/next-sitemap/issues/64, I wanted to use `frontmatter` fields to generate Sitemap.

I found a way to do it by using Next's compilation chain.

Here's a short article on that → https://dev.to/nalanj/adding-scripts-to-next-js-n7i

TL;DR 👇

I put this in my `next.config.js`:

```js
const withBundleAnalyzer = require('@next/bundle-analyzer')({
	enabled: process.env.ANALYZE === 'true',
})

module.exports = withBundleAnalyzer({
	.
	.
	.
	webpack: (config, options) => {
		.
		.
		.
		if (!options.dev && options.isServer) {
			const originalEntry = config.entry

			config.entry = async () => {
				const entries = { ...(await originalEntry()) }
				entries['./scripts/build-rss'] = './scripts/build-rss.js'
				entries['./scripts/build-sitemap'] = './scripts/build-sitemap.js'
				return entries
			}
		}
	}
})
```

The `build-sitemap.js` file gets compiled through Webpack using Next's compilation chain & gets outputted at `.next/server/scripts/build-sitemap.js`

My `build-sitemap.js` file looks like:

```js
import { getAllDraftEssays } from '@/utils/essay/getAllEssayPreviews'
import { getAllDraftTutorials } from '@/utils/tutorial/getAllTutorialPreviews'

const draftPosts = [...getAllDraftEssays(), ...getAllDraftTutorials()].map(
  (p) => `/${p.slug}`
)

export default {
  siteUrl: 'https://akshaykadam.com',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  exclude: draftPosts,
}
```

`module.exports` wasn't working so I used `export default`.

`getAllDraftEssays` looks like:

```js
export const getAllDraftEssays = (): Array<{
	slug: string
	module: any
}> =>
	importAll(require.context('../../pages/essay/?rss', true, /\.mdx$/))
		.filter((p: Post) => !p.module.meta.published)
		.sort((a: Post, b: Post) => dateSortDesc(a.module.meta.date, b.module.meta.date))
```

Technically, this should output `sitemap.xml` correctly & `robots.txt` should be generated. I'm not sure why it isn't happening but would love to build it in my Next's compilation chain as it can generate Sitemap dynamically by using some `frontmatter` fields like `published` or `draft` :)

**Comment by iamvishnusankar** [comment]
Hi @deadcoder0904 , This package is not dependent on webpack. So, reading from frontmatter is out of the scope o this project.

Since, it doesn't any do any sort of transpilation, config file can't be parsed from `esm` modules. You need to use `commonjs` syntax (`module.exports`), otherwise `next-sitemap` won't read the config file. That's the reason for `undefined` errors.

However, I do agree that reading from frontmatter and generating sitemaps based on `published` property is a valid use case.

If you can  get the frontmatter data and urls using your above mention build step, you can use the `transformer` function or `exclude` option.

**Comment by deadcoder0904** [comment]
Would have loved to use this package as it takes away a lot of pain by simply providing a hook into Webpack.

I did manage to make a custom Sitemap generator for my needs:

```js
const fs = require('fs')
const glob = require('fast-glob')
const prettier = require('prettier')
const { getAllPublishedEssays } = require('@/utils/essay/getAllEssayPreviews')
const { getAllPublishedTutorials } = require('@/utils/tutorial/getAllTutorialPreviews')

const posts = [...getAllPublishedEssays(), ...getAllPublishedTutorials()]

const config = {
	siteUrl: 'https://akshaykadam.com',
	changefreq: 'daily',
	priority: '0.7',
	lastmod: new Date().toISOString(),
}

const robotsTxt = `
User-agent: *
Allow: /
Host: ${config.siteUrl}
Sitemap: ${config.siteUrl}/sitemap.xml
`.trim()

const main = async () => {
	const prettierConfig = await prettier.resolveConfig('./prettier.config.js')

	const sitemap = `
        <?xml version="1.0" encoding="UTF-8"?>
        <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
            ${posts
							.map((post) => {
								return `
                        <url>
														<loc>${`${config.siteUrl}/${post.slug}`}</loc>
														<changefreq>${`${config.changefreq}`}</changefreq>
														<priority>${`${config.priority}`}</priority>
														<lastmod>${`${config.lastmod}`}</lastmod>
                        </url>
                    `
							})
							.join('')}
        </urlset>
    `

	const formatted = prettier.format(sitemap, {
		...prettierConfig,
		parser: 'html',
	})

	fs.writeFileSync('public/sitemap.xml', formatted)
	fs.writeFileSync('public/robots.txt', robotsTxt)
}

main()
```

I don't understand why the `module.exports` doesn't work for your package & `export default` throws `undefined` for most things 😂 but anyways thanks for the wonderful package 👍
