### ISSUE TITLE
Server sitemap located inside both robots.txt and sitemap.xml

### ISSUE THREAD

**Issue by activifinder** [iamvishnusankar/next-sitemap#656]
When I create a server sitemap I follow the documentation and add it to my robots.txt settings which looks like this:

```
# *
User-agent: *
Allow: /

# Host
Host: http://127.0.0.1:3000

# Sitemaps
Sitemap: http://example.com/sitemap.xml
Sitemap: http://example.com/server-sitemap.xml
```

But when i look inside sitemap.xml there is also my server sitemap. 

```
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap><loc>http://example.com/sitemap-0.xml</loc></sitemap>
<sitemap><loc>http://example.com/server-sitemap.xml</loc></sitemap>
</sitemapindex>
```

Is this functionality intentional? Is there a specific reason why we want to place them on both or should it just be in one of them?

Thanks

**Comment by jaeger-dvlp** [comment]
You have to exclude in sitemap config.

Try this;

```ts
// next-sitemap.config.js

/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: 'https://example.com',
  generateRobotsTxt: true,
  exclude: ['/server-sitemap-index.xml'], // <= exclude here
  }
```

**Comment by FINDarkside** [comment]
> You have to exclude the server-sitemap in next-sitemap config.

Exclude doesn't work. See https://github.com/iamvishnusankar/next-sitemap/issues/481

**Comment by taraskhvyl** [comment]
Actual bug
