### ISSUE TITLE
SSR Sitemap.xml with alternateRefs does not render properly on browser

### ISSUE THREAD

**Issue by sebastien-comeau** [iamvishnusankar/next-sitemap#676]
**Describe the bug**
Generating a Sitemap with multiple languages SSR with alternateRefs does not render properly on browser:

Following Google instructions from:
https://developers.google.com/search/docs/specialty/international/localized-versions?hl=en&visit_id=638259039702462884-629115822&rd=1#sitemap

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>http://localhost:3000/en/</loc>
        <changefreq>daily</changefreq>
        <xhtml:link rel="alternate" hreflang="en" href="http://localhost:3000/en/" />
        <xhtml:link rel="alternate" hreflang="fr" href="http://localhost:3000/fr/" />
    </url>
</urlset>
```

### Actual Results (rendered in the browser):
![image](https://github.com/iamvishnusankar/next-sitemap/assets/114004123/acc09a99-f9de-45ac-a943-47771c5fcad0)

Compared to sitemap without alternateRefs:

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:mobile="http://www.google.com/schemas/sitemap-mobile/1.0" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
    <url>
        <loc>http://localhost:3000/en/</loc>
        <changefreq>daily</changefreq>
    </url>
</urlset>
```

### Expected results (rendered in the browser):
![image](https://github.com/iamvishnusankar/next-sitemap/assets/114004123/7ac45054-e7f5-4dbd-b574-965ca0a42412)

**To Reproduce**

Create and output a sitemap with alternateRefs.

**Additional context**

Related issues:
https://stackoverflow.com/questions/60564479/sitemap-xml-with-xhtmllink-rel-alternate-hreflang-href-for-multilang
https://stackoverflow.com/questions/36193346/validation-of-xml-sitemap-urlset-with-xhtmllink-inside-url-element

**Comment by bhavesh-chaudhari** [comment]
Did you find any solution for this?
