### ISSUE TITLE
Type error: Could not find a declaration file for module 'next-sitemap'

### ISSUE THREAD

**Issue by Barokai** [iamvishnusankar/next-sitemap#678]
**Describe the bug**
when changing moduleResolution from `node` to `bundler` (as in https://github.com/vercel/next.js/pull/51957/files#diff-066cacecd32e0ca72d47360ddb35c19a676835816eed05163e05564ec0874590) in tsconfig.json, the following errors occur during build:

```
./pages/sitemap.xml/index.tsx:2:36
Type error: Could not find a declaration file for module 'next-sitemap'. 'C:/dev/frontend/project/node_modules/next-sitemap/dist/esm/index.js' implicitly has an 'any' type.
  There are types at 'C:/dev/frontend/project/node_modules/next-sitemap/dist/@types/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'next-sitemap' library may need to update its package.json or typings.

  1 | import type { GetServerSideProps } from "next";
> 2 | import type { ISitemapField } from "next-sitemap";
```

Info: Seems as bundler will be used for all future applications created with create-next-app.

**To Reproduce**

1. change tsonfig.json moduleResolution from node to bundler in an existing project which uses next-pw
2. try to build

**Expected behavior**
Build should succeed

**Screenshots**
-

**Additional context**
created a pull-request #677 which should fix it (tested locally)

**Comment by deviationist** [comment]
Got the same issue

**Comment by Barokai** [comment]
Closing this as my PR was merged, tested with version https://github.com/iamvishnusankar/next-sitemap/releases/tag/4.2.3
