### ISSUE TITLE
Regenerate Sitemap periodically.

### ISSUE THREAD

**Issue by LedzZm** [iamvishnusankar/next-sitemap#680]
In the docks it is mentioned that we should add a command in postbuild, but a sitemap might change, especially if a dynamic sitemap is included.
Is there a way to regenerate the sitemap periodically?

This also affects the `changefreq` attribute. The default value is `daily`, but is that not misleading if the sitemap is not regenerated?

Thanks :)

**Comment by nicogulo** [comment]
I need this tho

**Comment by LedzZm** [comment]
@iamvishnusankar I am not sure how/if I should tag this issue?

Could you give us some insight?

**Comment by tinncdev** [comment]
- Is the `changefreq` supposed to reflect the change frequency of the page's content, not the page url? I don't think it have any relationship with the dynamic sitemap.
- If the page paths (urls) are changed, you can generate these urls in [dynamic sitemap](https://github.com/iamvishnusankar/next-sitemap#generating-dynamicserver-side-sitemaps). Next.js serve it as a `route.ts` GET request response , which means it's [cached by default](https://nextjs.org/docs/app/building-your-application/routing/route-handlers#behavior). You can adjust the cache behavior (or completely disable it) to achive your periodically regeneration purpose.

**Comment by LedzZm** [comment]
Sure but what if your paths depend on a non nextjs backend. In my case I add those paths with additionalPaths, so the generation has to run again, unless I am missing something.

**Comment by tinncdev** [comment]
The paths are no need to be depend on a non nextjs backend to be in server site map.

In one of my project, my paths are a human-readable form of a filter, something like `/products/${productType}/by-${brandName}/price-from${min}-to-${max}`.
I used a shared function from code to generate a set of most common paths from a constant list of filters.
The functions is typescript with some deep dependencies, so it can not be rewritten to js to be used in `additionalPaths`).

Any reasions that these path can't not be added to server sitemap instead of additionalPaths? Perhaps, all your site is static generated?

**Comment by LedzZm** [comment]
I have some paths with slugs dependent on the backend data, my backend URLs are API URLs so I don't necessarily want them indexed. I want the front end URLs to be present in the site map. 

So I generate a sitemap of the API URLs (which contain the slug I need) and transform them to the front end pattern in the additionalPaths callback. For business reasons I want the front end to be able to set the rules for the rewrites.

At first I was going to do that in a page component etc, but then I found this module and thought it would be great to have everything together. additionalPaths works great, but I just need to regenerate the sitemap when new content is added, or at least at some specific intervals.

I hope I covered the reason I don't go with what you suggested, (if I even understood correctly, what you suggested :P).

Thanks for taking the time. If I was not clear or misunderstood something, please let me know, so that I can clarify.

**Comment by tinncdev** [comment]
Haven't figured out your backend URL to sitemap url transform yet.
May I have a look at your `additionalPaths` callback?

Perhaps, if you want to stick to the `additionalPaths`, I think a interval/cronjob/webhook-triggered CICD pipeline would be a better suit.

**Comment by LedzZm** [comment]
I'll be regenerating with cron, thanks @tinncdev
