### ISSUE TITLE
Excluding a file

### ISSUE THREAD

**Issue by Arunjenson-ss** [iamvishnusankar/next-sitemap#687]
### Discussed in https://github.com/iamvishnusankar/next-sitemap/discussions/686

<div type='discussions-op-text'>

<sup>Originally posted by **Arunjenson-SurveySparrow** August  1, 2023</sup>
how to exclude a single url like "example/demo/"
consider example has a home page and demo has one of the innerpage of the example homepage ,i dont need to exclude all inner page but only demo innerpage</div>

**Comment by Arunjenson-SurveySparrow** [comment]
i have used wildcard '*/demo' to exclude only the demo innerpage ,
is this the recommended approach
