### ISSUE TITLE
to automatically exclude the pages with noindex in metarobots

### ISSUE THREAD

**Issue by Arunjenson-ss** [iamvishnusankar/next-sitemap#689]
### Discussed in https://github.com/iamvishnusankar/next-sitemap/discussions/688

<div type='discussions-op-text'>

<sup>Originally posted by **Arunjenson-SurveySparrow** August  2, 2023</sup>
for any page with the 
<img width="345" alt="image" src="https://github.com/iamvishnusankar/next-sitemap/assets/116062066/854d3d72-4ff3-4d7d-a2b1-f3af9b686fda">
no index value in the meta robots should be automatically be excluded from the sitemap ,because the main aim of adding the noindex is to avoid the crawlers to not access the particular url and for other pages should work fine 
can you add this feature, so that we dont need to exclude this file in the config rather its automatically exclude because of the meta robots value</div>

**Comment by austencm** [comment]
I'm working on a project where the pages come from a CMS, in which an editor can toggle whether the page is indexable or not. It's too expensive to check every path in the transform function.

> Hey @Arunjenson-ss, it seems like it won't be added in this lib. But as discussed in [#182 (comment)](https://github.com/iamvishnusankar/next-sitemap/issues/182#issuecomment-1224756239), you can follow a workaround to handle it by your own.

^ This solution works for now, but I'd like to suggest allowing an async function for `exclude`.
