### ISSUE TITLE
Sitemap index

### ISSUE THREAD

**Issue by arnaudjnn** [iamvishnusankar/next-sitemap#69]
**Is your feature request related to a problem? Please describe.**
I want to add an index sitemap with all the children urls inside as detailed here: https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps

**Describe the solution you'd like**
I would like a new option like ```index: true``` to use the first /sitemap.xml as index.

**Comment by iamvishnusankar** [comment]
Hi @arnaudjnn , This is totally possible with the current setup. I'll add support for this soon.

**Comment by tofiqquadri** [comment]
@arnaudjnn @iamvishnusankar any updates on this?

**Comment by nbunner** [comment]
I'd like to see this too if possible? We're using the dynamic sitemap option so being able to pass in an extra option there to generate an index sitemap would be very useful. Thanks.

**Comment by iamvishnusankar** [comment]
> I'd like to see this too if possible? We're using the dynamic sitemap option so being able to pass in an extra option there to generate an index sitemap would be very useful. Thanks.

@nbunner This is my plan for next version of `next-sitemap`. Basically creating two APIs for sitemap and index generation. Doing this way will help to use them on server-side and for static generation.

Server side

- `getServerSideSitemap`: Generates sitemap XML
- `getServerSideIndexSitemap`: Generates index sitemap XML

Static build:
- `next-sitemap`: Build sitemaps only
- `next-sitemap --mode=index`: Build sitemaps with index sitemap.

I'm little busy with my current projects. I'll start working on this as soon as possible.


@arnaudjnn, @tofiqquadri  Sorry for the late reply.

**Comment by nbunner** [comment]
thanks, much appreciated.

**Comment by archanaagivale30** [comment]
@iamvishnusankar  is this feature (sitemap index) available  now? Actually it will be the  very useful  feature.
Thanks !

**Comment by rus-yurchenko** [comment]
+1, we're highly waiting for this to be implemented. Thanks!

**Comment by MichaelBurgess** [comment]
Would love to be able to generate an index file + multiple sitemaps using the package. Any idea when this will be available? Thanks!

**Comment by iamvishnusankar** [comment]
@arnaudjnn @MichaelBurgess @rus-yurchenko @archanaagivale30 @nbunner @tofiqquadri 

Added support for sitemap indexing #268 

Now default sitemap.xml will be sitemap index file.
