### ISSUE TITLE
Support mjs extension for config file

### ISSUE THREAD

**Issue by RodrigoTomeES** [iamvishnusankar/next-sitemap#690]
**Is your feature request related to a problem? Please describe.**
Yes, I want to use Modules inside config file

**Describe the solution you'd like**
Support mjs files

**Describe alternatives you've considered**
Give up and use CommonJS 😢 

Thanks! ❤️

**Comment by RodrigoTomeES** [comment]
Up

**Comment by RodrigoTomeES** [comment]
Up

**Comment by RodrigoTomeES** [comment]
Can we this issue reopened, please? @iamvishnusankar without this is very hard to make a fetch to get the pages to exclude from a CMS

**Comment by WanLinLin** [comment]
Hey @RodrigoTomeES, I've tried using mjs and it works.

```
next-sitemap --config next-sitemap.config.mjs
```

next-sitemap version 4.2.3
