### ISSUE TITLE
hello I am using next-sitemap with my nextjs app. My website is multi-lingual. I want only the /en, /fr and not '/' pages. Likewise, for cancel page, I don't want /en/cancel, /fr/cancel, but only /cancel . how do I do it?

### ISSUE THREAD

**Issue by joorraa** [iamvishnusankar/next-sitemap#691]
**Describe the bug**
hello I am using next-sitemap with my nextjs app. My website is multi-lingual. I want only the /en, /ar and not '/' pages. Likewise, for cancel page, I don't want /en/cancel, /fr/cancel, but only /cancel . how do I do it?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by joorraa** [comment]
@iamvishnusankar please brother help!!!

**Comment by iamvishnusankar** [comment]
@joorraa Check [custom transformation functions ](https://github.com/iamvishnusankar/next-sitemap#custom-transformation-function)

You can check each url and return a null value if the url matches `ignore` condition

**Comment by joorraa** [comment]
> @joorraa Check [custom transformation functions ](https://github.com/iamvishnusankar/next-sitemap#custom-transformation-function)
> 
> You can check each url and return a null value if the url matches `ignore` condition

thank you so much good sir!
