### ISSUE TITLE
next/headers call prevent sitemap generation

### ISSUE THREAD

**Issue by bastienrobert** [iamvishnusankar/next-sitemap#692]
**Describe the bug**
When `headers()` (imported from next/headers) is called in a layout.js or in a page.js file, next-sitemap doesn't generate.

**To Reproduce**
**Link to the repro**: https://github.com/bastienrobert/next-sitemap-generation-with-headers-repro

- create a new project with `pnpm create next-app`
- install `next sitemap`
- create a basic `next-sitemap.config.js` file
- add postbuild script
- add `headers()` call (from next/headers) in layout.js
- run `pnpm build`
- run `pnpm postbuild`

**sitemap is empty**

- remove `headers()` in layout.js
- run `pnpm build`
- run `pnpm postbuild`

**sitemap-0.xml is generated**

**Expected behavior**
`sitemap-0.xml` generation event if there's a `headers()` call.

**Comment by pranavks** [comment]
+1

**Comment by LouisCuvelierStadion** [comment]
Same here when `headers()` are called

**Comment by AlexanderBich** [comment]
+1

**Comment by bastienrobert** [comment]
Please don't "+1", use the Github reactions feature
