### ISSUE TITLE
Don't make a new released when the changes doesn't affect to the package

### ISSUE THREAD

**Issue by RodrigoTomeES** [iamvishnusankar/next-sitemap#696]
I think that new versions of the library should only be published when there are real changes in it. An update in the documentation for Github, the web, exclusively development dependencies... do not bring anything to end users with a new version of the package.

It's a bit frustrating managing pinned dependencies and having to read through all the changelogs to find out that there really aren't any changes.

I hope my comment is worth helping. Thank you very much for the library is great!

**Comment by iamvishnusankar** [comment]
@RodrigoTomeES Thanks for the feedback. You're free to skip the minor patches as they're triggered by dependabot updating dependencies.

If you're talking about the release happened yesterday, it's because of this issue: https://github.com/iamvishnusankar/next-sitemap/issues/693

**Comment by RodrigoTomeES** [comment]
@iamvishnusankar thanks, in the changelog of the release 4.2.2 doesn't appear that change 😅. Only appear the changes of the link in the website.

https://github.com/iamvishnusankar/next-sitemap/releases/tag/v4.2.2
