### ISSUE TITLE
Does this support /app directory in next13?

### ISSUE THREAD

**Issue by bonbonio** [iamvishnusankar/next-sitemap#701]
Hi,

I have added this to nextjs 13, and I have migrated to use the /src/app approach which Next13 promotes as the best option. When I run the postbuild, it only generates the static pages; the /articles section isnt in the sitemap.

I am using this code, removed the cruft though for clarity.

```
export default async function ArticlesPage() {
  const stories = await getData();

  return (
    <>
      view
    </>
  );
}

const getData = async () => {
  const res = await fetch(``, { cache: 'no-store' });
  const data = await res.json();
  const { stories } = data;

  return stories;
}

```

**Comment by nitinTJ** [comment]
I am grouping the routes and its not even generating the static pages for me.

**Comment by alasdair009** [comment]
I am not getting the static pages either - any word on this?

**Comment by agonist** [comment]
You need to use `generateStaticParams` 
See the [official doc](https://nextjs.org/docs/app/api-reference/functions/generate-static-params)
After that everything should end up in your sitemap. I've been using it for a while very and everything is smooth.
