### ISSUE TITLE
[Suggest] Include leafs in the generated sitemap?

### ISSUE THREAD

**Issue by gustaveWPM** [iamvishnusankar/next-sitemap#703]
Hello,
I was just wondering why the sitemap generator does not include my blog posts leafs in the `<loc>` fields?

![generatedRoutes](https://github.com/iamvishnusankar/next-sitemap/assets/118654172/e0bf8e91-e83d-47e9-be60-dd4caee9fbb4)

![generatedSitemap](https://github.com/iamvishnusankar/next-sitemap/assets/118654172/35216c5a-2842-44d4-9572-cca397e12057)

Those leafs are missing:
> `/fr/patch-notes/dashboard/post-01`
> `/fr/patch-notes/discord-bot/post-01`
> `/en/patch-notes/dashboard/post-01`
> `/en/patch-notes/discord-bot/post-01`

To give a real-world example of what I suggest, this sitemap also specify the blog posts leafs:
https://www.abondance.com/post-sitemap.xml

> `https://www.abondance.com/20051124-8440-google-ferait-il-de-laerophagie.html`
`https://www.abondance.com/20051117-8438-webdesign-et-referencement.html`

Thank you for your answers! :)

**Comment by gustaveWPM** [comment]
ping @iamvishnusankar

**Comment by drwpow** [comment]
Having a similar issue. Not using localization, but nested dynamic routes are missing from the sitemap. Even when they call `getStaticPaths()`, and are marked as static routes in the build output, they are still missing from the sitemap

**Comment by Arunjenson-ss** [comment]
any update on this??
