### ISSUE TITLE
Additional sitemaps not included in index sitemap

### ISSUE THREAD

**Issue by Xaptor** [iamvishnusankar/next-sitemap#704]
**Describe the bug**
I want to add some dynamic sitemaps to the index sitemap and I used the example to create an index sitemap from the documentation but it is not working for me. As far as I understood the getServerSideSitemapIndexLegacy allows to provide an array of additional sitemaps which should be included to the index sitemap.

```
// pages/server-sitemap-index.xml/index.tsx
import { getServerSideSitemapIndexLegacy } from 'next-sitemap'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // Method to source urls from cms
  // const urls = await fetch('https//example.com/api')

  return getServerSideSitemapIndexLegacy(ctx, [
    'https://example.com/path-1.xml', <----- Not added to index sitemap
    'https://example.com/path-2.xml', <----- Not added to index sitemap
  ])
}

// Default export to prevent next.js errors
export default function SitemapIndex() {}
```

**To Reproduce**

1. Clone project from https://github.com/Xaptor/next-sitemap-test . This project is a plain nextjs example with next-sitemap added. Created just for this test.
2. Run npm install
3. Run npm build
4. See sitemap.xml not showing the path-1 and path-2 sitemap

**Expected behavior**
https://example.com/path-1.xml and https://example.com/path-2.xml in sitemap.xml

**Comment by hokidoki** [comment]
Hi. 

first . `getServerSideSitemapIndexLegacy ` can not make dynamic sitemap . 

you can use SitemapBuilder and withXMLResponseLegacy in getServerSideProps. 

this is example 

`
import { SitemapBuilder, withXMLResponseLegacy } from "next-sitemap";
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // Method to source urls from cms
  // const urls = await fetch('https//example.com/api')
 const builder = new SitemapBuilder()
 const sitemaps = builder.buildSitemapIndexXml( [
    'https://example.com/path-1.xml', <----- Not added to index sitemap
    'https://example.com/path-2.xml', <----- Not added to index sitemap
  ])
  return withXMLResponseLegacy(ctx, sitemaps)
}

// Default export to prevent next.js errors
export default function SitemapIndex() {}
`

**Comment by mctrl** [comment]
I also would like to have some guidance on this please. 

I would like to add additional sitemaps to my sitemap.xml without adding them to the robots.txt. However, it's unclear to me where I should use the above mentioned SitemapBuilder. I would like my sitemap.xml to keep behaving as per configuration (splitting the static generated pages in indexes etc) but need to add a few custom sitemap indexes to point to SSR sitemaps which I'm handling already with getServerSideSitemapLegacy for creation. 

Isn't there an option such as "additionalSitemap"? I can only see it for the robots.txt options. 

Many thanks in advance 🙏
