### ISSUE TITLE
[Probs a bug] Totally empty sitemap? Lol?

### ISSUE THREAD

**Issue by gustaveWPM** [iamvishnusankar/next-sitemap#705]
Hello.

I'm using Next.js 13 with the App Router.
I know that next-sitemap can generate good sitemaps files with this setup.
I've already done this in my current (and first Next.js) project.

I'm doing my best with `generateStaticParams`, and have an exhaustive output of my paths when I build my Next project.

Output of `yarn build`:
```
Route (app)
┌ ● /[locale]
├   ├ /fr
├   └ /en
├ ● /[locale]/[categ]
├   ├ /fr/patch-notes
├   └ /en/patch-notes
├ ● /[locale]/[categ]/[subcateg]
├   ├ /fr/patch-notes/dashboard
├   ├ /fr/patch-notes/discord-bot
├   ├ /en/patch-notes/dashboard
├   └ /en/patch-notes/discord-bot
├ ● /[locale]/[categ]/[subcateg]/[slug]
├   ├ /fr/patch-notes/dashboard/post-01
├   ├ /en/patch-notes/dashboard/post-01
├   ├ /fr/patch-notes/discord-bot/post-01
├   └ /en/patch-notes/discord-bot/post-01
├ ● /[locale]/dashboard
├   ├ /fr/dashboard
├   └ /en/dashboard
├ ○ /apple-icon.png
├ ○ /favicon.ico
└ ○ /icon.svg

●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

```

Here is `sitemap.xml`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
</sitemapindex>
```
(yah, I'm crying)

Moreover, here's the disaster:
As I'm a bit of an idiot (lol), I tend to use the `git commit --amend` command a lot and I totally lost the original code which was somehow "compatible" (?) with next-sitemap, and which was not generating empty sitemaps. 

To be honest, I don't have the courage, nor the knowledge, to understand what's happening to take me from a correct sitemap generation to a totally empty one. ( :'( )

I've made a branch to help you to reproduce and investigate.
https://github.com/Tirraa/dashboard_rtm/tree/next-sitemap-empty-sitemap-issue

> :information_source: It would be also helpful to know how could I investigate myself? I naively assumed that if my routes were displayed correctly in the build output, it should be fine (lol).

Warm regards. ( I'm so sad to have an empty sitemap. :'( )

**Comment by RaenonX** [comment]
Having the same issue, I thought it's my issue (missing some config) until I see this. Will wait for the inputs here.

**Comment by yongyi520** [comment]
Up this, I have the same issue as well

**Comment by fgeorgsson** [comment]
Empty sitemap here as well

**Comment by letops** [comment]
For me it is just happening with the new `app` directory, I have 2 other projects with this same library and almost exactly the same configuration but they use the old `pages` directory and they work perfectly

**Comment by gustaveWPM** [comment]
> For me it is just happening with the new `app` directory, I have 2 other projects with this same library and almost exactly the same configuration but they use the old `pages` directory and they work perfectly

idk why, but it was initially working fine on my project, using app directory. :/

**Comment by sofly** [comment]
Empty sitemap as well

**Comment by JJGoogles** [comment]
When can we expect any comment or progress on this issue? We currently have to resort to maintaining the Sitemap manually which is quite cumbersome given that most of our pages are generated based on CMS content.

**Comment by gustaveWPM** [comment]
Hmmm...
I think I read somewhere that _Next-Sitemap_ is based on the `build-manifest.json` file (`.next/.build-manifest.json`).

It seems that there is a lot more informations in the `trace` file (`.next/trace`) that in the `build-manifest.json` when the _SSG_ from the _App Directory_'s context is used.

Maybe _Next-Sitemap_ was designed to work with _Static_ generation, but not with the _SSG_ one.

**Comment by gustaveWPM** [comment]
ping @iamvishnusankar 
Have you started to investigate?

**Comment by gustaveWPM** [comment]
Lol. I've done some changes in the architecture of my project, and now the sitemap generation came back (partially).

Created a new branch, in addition of https://github.com/Tirraa/dashboard_rtm/tree/next-sitemap-empty-sitemap-issue
- https://github.com/Tirraa/dashboard_rtm/tree/next-sitemap-empty-sitemap-issue2

Hope it would help to investigate.

**Comment by rafalzawadzki** [comment]
same issue here. Pages marked as Static during the build are in sitemap, but SSG not. 
✅ `○  (Static)     automatically rendered as static HTML (uses no initial props)`
❌ `●  (SSG)        automatically generated as static HTML + JSON (uses getStaticProps)`

**Comment by gustaveWPM** [comment]
Idk why, but I have the impression that if you have a minimum of one "Server" page, things go back to normal?

Could someone try creating a dynamic path [stupidworkaround] and putting in an empty page that just returns a div? Just to see.

**Comment by rafalzawadzki** [comment]
I have pages of all kinds in my build (two server side and two static) - still doesn't work.

**Comment by gustaveWPM** [comment]
> I have pages of all kinds in my build (two server side and two static) - still doesn't work.

Hmm, that's curious.

Does your `next build` feedback provide something like this?

> λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
> ○  (Static)  automatically rendered as static HTML (uses no initial props)
> ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

**Comment by rafalzawadzki** [comment]
> > I have pages of all kinds in my build (two server side and two static) - still doesn't work.
> 
> 
> 
> Hmm, that's curious.
> 
> 
> 
> Does your `next build` feedback prints something like this?
> 
> 
> 
> > λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
> 
> > ○  (Static)  automatically rendered as static HTML (uses no initial props)
> 
> > ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)

Yup, with one more:

```

ℇ  (Streaming)  server-side renders with streaming (uses React 18 SSR streaming or Server Components)
λ  (Server)     server-side renders at runtime (uses getInitialProps or getServerSideProps)
○  (Static)     automatically rendered as static HTML (uses no initial props)
●  (SSG)        automatically generated as static HTML + JSON (uses getStaticProps)

```

**Comment by nsberrow** [comment]
I'm in the same boat, I've tried and tried but I can't get my sitemap to generate all the static paths, also on nextjs13

**Comment by nitinTJ** [comment]
Facing the same issue.

**Comment by bastienrobert** [comment]
I think it might be related to this issue : https://github.com/iamvishnusankar/next-sitemap/issues/692

**Comment by rafalzawadzki** [comment]
Could also be this: https://github.com/iamvishnusankar/next-sitemap/issues/700

**Comment by erwannbst** [comment]
Same issue

**Comment by AlexanderBich** [comment]
in my case it was related to this: https://github.com/iamvishnusankar/next-sitemap/issues/692

**Comment by evertjr** [comment]
I have one project having issues with sitemap on app router while others works fine, it was driving me crazy, I compared versions and  downgraded to  4.1.8 and it seems to be working now. This library seems a little abandoned? The oficial sitemap support from nextjs is very basic, how do you even generate sitemaps for static pages generated at build time @agonist ?

**Comment by evertjr** [comment]
> > I have one project having issues with sitemap on app router while others works fine, it was driving me crazy, I compared versions and downgraded to 4.1.8 and it seems to be working now. This library seems a little abandoned? The oficial sitemap support from nextjs is very basic, how do you even generate sitemaps for static pages generated at build time @agonist ?
> 
> It depends on how you generate your static page, but on my side, I generate page based on data from my db, so I'm simply generating my sitemap based on the same data I use to generate static page. Just an example for the idea :
> 
> ```
>   const tools = await findAllToolsSlugOnly(); // this is my db call
> 
>   const allTools = tools.map((t) => {
>     const to: R = {
>       url: `${site}/ai-tools/${t.slug}`,
>       lastModified: new Date(),
>       changeFrequency: "daily",
>       priority: 0.7,
>     };
>     return to;
>   });
> ```
> 
> I'm doing something like that. So I have various array of from my static pages for different routes. once setup you don't have to touch it anymore and what's happening is very predictable which make the sitemap less mysterious and give you full control over it. and adding a single regular page just take 10 seconds which is find.

thanks for the suggestion, I kinda liked how this library used to "just works", but I think it's worth doing some refactoring to use the built in support from nextjs and get more predictable results, I wrote a function to map the static pages from the filesystem, now I just need to include pages generated at build time.

**Comment by kevinstark86** [comment]
I'm using Next 14 with the pages folder and I'm getting empty sitemaps too. No errors.

**Comment by polvallverdu** [comment]
Getting empty sitemaps even exporting `generateStaticParams` on my pages. I'm using Next 14 with App directory.

**Comment by Dlazder** [comment]
Same problem on next 14.1.2.

config
```
module.exports = {
    siteUrl: 'https://aksenov-maksim.ru',
    generateRobotsTxt: false,
    outDir: './'
};`

**Comment by InsightfulFuture** [comment]
I'm using Next.js 14 and experiencing the same issue.

**Comment by tiste** [comment]
On my side, I had a root layout (on a approuter next.js 14), and when importing `import { headers } from "next/headers";`, the sitemap were empty.

**Comment by berzi** [comment]
This makes the whole package unusable and there are basically no alternatives around bar manually maintaining a sitemap, which is not acceptable. Nextjs itself pretty much did not go any further than making manual generation easier *because this package exists*, so it needs to work.

#692 needs to be reopened: it's a very current bug and the ticket was closed automatically because it was ignored. Such a small thing can't make the package entirely useless for so many users.

**Comment by Th1nhNg0** [comment]
I got the same bug with next.js 14, currently I was manually code sitemap

**Comment by berzi** [comment]
I worked around this in my case by removing my `import { headers } from "next/headers";` import from `layout.tsx` and using `const headers = require('next/headers').headers();` inside the layout function instead.

**Comment by travistylervii** [comment]
Same problem in nextjs 14.

**Comment by johanazhu** [comment]
I'm using Next.js 14 and experiencing the same issue.

**Comment by RayhanHamada** [comment]
Currently it's quite useless for me to use this library in next 14 using app router. I'm able to generate static pages using `additionalPaths` inside `next-sitemap.config.js`, kinda like this

```ts
const globby = require('globby')

const basePath = process.env.NEXT_PUBLIC_URL

/** @type {import('next-sitemap').IConfig} */
module.exports = {
	siteUrl: basePath,
	generateRobotsTxt: true,
	async additionalPaths(config) {
		// get all static pages
		const globResult = await globby(['app/**/!([.*])/page.tsx'])
		const now = new Date().toISOString()

		const pages = globResult
			.filter((e) => !e.includes('['))
			.map((e) => e.replace(/^app/, '').replace('/page.tsx', ''))
			.map((e) => new URL(e, basePath).toString())
			.map((loc) => ({
				loc,
				lastmod: now,
				changefreq: config.changefreq,
			}))

		return [...pages]
	},
	async transform(config, path) {
		const loc = new URL(path, config.siteUrl)

		return {
			loc: loc.toString(),
			changefreq: config.changefreq,
			lastmod: config.lastmod,
		}
	},
}

```

and since `additionaPaths` is async i'm planning to do dynamic sitemap from here as well (fetch the data from my CMS).
