### ISSUE TITLE
Additional sitemaps included in robots.txt despite includeNonIndexSitemaps set to false

### ISSUE THREAD

**Issue by paras-malhotra** [iamvishnusankar/next-sitemap#708]
**Describe the bug**
Here is my config:

```js
/** @type {import('next-sitemap').IConfig} */
module.exports = {
    siteUrl: process.env.APP_URL ?? 'https://example.com',
    generateRobotsTxt: true,
    robotsTxtOptions: {
        additionalSitemaps: [
            'https://example.com/blog/sitemap.xml'
        ],
        includeNonIndexSitemaps: false
    }
    // ...other options
}
```

Despite this config, /blog/sitemap.xml appears in both sitemap.xml (index sitemap) and robots.txt

**To Reproduce**
Steps explained above

**Expected behavior**
/blog/sitemap.xml should not appear in robots.txt but should appear in sitemap.xml

**Comment by FINDarkside** [comment]
Related: #481, #656

Here's a PR fixing it, which is closed by a bot like the previous issues: #568
