### ISSUE TITLE
Support for Catch All Routes

### ISSUE THREAD

**Issue by pigmanbear** [iamvishnusankar/next-sitemap#71]
Slug with underscore is removed because naive Regexp in `isNextInternalUrl`

In any route I assume, but in my particular case, using getStaticPaths, the prerender manifest creates routes such as 'pineapple_basil_smash', this causes the routes to be removed in `createUrlSet`

The test for `isNextInternal` needs to be more specific and not automatically remove routes with an underscore.

The initial improvement would be to just test for /\_app , /\_error and not for just the underscore. Then testing for routes with brackets.

If I find the time, maybe I can take a crack at a fix if you are willing to accept a PR, didn't see anything in the README about contributing.

**Comment by iamvishnusankar** [comment]
@pigmanbear I've updated the regexp to test the internal urls. Now it only catches any url which starts with `/_` or contains `[` (url params). So your use case would be safe from now onwards.

For the contribution part, all PRs are welcome. :)
