### ISSUE TITLE
Type Error and Rendering Issue in getServerSideSitemapIndexLegacy,Additionally, observed that the rendering results in [object Object] [object Object].

### ISSUE THREAD

**Issue by KevinYouu** [iamvishnusankar/next-sitemap#742]
**Description of the issue**

Encountered a type error while performing server-side rendering (SSR). The specific error message is: "Argument of type '{ loc: string; lastmod: string; }[]' is not assignable to parameter of type 'string[]'.
  Type '{ loc: string; lastmod: string; }' is not assignable to type 'string'."
Additionally, when rendering, observed [object Object] [object Object].

1. Use the following code for server-side rendering.
```tsx
// pages/server-sitemap.xml/index.tsx
import { getServerSideSitemapLegacy } from 'next-sitemap'
import { GetServerSideProps } from 'next'
 
export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // Method to source urls from cms
  // const urls = await fetch('https//example.com/api')
 
  const fields = [
    {
      loc: 'https://example.com', // Absolute url
      lastmod: new Date().toISOString(),
      // changefreq
      // priority
    },
    {
      loc: 'https://example.com/dynamic-path-2', // Absolute url
      lastmod: new Date().toISOString(),
      // changefreq
      // priority
    },
  ]
 
  return getServerSideSitemapLegacy(ctx, fields)
}
 
// Default export to prevent next.js errors
export default function Sitemap() {}
```

2. Visit the page 'http://localhost:3000/server-sitemap.xml'
3. See the error 

**Screenshots**
<img width="1124" alt="image" src="https://github.com/iamvishnusankar/next-sitemap/assets/46970005/007120c4-8e64-4042-962f-eea141a3e283">

<img width="489" alt="截屏2023-12-04 22 10 32" src="https://github.com/iamvishnusankar/next-sitemap/assets/46970005/7720bc83-e50a-4b76-a794-3594212337ae">
<img width="554" alt="image" src="https://github.com/iamvishnusankar/next-sitemap/assets/46970005/8a23a634-353a-4fcb-9097-8ba2967c4c59">

**Comment by LouisR-P** [comment]
facing same issue 😔
returning this in my transform function in `next-sitemap.config.js` file:
<img width="795" alt="image" src="https://github.com/iamvishnusankar/next-sitemap/assets/46956027/940d0cb4-a94a-4eb5-9f4e-ee1d7343faeb">
will result in this in my sitemap:
![image](https://github.com/iamvishnusankar/next-sitemap/assets/46956027/c056d243-aafc-4f32-9fce-5697f127e6af)

any clue? @iamvishnusankar

**Comment by victorcarvalhosp** [comment]
> facing same issue 😔 returning this in my transform function in `next-sitemap.config.js` file: <img alt="image" width="795" src="https://private-user-images.githubusercontent.com/46956027/292044899-940d0cb4-a94a-4eb5-9f4e-ee1d7343faeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDEwOTQ3NjUsIm5iZiI6MTc0MTA5NDQ2NSwicGF0aCI6Ii80Njk1NjAyNy8yOTIwNDQ4OTktOTQwZDBjYjQtYTk0YS00ZWI1LTlmNGUtZWUxZDczNDNmYWViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzA0VDEzMjEwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YmZmZTQyMDdiN2MzNmMwZDhlNjhmYzc2ZDA5MTk0M2VmYmIzMWFiYWJiNmUxOWMxNzgxZWJkZTAxYmM0MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IYfczn_PJ8fEmVNNC_Zrf7CeGuKUz9QjqDd3LhGKfPw"> will result in this in my sitemap: ![image](https://github.com/iamvishnusankar/next-sitemap/assets/46956027/c056d243-aafc-4f32-9fce-5697f127e6af)
> 
> any clue? [@iamvishnusankar](https://github.com/iamvishnusankar)

Did you find a workaround to this? I'm having the exact same issue

**Comment by RSurya99** [comment]
Still got the same issue until now, if I did an array of string it shows normally, but if an array of object it becomes [Object object]
