### ISSUE TITLE
I want the host directive to be an optional entry.

### ISSUE THREAD

**Issue by hashibadaiki** [iamvishnusankar/next-sitemap#748]
**Is your feature request related to a problem? Please describe.**

![error-image](https://github.com/iamvishnusankar/next-sitemap/assets/57456234/720ea621-a427-4430-8b4a-bf7417fe8e1e)

I am getting a "syntax error" at the host directive.
 (This is the result of a crawler run by a search engine called bing.)

**Describe the solution you'd like**

```next-sitemap.config.js
  robotsTxtOptions: {
    additionalSitemaps: [
     "example.com" + "foo",
    ],
    policies: [
      {
        userAgent: '*',
        allow: '/',
      },
    ],
  hideHost: true, // ← Please add this option!
  },
```

**Describe alternatives you've considered**

And now google doesn't seem to recognize the Host directive either!

https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt?hl=en#syntax
https://stackoverflow.com/questions/22011604/can-i-use-the-host-directive-in-robots-txt

Thanks for reading.

**Additional context**

**Comment by lukastransom** [comment]
Temporary workaround found here: https://github.com/iamvishnusankar/next-sitemap/issues/381#issuecomment-1268146841

**Comment by hashibadaiki** [comment]
thx!!!!!
