### ISSUE TITLE
Es posbile la creación de ejemplos?

### ISSUE THREAD

**Issue by potier97** [iamvishnusankar/next-sitemap#75]
Estaba mirando la funcionalidad de esta herramienta pero no es muy clara para su uso en el desarrollo cuando se genera y despliega la aplicación en producción, no se si es posible crear un ejemplo con una página real en Vercel y colocar el ejemplo. Gracias

Sorry to write in Spanish, I will try to translate the above.

I was looking at the functionality of this tool but it is not very clear for use in development when the application is generated and deployed in production, I do not know if it is possible to create an example with a real page in Vercel and place the example. Thank you

**Comment by iamvishnusankar** [comment]
@potier97  You can find the full documentation [here](https://github.com/iamvishnusankar/next-sitemap#next-sitemap) and a working example [here](https://github.com/iamvishnusankar/next-sitemap/tree/master/example). It's a standalone build tool, and I'm not sure what do you meant by "real page".
