### ISSUE TITLE
why add amp;  in my url

### ISSUE THREAD

**Issue by yi1260** [iamvishnusankar/next-sitemap#766]
**Describe the bug**
i use 'additionalPaths' to add my custom url : 

![image](https://github.com/iamvishnusankar/next-sitemap/assets/5690223/4ed6a1b0-daa9-4115-a2a2-e2a12cfd593b)

but i get a result like this: 
![image](https://github.com/iamvishnusankar/next-sitemap/assets/5690223/e96596dc-16dc-413a-bf41-cacfed6dff53)

whywhy 'amp;' is added after '&' ?

**Comment by graemegeorge** [comment]
@yi1260 This functionality was added as a result of https://github.com/iamvishnusankar/next-sitemap/issues/207 where `&` is not valid for xml generation but does appear in a url. While we probably shouldn't `&` is still valid in a url in many cases though not ideal. Take a CMS for example, an editor may create a title that produces a slug such as `/burger-&-fries` who wouldn't be aware of the implications this has on an xml file. 

I think in your case, you shouldn't need to include the url search params in your sitemap declaration (correct me if I'm wrong). A sitemap will only require the page route itself, not it's "state", just remove the `?page=1...` and you should be good to go. Assuming I'm not missing nay other specifics to your requirement.
