### ISSUE TITLE
Add support for generating sitemaps for multiple domains

### ISSUE THREAD

**Issue by supernaut** [iamvishnusankar/next-sitemap#767]
I have several Next.js websites with different domains for different markets. Some domains have several locales handled with prefixes, some don't. As far as I can tell there is no way to generate sitemaps for each domain with `next-sitemap`.

I would like a way to generate sitemaps for each domain with alternate URL's both for other domains and locale prefixes on the same or other domains. Something like:

Sitemap for example.com:

```xml
<url>
    <loc>https://www.example.com/path/to/page</loc>
    <xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/path/to/page" />
    <xhtml:link rel="alternate" hreflang="de-de" href="https://www.example.de/path/to/page" />
    <xhtml:link rel="alternate" hreflang="nl-be" href="https://www.example.be/path/to/page" />
    <xhtml:link rel="alternate" hreflang="fr-be" href="https://www.example.be/fr/path/to/page" />
</url>
```

Sitemap for example.de:

```xml
<url>
    <loc>https://www.example.de/path/to/page</loc>
    <xhtml:link rel="alternate" hreflang="de-de" href="https://www.example.de/path/to/page" />
    <xhtml:link rel="alternate" hreflang="en" href="https://www.example.com/path/to/page" />
    <xhtml:link rel="alternate" hreflang="nl-be" href="https://www.example.be/path/to/page" />
    <xhtml:link rel="alternate" hreflang="fr-be" href="https://www.example.be/fr/path/to/page" />
</url>
```
It would have to combined with middleware or rerwites outside of Next.js I assume.

Today I generate sitemaps with my own code with filenames with locale suffixes like `sitemap.en.xml`, `sitemap.de-de.xml`, etc. I use middleware to rewrite requests to `/sitemap.xml` to the correct locale.

I would love to be able to refactor out a lot of my custom code and just use a tool that works the same on all websites. If `next-sitemap` easily could be configured to generate sitemaps for all domains I would love it. As it is now I can't use it but I would love to.

Caveat: This might be possible today, just that I don't understand the correct configuration for it.

**Comment by thiennd3589** [comment]
> Today I generate sitemaps with my own code with filenames with locale suffixes like `sitemap.en.xml`, `sitemap.de-de.xml`, etc. I use middleware to rewrite requests to `/sitemap.xml` to the correct locale.
> 

Can you share your solutions about that?
