### ISSUE TITLE
next-sitemap doesn't work with next-auth

### ISSUE THREAD

**Issue by Skolaczk** [iamvishnusankar/next-sitemap#768]
repo: https://github.com/Skolaczk/next-starter
After adding next-auth to my app next-sitemap doesn't generate sitemap properly.  The result of building the app before and adding next-auth to the photos. 
Does anyone have an idea how to fix this?

I tried adding this line to sitemap.config.js: 
```
exclude: ['/api/auth/*']
```
, but it didn't help.

Sitemap before adding next-auth:
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
 <sitemap>
  <loc>http://localhost:3000/sitemap-0.xml</loc>
 </sitemap>
</sitemapindex>
```

Sitemap after adding next-auth:
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"> </sitemapindex>
```

![Frame 2](https://github.com/iamvishnusankar/next-sitemap/assets/76774237/66f18d85-9d6d-4d05-a118-15be28b45a88)
![Frame 1](https://github.com/iamvishnusankar/next-sitemap/assets/76774237/eaffc6d7-fe79-4bb1-ab54-36b8dd14a123)

**Comment by travistylervii** [comment]
This ever get solved? I think I have the same issue.

**Comment by Skolaczk** [comment]
> This ever get solved? I think I have the same issue. 
> 

I don't know.  I still have this bug

**Comment by johanazhu** [comment]
+1
