### ISSUE TITLE
"robots.txt" or sitemap doesn't generated with npm scripts

### ISSUE THREAD

**Issue by ali-furkqn** [iamvishnusankar/next-sitemap#81]
It work fine when i want to generate sitemap with yarn. I try to use npm while but it doesn't work that sitemap or robots.txt generating. What's the reason for this ?

Occurrence Example:
- First of all, package add to devDependencies. Like `npm i -D next-sitemap`
- Create next-sitemap file as below
```js
module.exports = {
    siteUrl: "https://example.com",
    generateRobotsTxt: true
}
```
- Add postbuild script on package.json
```json
  "scripts": {
    "build": "next build",
    "postbuild": "next-sitemap",
  },
```
- Run the `npm run build` and you will see that it didn't work as expected that files exported to `public` directory.

**Comment by iamvishnusankar** [comment]
@ali-furkqn Please provide a reproduction repo. 

If you're using windows machine, it might be due to #61. If this is the case, please read [post build documentation for windows machines](https://github.com/iamvishnusankar/next-sitemap#building-sitemaps)

**Comment by ali-furkqn** [comment]
Wow this's interesting problem. I'm using windows. I've never thought about path priority. I changed the file name and added config option. Now, It's working correctly.
