### ISSUE TITLE
Next-Sitemap not picking up static pages (/folder/page.tsx), but works for dynamic pages ([slug]/page.tsx)

### ISSUE THREAD

**Issue by dominik-sfl** [iamvishnusankar/next-sitemap#829]
**Describe the bug**
Our sitemap seems to pick up all dynamic items, e.g. `/some-category-folder/[slug]/page.tsx` but our category pages are NOT included, e.g. `/some-category-folder/page.tsx`

**To Reproduce**
Not sure how to reproduce this error.

**Expected behavior**
Pick up all pages in our app directory.

**Screenshots**
-

**Additional context**

Not sure if it makes a difference, but we have a lot of our pages inside nextjs' invisible folders in round brackets, to just order things for us internally e.g. `/app/.../(folder)/category/page.tsx`

**Comment by soufianeelc** [comment]
Could you fix it ? I'm having the same issue

**Comment by OzzieOrca** [comment]
This sounds like it could be similar to https://github.com/iamvishnusankar/next-sitemap/pull/812.
