### ISSUE TITLE
siteUrl overwritten by non-trailing slash when trailingSlashes=false

### ISSUE THREAD

**Issue by thomcrielaard** [iamvishnusankar/next-sitemap#833]
**Describe the bug**
When trailingSlashes is set to false, but siteUrl is set to "yourdomain.com/", next-sitemap will automatically remove the trailing slash (see additional context on why I'm doing this). 

**To Reproduce**

1. Go to 'next.config.js' and set trailingSlashes to false (or leave it out for the default setting, which is false)
2. Go to 'next-sitemap.config.js' and set siteUrl to yourdomain.com/ (with a trailing slash)
3. Run the next-sitemap command
4. Check sitemap-0.xml. It now has removed the trailing slash from the domain you provided

**Expected behavior**
I would expect the siteUrl property to be dominant here, since this is manually added. All other URLs should still be generated without a trailing slash. 

**Screenshots**

**Additional context**
Admittedly, a bit of a weird configuration, but I don't see any alternatives to keep SEO tools satisfied. All relative URLs to the homepage go to "/", meaning they direct to your domain with a trailing slash. SEO tools don't really like it when there are no incoming URLs to your canonical page, thus if you make the canonical page "yourdomain.com" and direct all homepage links to "/" (and thus yourdomain.com/), the SEO tools will throw an error. To solve this, you can make the homepage canonical version "yourdomain.com/", even though the page will still be redirected to "yourdomain.com", which does keep the tools satisfied. All other pages can just be non trailing. I don't know if this is "the way to go", so if anyone has any suggestions please drop them down below :)

**Comment by comlaterra** [comment]
Is this repo abandoned?

**Comment by thomcrielaard** [comment]
It seems like it... I've tried to fix the issue myself, but don't have a lot of time and couldn't figure it out unfortunately

**Comment by thomcrielaard** [comment]
I see that the issue is closed since it is not planned, but it is present in the task list of @iamvishnusankar . Will this still be implemented? :)
