### ISSUE TITLE
Skip line between User-agent's in robots.txt

### ISSUE THREAD

**Issue by Nases** [iamvishnusankar/next-sitemap#84]
**Is your feature request related to a problem? Please describe.**
Many of the big companies have empty line between User-agent, Host and Sitemap in robots.txt.
E.g.
https://www.google.com/robots.txt
https://www.amazon.com/robots.txt
Not sure if this impacts anything but it should be a best practice.

**Describe the solution you'd like**
Have one line of empty space by default like:
```
# robots.txt
User-agent: *
Disallow: /exec/obidos/account-access-login
Disallow: /exec/obidos/change-style

User-agent: EtaoSpider
Disallow: /
```

**Comment by iamvishnusankar** [comment]
@Nases Apart from the readability standpoint, does this provide any functional value by adding new line to separate user agents?

**Comment by Nases** [comment]
@iamvishnusankar I don't think it does although just checked [Google's documentation](https://developers.google.com/search/docs/advanced/robots/create-robots-txt), they have line breaks between User-agents.

**Comment by iamvishnusankar** [comment]
@Nases Added support for better readability.
