### ISSUE TITLE
String "index" is stripped from the URL in the sitemap

### ISSUE THREAD

**Issue by blazzzk** [iamvishnusankar/next-sitemap#845]
**Describe the bug**
When generating the sitemap using next-sitemap version 4.2.3, URLs containing the word "index" (e.g., cool-product-index-test) are stripped of the "index" string in the generated sitemap.

**To Reproduce**

1. Set up a Next.js project (version 14, pages router).
2. Install next-sitemap version 4.2.3.
3. Create a page with "index" in the URL, e.g., pages/cool-product-index-test.js.
4. Generate the sitemap using npx next-sitemap.
5. Check the generated sitemap 

**Expected behavior**
The URLs in the sitemap should include the "index" word as in the original paths, for example, https://www.example.com/cool-product-index-test.

**Comment by melutovich** [comment]
@iamvishnusankar I'm also seeing this issue.  @blazzzk did you figure something out?

**Comment by blazzzk** [comment]
> @iamvishnusankar I'm also seeing this issue. @blazzzk did you figure something out?

@melutovich I only had a few urls impacted by this bug, so I haven't looked into it yet 😕
