### ISSUE TITLE
url in transform gives path for conditioning

### ISSUE THREAD

**Issue by Nases** [iamvishnusankar/next-sitemap#85]
**Describe the bug**
```js
const origin = 'https://example.com'
module.exports = {
   siteUrl: origin,
   transform: (config, url) => {
       return {
         loc: url,
         test: (url == origin) ? 'true' : 'false'  // returns false
    }
  },
}
```
test will always give false even though they are the same value.
test gives true only if I give the path not the actual url.
```js
{
   test: (url == '/') ? 'true' : 'false' // returns true
}
```
will give true in this case.

**Expected behavior**
url should give the actual url not the path for conditioning.

**Comment by iamvishnusankar** [comment]
@Nases `next-sitemap` is applying `trailingSlash` rules once the transformation is over. Transformation is done using the raw relative paths provided by `next.js`. I do agree that the naming `url` is bit confusing in the documentation. I've updated the doc to change `url` to `path` or `relative-path`.
