### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by gokaygurcan** [iamvishnusankar/next-sitemap#861]
Hi,

Considering the lack of involvement and acknowledgment from @iamvishnusankar and last meaningful commit being like 10 months ago, I have serious doubts that the project is still active. Can you please give a clear answer before more people tries to use it and end up in frustration? 

Or maybe convert it to an org and seek for maintainers, if you don't have time to maintain it yourself. Because it looks like a neat solution, but just kind of abandoned and that's just sad.

Best,
G.

**Comment by dominik-sfl** [comment]
I'm also curious to hear some updates!

**Comment by themeix** [comment]
Cant see any update since last 1 year

**Comment by thomcrielaard** [comment]
Totally agree, especially for a package which has over 340.000 weekly downloads it's a bit sad...

**Comment by iamvishnusankar** [comment]
@gokaygurcan , @dominik-sfl , @themeix , @thomcrielaard Please check #865

**Comment by thomcrielaard** [comment]
Thanks for the update Vishnu! Looking forward to weeing where this project is going :). If I have the time to look into the project myself I'll try to help you out with some PRs!
