### ISSUE TITLE
Sitemap for SSR rendered pages

### ISSUE THREAD

**Issue by Jbmanllr** [iamvishnusankar/next-sitemap#88]
Hi, it seems like your sitemap generator build the xml according to the pre rendered static pages, am i misleading or there is no way to generate it for pages using GetServerSideProps ?

**Comment by iamvishnusankar** [comment]
@Jbmanllr Please refer this reply: https://github.com/iamvishnusankar/next-sitemap/issues/68#issuecomment-752864017

**Comment by Jbmanllr** [comment]
Hi, thanks for the new feature! However im wondering how to have 'sitemap.xml' as an index sitemap for the others (ill have more than 50000 urls, way more)

**Comment by Jbmanllr** [comment]
Sorry if i'm not clear, i saw the pageSize option, however, i wondered if it's possible to apply the pagesize option to dynamics sitemaps, and for the static sitemap to act like an index for example:

sitemap.xml:
<?xml version="1.0" encoding="UTF-8"?>
  <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
      <loc>http://www.example.com/static_pages</loc> (mainly landing and category pages)
    </sitemap>
    <sitemap>
      <loc>http://www.example.com/server-sitemap-products-1</loc>
    </sitemap>
<sitemap>
      <loc>http://www.example.com/server-sitemap-products-2</loc>
    </sitemap>
<sitemap>
      <loc>http://www.example.com/server-sitemap-articles</loc>
    </sitemap>
  </sitemapindex>

**Comment by iamvishnusankar** [comment]
@Jbmanllr `next-sitemap` doesn't support sitemap index at this point. If you have more than 50K urls, you can use `next.js` url params to query from your database. Create `/pages/[sitemapId]/index.tsx` page and use `sitemapId` variable to query/paginate data from your server.
