### ISSUE TITLE
Throws error: Cannot read property 'pages' of undefined

### ISSUE THREAD

**Issue by madeleineostoja** [iamvishnusankar/next-sitemap#91]
**Describe the bug**
Running `next-sitemap` in a `postbuild` script errors out with the error 

```
Cannot read 'pages' of undefined

....Object.keys(manifest.build.pages)
							  ^
```

**To Reproduce**

1. Run `next build` in build and `next-sitemap` in postbuild
2. Wait for it to build

**Expected behavior**
next-sitemap should not throw an error

**Screenshots**
![Screen Shot 2021-01-13 at 5 29 47 PM](https://user-images.githubusercontent.com/6374876/104406782-f35f6b80-55c4-11eb-8468-5bdf02b2ada9.png)

**Comment by madeleineostoja** [comment]
Nevermind, I'd forgotten we'd set a custom build directory 🤦‍♀️

Opportunity for better DX: throw a helpful error in this case :)

**Comment by danny-stateside** [comment]
What happened with this error? I'm still getting it when the script runs

**Comment by frbl** [comment]
See the response in https://github.com/iamvishnusankar/next-sitemap/issues/117. The issue is most probably that you're using a different build directory than `.next`. Use the `sourceDir` option to specify your directory.

**Comment by thehackingknight** [comment]
Still getting the issue.

**Comment by frbl** [comment]
what is in your `next-sitemap.js` and in your `next.config.js`?
