### ISSUE TITLE
Working Example For Generating dynamic/server-side sitemaps

### ISSUE THREAD

**Issue by ItsCosmas** [iamvishnusankar/next-sitemap#92]
**Is your feature request related to a problem? Please describe.**
Yes, I don't seem to figure out how to generate dynamic server side sitemaps as the docs are not clear and no working example exists on the same.

**Describe the solution you'd like**
Providing a working example of this would be great.

**Comment by iamvishnusankar** [comment]
@ItsCosmas Hi, the example directory contains `dynamic-sitemap` example. https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx

**Comment by ItsCosmas** [comment]
Hello, I can't seem to get it working, on line 18 here:  https://github.com/iamvishnusankar/next-sitemap/blob/192a5f1f1557872dd475fe16dc640e40426f4b7b/example/pages/server-sitemap.xml/index.tsx#L18
How do we pass a dynamic link `loc: 'https://example.com/dynamic-path-2',` in a real scenario like `loc: https://example.com/blog/[id]` dynamic URL. 

Also I don't quite get this piece:
https://github.com/iamvishnusankar/next-sitemap/blob/192a5f1f1557872dd475fe16dc640e40426f4b7b/example/pages/server-sitemap.xml/index.tsx#L8

You have done a great job on this package but I think we could really use a working example on this one. Thanks.



Here's my non working code: `public/server-sitemap.xml/index.tsx`

```
import { getServerSideSitemap } from 'next-sitemap';
import { GetServerSideProps } from 'next';

export const getServerSideProps: GetServerSideProps = async (ctx) => {
	// Method to source urls from cms
	// const urls = await fetch('https//example.com/api')

	const fields = [
		{
			loc: `https://example.com`, // Absolute url
			lastmod: new Date().toISOString(),
			// changefreq
			// priority
		},
		{
			loc: `https://example.com/blog/[id]`, // dynamic url
			lastmod: new Date().toISOString(),
			// changefreq
			// priority
		},
		{
			loc: `https://example.com/category/[id]`, // dynamic url
			lastmod: new Date().toISOString(),
			// changefreq
			// priority
		},
	];

	return getServerSideSitemap(ctx, fields);
};

// Default export to prevent next.js errors
export default () => {};
```


And here is my `next-sitemap.js` :
```
module.exports = {
	siteUrl: `https://example.com`,
	changefreq: 'daily',
	priority: 0.7,
	sitemapSize: 5000,
	generateRobotsTxt: true,
	exclude: ['/server-sitemap.xml'],
	// Default transformation function
	transform: (config, path) => {
		return {
			loc: path, // => this will be exported as http(s)://<config.siteUrl>/<path>
			changefreq: config.changefreq,
			priority: config.priority,
			lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
		};
	},
	robotsTxtOptions: {
		additionalSitemaps: [`https://example.com/server-sitemap.xml`],
		policies: [
			{
				userAgent: '*',
				allow: '/',
			},
		],
	},
};
```

**Comment by iamvishnusankar** [comment]
@ItsCosmas I think you're totally mistaken with the concept of dynamic sitemap. The purpose of dynamic sitemap is to parse urls from your CMS/api and generate sitemaps based on it. 

So in the case of `https://example.com/blog/[id]` you are responsible for resolving the value from your api/cms.

This package consists of two mode of sitemap generation. 

1. **Static/Pre-Rendered sitemaps** : This method will generate sitemaps for all pre-render/static contents. If `next.js` is building your pages with url params(`https://example.com/blog/[id]`). `next-sitemap` will generate corresponding sitemaps by resolving the pre-rendered values for the pages.

2. **Dynamic sitemaps**: This method is to source data from your API/CMS. As data sourcing is out of the context of `next-sitemap`, its your responsibility to source the absolute urls for your sitemap.

**Pseudo Example**:

You can create an example page `pages/[sitemapId]/index.tsx` with [dynamic sitemap contents](https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx). And resolve sitemap-urls based on the url param.

`sitemapId === 'server-sitemap-1.xml'`  ===> Resolve urls for server-sitemap-1.xml
`sitemapId === 'server-sitemap-2.xml'`  ===> Resolve urls for server-sitemap-2.xml

And so on.

**Comment by ItsCosmas** [comment]
> @ItsCosmas I think you're totally mistaken with the concept of dynamic sitemap. The purpose of dynamic sitemap is to parse urls from your CMS/api and generate sitemaps based on it.
> 
> So in the case of `https://example.com/blog/[id]` you are responsible for resolving the value from your api/cms.
> 
> This package consists of two mode of sitemap generation.
> 
> 1. **Static/Pre-Rendered sitemaps** : This method will generate sitemaps for all pre-render/static contents. If `next.js` is building your pages with url params(`https://example.com/blog/[id]`). `next-sitemap` will generate corresponding sitemaps by resolving the pre-rendered values for the pages.
> 2. **Dynamic sitemaps**: This method is to source data from your API/CMS. As data sourcing is out of the context of `next-sitemap`, its your responsibility to source the absolute urls for your sitemap.
> 
> **Pseudo Example**:
> 
> You can create an example page `pages/[sitemapId]/index.tsx` with [dynamic sitemap contents](https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx). And resolve sitemap-urls based on the url param.
> 
> `sitemapId === 'server-sitemap-1.xml'` ===> Resolve urls for server-sitemap-1.xml
> `sitemapId === 'server-sitemap-2.xml'` ===> Resolve urls for server-sitemap-2.xml
> 
> And so on.

Thank you fro your response. it has cleared my misunderstanding.

**Comment by lukebennett88** [comment]
First again thank you for building this package @iamvishnusankar. Generating sitemaps seems like a pretty tricky problem in Next.js so really happy that someone has decided to tackle the problem to make it a bit easier.

Having said that, I agree with @ItsCosmas, an example of sourcing the info from a real API would definitely clear things up. I have a lot of questions.

I still don't really understand how the file at [`server-sitemap.xml/index.tsx`](https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx) is supposed to work.

Is the file name significant? It doesn't seem to be referenced in the `next-sitemap.js` config file. Is the package just looking for files in the pages directory that exports the `getServerSideSitemap` function?

In the example you've got a comment setting a variable called `urls` but it's never mentioned again, so not sure how to use it. Is it the same as `fields`?

e.g. do I write a function to generate all the server rendered pages? And is it just for server rendered pages, or static pages that are built dynamically (I think just server rendered, but I'm not sure)?

What if I have multiple types of server rendered pages (products and collections for example). Do I spread them into the same array or create and new file in the pages directory?

**Comment by iamvishnusankar** [comment]
@lukebennett88 You're welcome.

> I still don't really understand how the file at server-sitemap.xml/index.tsx is supposed to work. Is the file name significant?

No the file name is **NOT** significant. I mentioned it to make more obvious that it's a server side item. You can use any filename you want.(eg: `/awesome-page.xml/index.tsx`). The `.xml` extension in the file name is for `next.js` to generate and endpoint like `http://localhost:3000/awesome-page.xml`.

You can even use parametrised filename (eg: `/[sitemapId]/index.tsx`). And create `getServerSideSitemap` logic as follows.

```tsx
// pages/[sitemapId]/index.tsx

import { getServerSideSitemap } from 'next-sitemap'
import { GetServerSideProps } from 'next'

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  let fields = []

  if (ctx.params['sitemapId'] === 'awesome-sitemap-1.xml') {
    fields = [] // Logic for populating fields for http://localhost:3000/awesome-stiemap.xml
  } 

  else if (ctx.params['sitemapId'] === 'another-sitemap-1.xml') {
    fields = [] // Logic for populating fields for http://localhost:3000/another-sitemap-1.xml
  }

  return getServerSideSitemap(ctx, fields)
}

// Default export to prevent next.js errors
const DefaultPage = () => {}

export default DefaultPage
```

>  It doesn't seem to be referenced in the next-sitemap.js config file. Is the package just looking for files in the pages directory that exports the getServerSideSitemap function?

When using `getServerSideSitemap ` API you are actually building a `next-js` page. However, `getServerSideSitemap` overwrites server response type from `application/html` to `application.xml`. So no need to reference these files from `next-sitemap.js`. You are only required to add logic for sourcing urls and building fields for server side response.

> In the example you've got a comment setting a variable called urls but it's never mentioned again, so not sure how to use it. Is it the same as fields?

If you are building static/pre-rendered pages only. `next-sitemap` already knows about the endpoint from the build manifest. However, there are cases where the urls need to be parsed from an API/CMS. In this case, this package is unaware of the urls as sourcing data is out of it's context.

It is your responsibility to parse urls from your endpoint and build fields accordingly. See the following logic

```tsx
      // Sourced urls
      const urls = []

      // Fields
      const fields = urls.map((x)=> ({
        loc: x,
      }))
```

> What if I have multiple types of server rendered pages (products and collections for example). Do I spread them into the same array or create and new file in the pages directory?

See first part of this reply.

**Comment by lukebennett88** [comment]
Thanks for the detailed response!
I've managed to get the package working for my needs. 
I'll do my best to my a PR to the README and the example site if you're open to that?

**Comment by iamvishnusankar** [comment]
@lukebennett88 . Feel free to send a PR anytime :)

**Comment by Shofol** [comment]
@iamvishnusankar, what will be the entry for `additionalSitemaps` if I create dynamic page like this: `pages/[sitemapId]/index.tsx`

**Comment by soroushahrari** [comment]
> @iamvishnusankar, what will be the entry for `additionalSitemaps` if I create dynamic page like this: `pages/[sitemapId]/index.tsx`
> 
> And, this is not working: https://github.com/iamvishnusankar/next-sitemap/blob/master/example/pages/server-sitemap.xml/index.tsx

I have the same question. Currently I have +50k dynamic pages and the number is going to grow over time so I don't know the exact number of the dynamic sitemaps beforehand to add them to additionalSitemaps. Does robotsTxtOptions.additionalSitemaps accepts wildcard or is there any workaround for this?
I really appreciate your help.

**Comment by StanislavNemytov** [comment]
Don’t forget that sometimes you need to use generation functions with the addition of Legacy. For example getServerSideSitemapLegacy
