### ISSUE TITLE
lastmod undefined is added when autoLastmod is false

### ISSUE THREAD

**Issue by phuctm97** [iamvishnusankar/next-sitemap#94]
**Describe the bug**
When I set config `autoLastmod` to `false`, I expect `<lastmod>` doesn't appear at all in the `sitemap.xml` output. However, output `sitemap` has `<lastmod>undefined</lastmod>`. I'm not sure this is an expected behavior either.

**To Reproduce**

1. Set `autoLastmod` in `next-sitemap.js` to false.
2. Add `"postbuild": "next-sitemap"` to `package.json`.
2. Run `yarn build`.

**Comment by iamvishnusankar** [comment]
@phuctm97 Thanks for reporting this bug. Fixed :)

**Comment by phuctm97** [comment]
Oh, that's fast! Thanks, looking forward to the release.
