### ISSUE TITLE
Creating a sitemap for dynamic pages

### ISSUE THREAD

**Issue by qb-rivkyb** [iamvishnusankar/next-sitemap#98]
Is there a way for the sitemap to include dynamic pages? Looking to implement that in my site and don't see it in the docs.

Thanks! 😃

**Comment by iamvishnusankar** [comment]
If your dynamic page is a statically rendered, `next-sitemap` will take care of adding urls to generated sitemap without any additional configuration. And if your dynamic page is SSR, then you will have to take care of generating sitemaps using `getServerSideSitemap` API.

Check this [example](https://github.com/iamvishnusankar/next-sitemap/tree/master/example)
